### ISSUE TITLE
Typegen - predicate typegen to support configurable constants

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1014]
Now that predicates support configurable constants in #998, we should look to support them in typegen.

Predicates with configurable constants are instantiated like so:

https://github.com/FuelLabs/fuels-ts/blob/28c1cda969c2cf97519d9289798c18843dc3364b/packages/fuel-gauge/src/predicate-with-configurable.test.ts#L77

However the autogenerated predicate factory created using typegen doesn't offer any way of passing configurables:

https://github.com/FuelLabs/fuels-ts/blob/28c1cda969c2cf97519d9289798c18843dc3364b/packages/abi-typegen/src/templates/predicate/factory.hbs#L49-L62

We should be able to infer from the ABI that the predicate contains configurable constants and the types of them, and provide a way for them to be easily passed to the factory instance. This could be done by amending the `createInstance` signature should configurables be present.

**Comment by danielbate** [comment]
@FuelLabs/sdk-ts I'd be quite keen to pick this one up over the next week or so unless anyone has any objections?

**Comment by arboleya** [comment]
Fantastic, this is the issue I said I'd pick up yesterday on the sync, but you're more than welcome to do it yourself! ⚡

Predicates, Scripts, and Contracts will be practically the same. Since the code sharing between them should be prevalent, the three might fit in a single PR. Do you want to do all three?

I suspect we will end up with something like this:

```ts
export type {{capitalizedName}}Cofigurables { 
  ...
}

static createInstance(provider?: Provider, configurable?: {{capitalizedName}}Cofigurables) { 
  ... 
}

```

**Comment by danielbate** [comment]
@arboleya Ah apologies, I do remember you mentioning it now. If that's alright with you I'd really like to!

**Comment by arboleya** [comment]
No worries, man. Thank you.

If you need anything, just let me know.
