### ISSUE TITLE
Add "edit page" link on each page in documentation that would lead to the corresponding docs file in GitHub

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1017]
We can use GitHub's "edit file" functionality to do updates to our documentation whenever we see something we could improve. To streamline this, @arboleya proposed adding an edit icon to every page which would link to the corresponding .md file and put it in edit mode like [this](https://github.com/FuelLabs/fuels-ts/edit/master/apps/docs/src/guide/contracts/call-parameters.md).

**Comment by Dhaiwat10** [comment]
Want me to take this one up? @nedsalk
