### ISSUE TITLE
Add the ability to checkout a specific git branch as the source for the `forc-bin` binaries

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1019]
Right now, the `forc-bin` package is only able to fetch binaries from any of the official releases on the `sway` repo. 

We should make the package more flexible so that it lets us checkout a specific git branch on the `sway` repo if needed. Recently when working on #986, I faced the need to be using `forc` from a specific _unreleased_ git branch. I think we'll need to do this again whenever we have to upgrade `fuel-core` in the future.

**Comment by arboleya** [comment]
Good point.

At the moment, the `forc-bin` package is a simple wrapper that uses pre-compiled [downloaded] binaries.

If we'd start from a git branch, we'd need to build it from source.

Is that what you did manually?

**Comment by Dhaiwat10** [comment]
@arboleya Yes, precisely. I had to clone the `sway` repo on my machine, run `cargo build` and build the contracts by using those newly-buit binaries.
