### ISSUE TITLE
Some links to code snippets are broken in our docs

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1024]
If you click on 'See code in context' for any of the code snippets on https://fuellabs.github.io/fuels-ts/guide/contracts/inter-contract-calls.html, you will notice that the links are broken. eg. `https://github.com/FuelLabs/fuels-ts/blob/master/undefined#L1-L25`

**Comment by arboleya** [comment]
It looks like all `See code in context` links are broken. 🤔 

> cc @Torres-ssf
