### ISSUE TITLE
in Wallet project, pnpm build:all is broken when using local linked sdk

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#1026]
### What version of fuels-ts are you using?

pr-984

### Steps to Reproduce

in SDK side:

1- run `pnpm dev`
2- run `pnpm -r exec pnpm link --global --dir ./`

in Wallet side

1- enter in `deps.sh` file and enable linking with local fuels-ts
2- run `pnpm dev:crx`
  - after complete, stop the process... linking is working and done
3- run `pnpm build:all` 

you'll see this error: 
![image](https://github.com/FuelLabs/fuels-ts/assets/8636507/db2765f8-20e5-4be6-9703-10405fef5792)

this could be related to #765 

cc @arboleya

**Comment by arboleya** [comment]
Maybe related:
 - https://github.com/FuelLabs/fuels-ts/issues/909

**Comment by Torres-ssf** [comment]
@LuizAsFight is this problem still happening?

**Comment by LuizAsFight** [comment]
nope, thanks @Torres-ssf
