### ISSUE TITLE
TS SDK bytecode root function gives different result as Rust SDK / Sway functions

### ISSUE THREAD

**Issue by mauricewbr** [FuelLabs/fuels-ts#1027]
### What version of fuels-ts are you using?

Latest

### Steps to Reproduce

**TS SDK**
As we would expect from [this](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/src/util.ts) TS SDK code, the correct function to compute a bytecode root is:
```Typescript
const getContractRoot = (bytecode: BytesLike): string => {
  const chunkSize = 8;
  const chunks: Uint8Array[] = [];
  const bytes = arrayify(bytecode);

  for (let offset = 0; offset < bytes.length; offset += chunkSize) {
    const chunk = new Uint8Array(chunkSize);
    chunk.set(bytes.slice(offset, offset + chunkSize));
    chunks.push(chunk);
  }

  return calcRoot(chunks.map((c) => hexlify(c)));
};
```

**Rust SDK**
When looking at how the Rust SDK computes the bytecode root, we resort to the following function from [here](https://github.com/FuelLabs/fuels-rs/blob/master/packages/fuels-programs/src/contract.rs#L201):
```Rust
fn compute_contract_id_and_state_root(
        binary: &[u8],
        salt: &Salt,
        storage_slots: &[StorageSlot],
    ) -> (ContractId, Bytes32, Bytes32) {
        let fuel_contract = FuelContract::from(binary);
        let code_root = fuel_contract.root();
        let state_root = FuelContract::initial_state_root(storage_slots.iter());

        let contract_id = fuel_contract.id(salt, &code_root, &state_root);

        (contract_id, code_root, state_root)
    }
```
... which uses the `.root()` function and provides the `code_root` as a parameter of the struct.

**Sway**
In Sway, there is a separate function using opcodes to compute it. [This](https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/external.sw#LL8C1) function right here:
```Sway
pub fn bytecode_root(contract_id: ContractId) -> b256 {
    let root: b256 = ZERO_B256;

    asm(root_addr: root, target: contract_id.value) {
        croo root_addr target;
        root_addr: b256
    }
}
```

### Expected Behavior

We would expect that all three functions compute the **exact same** bytecode root, given the same contract id as input.

### Actual Behavior

The Rust SDK and Sway functions yield the same result. Unfortunately, the TS SDK function does not.

**Comment by Dhaiwat10** [comment]
@mauricewbr can you please check if this has been fixed for you? Thanks :)
