### ISSUE TITLE
Read transaction parameters from chain and not hardcoded values

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#1050]
### Motivation

The max Inputs setting for Transaction Parameters (aka Consensus Parameters) can be defined in fuel-core chain config:
https://github.com/FuelLabs/fuels-ts/blob/cm/issue-1015/.docker/fuel-core/chainConfig.json#L275

But the TS-SDK hardcodes a value of 255 which just happens to match that of the chain config:
https://github.com/FuelLabs/fuels-ts/blob/cm/issue-1015/packages/abi-coder/src/constants.ts#L21

### Possible implementations

We should update the functionality to use the actual value defined in the local chain if possible.

**Comment by Dhaiwat10** [comment]
@camsjams this value would have to be fetched asynchronously from the node just like the rest of the consensus parameters, right? Reading directly from a `chainConfig` file would only work for a local node.

**Comment by digorithm** [comment]
@Dhaiwat10 @camsjams should this be closed?

**Comment by digorithm** [comment]
That's what I thought. Dhai merged some PR related to this. Not sure about @Torres-ssf's work, though. I'll wait for him to update us before closing this issue.

**Comment by Torres-ssf** [comment]
@digorithm Some constants were purged here:

- https://github.com/FuelLabs/fuels-ts/pull/1272
- https://github.com/FuelLabs/fuels-ts/pull/1271

However, it seems that the hardcoded value for `MAX_INPUTS` is still being used to calculate `VM_TX_MEMORY`.

**Comment by Dhaiwat10** [comment]
Like @Torres-ssf mentioned, we still need to purge this one last constant. Filed an issue for it: #1313 

I guess we can close this issue though, since the supporting work for this has been done already
