### ISSUE TITLE
RFC: Fuel ASM Developer Experience

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#1064]
### Motivation

The usage of Fuel-ASM could use some dx improvements

Some key points:
- Programs are a list of FUEL-VM operations
- A single instruction is just an OpCode with some params
- Program instructions can be converted to a `Uint8Array`
- Program instructions can be converted to a hex string, which can be used by fuel vm
- Its possible to convert these hex and byte values back into instructions if they are fuel-asm compliant
- Writing a script in fuel-asm is often more space and memory efficient than a Sway script

### Usage example

I think one option is to create a wrapper class that behaves like an Array.

```typescript
// the name AsmProgram is up for debate
// creates a program empty instruction set
const theProgram = new AsmProgram();

// creates a program set with these instructions
const theProgram = new AsmProgram([ 
     Opcode.move(0x10, 0x01)
]); 


// push one instruction
theProgram.push(Opcode.ret(REG_ONE)) 
// maybe just need extend

// push multiple instruction
theProgram.extend([  // maybe `concat` instead?
      Opcode.ecr(0x10, 0x11, 0x12),
      Opcode.ret(REG_ONE),
]);

// convert to Uint8Array
theProgram.toBytes()

// convert to hex string (for use as a script in fuel vm)
theProgram.toHex()
```

Also recover a program
```typescript
// convert hex string into program
const myProgram = theProgram.fromHex(someString)

// convert byte array into program
const myProgram = theProgram.fromBytes(someBytes)

// get instructions
const instructions = myProgram.getInstructions();
// returns back an array of instructions:
assert(instructions === [Opcode.noop()]);
```

**Comment by luizstacio** [comment]
I think just `new Program` would be good if possible.

**Comment by Torres-ssf** [comment]
This looks good @camsjams

**Comment by arboleya** [comment]
Very concise. I'd favor "AsmProgram" or something else over "Program" to avoid conflicts with the program package.
