### ISSUE TITLE
Retry mechanism

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-ts#1078]
We should support an optional, configurable parameter to enable retries when sending a transaction to the node. This mechanism's design and API are part of this work; nothing in mind yet!

**Comment by arboleya** [comment]
Great idea; transient failures should indeed be accounted for. We could have a simple option like this (below) and have an internal retry pattern strategy with exponential back-off.

```ts
// if nothing is specified, we could have a default maxRetries=5
contract.functions.xyz(params).call({ maxRetries: 5 });
```

**Comment by digorithm** [comment]
Nope, not yet. This API looks good to me!

**Comment by nedsalk** [comment]
What about a global fuels.config.ts file in addition to @arboleya's proposal?

```js
{
 maxRetries: 5,
 txParams: {
  gasPrice: 2
 },
 predicates: {
  maxRetries: 2,
  txParams: {
   gasPrice: 1
  }
 }
}
```

**Comment by digorithm** [comment]
That's a lot of complexity for very little gain. The JS ecosystem already suffers from *way* too many config files, I'd rather not contribute to that, haha. 

And by very little gain I mean: gas price and many other transaction related configurations are mostly configured per call, usually being dynamically changed very quickly; often gas price being queried from external sources before a call happens. It isn't something that's set one time and the user rarely touches it. Retries does fit in this behaviour, though. But adding a whole new config file for just this value isn't justifiable.

**Comment by nedsalk** [comment]
Haha, yeah, makes sense. However, having to specify retries on a per-call basis might be cumbersome. A per-program config object passed via the constructor would alleviate some of that pain, so I think it's worth considering.
```ts
const myContract = new Contract(theAbi, ...whateverElse...,
 {
 maxRetries: 5, 
 onCallFail: async () => await notifyTheWhiteHouse()
 })
```
The `onCallFail` is just an example of how easily extendable this config object would be.
