### ISSUE TITLE
 Lack of Explanation for fuel-gauge in README

### ISSUE THREAD

**Issue by Ifechukwudaniel** [FuelLabs/fuels-ts#1100]
Hello,

I've been exploring the fuels-ts repository and noticed that the README for the fuel-gauge package doesn't provide a clear explanation of what fuel-gauge does.

Could you please update the README to include this information? This would greatly improve the understandability of the project and assist developers in navigating the repository.

Thank you for your attention to this matter.

**Comment by Dhaiwat10** [comment]
Hi @Ifechukwudaniel we haven't included a description for `fuel-gauge` in the readme since it is an internal package containing mostly test suites. It is not for consumption by end users.
