### ISSUE TITLE
Missing README for fuels Package

### ISSUE THREAD

**Issue by Ifechukwudaniel** [FuelLabs/fuels-ts#1101]
Hello,

I've been exploring the fuels-ts repository and noticed that there is no README file for the fuels package.

Could you please add a README for the fuels package? This would greatly improve the understandability of the project and assist developers in navigating the repository.

Thank you for your attention to this matter.

Best regards

**Comment by arapzz** [comment]
great

**Comment by Ifechukwudaniel** [comment]
Thanks
