### ISSUE TITLE
Implement new Error handling package

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1110]
Currently there is no standardized way to throw an error in the SDK. Rather, wherever an error has to be thrown, it gets thrown with `throw new Error(message)`, e.g.:
```ts
if (!gqlTransaction) {
  throw new Error('transaction not found');
}
```
This issue serves as a place to specify and implement _the_ way to throw exceptions.
My initial idea was to create custom errors like this: `new TransactionNotFoundError()`, `new EncodingFailedError()`, etc. However, after discussing privately with @arboleya and @LuizAsFight, they proposed a better way, which is to use one error class that has a `code` field that describes which error code it is:
```ts
  throw new SdkError("TransactionNotFound"); // typesafe string literals
```
or
```ts
throw new SdkError(SDK_ERRORS.TransactionNotFound); // enum of error codes
```

where `SdkError` is:
```ts
export class SdkError extends Error {
code: ERROR_CODES;
 constructor(code: ERROR_CODES, message?: string) {
  super(message);
  this.code = code;
  this.name = "SdkError";
 }
}  

type ERROR_CODES = 
| "TransactionNotFound" 
| "EncodingFailed"
| "NodeUnreachable"   
```

I'm a fan of the first approach as the user just has to import the `SdkError` and write the error code string, whereas in the second approach one has to import the `SDK_ERRORS` enum alongside `SdkError` every time an error has to be thrown. We can achieve the same level of type safety by resorting to string literals instead of enum values.

One concern that I have is error code ownership. Ideally each package should itself define what its failure modes are (e.g. `EncodingFailed` is part of the `abi-coder` package and it should be defined there, not somewhere else). If we do it like in the examples above, then we'll have to define the error codes in the same package where the `SdkError` class is defined, which is less than ideal. Maybe making it generic somehow (`class SdkError<T extends TemplateErrorMessage>`) would solve this issue, but I can't come up with an idea on how to properly do it without resorting to a lot of boilerplate.
One way to do it that may be clean enough (although it breaks error code ownership) would be to define error codes for each package separately and unite them in the `ERROR_CODES` type:
```ts
type AbiCoder_Error_Code = "EncodingFailed";
type Provider_Error_Code = "NodeUnreachable";

type ERROR_CODES = AbiCoder_Error_Code | Provider_Error_Code;
```
This looks simple and good enough.

Another **important** thing to keep in mind is that we should strive towards synchronizing the error naming with the rust sdk.

After we define this, we'll have to update our documentation to contain all the errors and their explanations. However, as @danielbate pointed out, we should save the documentation updating part for when typedoc is ready.

Please add your thoughts.

**Comment by nedsalk** [comment]
A possible solution for error code ownership is to make the `SdkError` abstract and have each package define their own _package_ error:
```ts
// sdk-error.ts
export abstract class SdkError<T extends string> extends Error {
  code: T;
  constructor(code: T, message?: string) {
    super(message);
    this.code = code;
  }
}
```

```ts
// abi-coder/abi-coder-error.ts

type ErrorCode = 'InvalidData' | 'TypeNotFoundOnAbi';

export class AbiCoderError extends SdkError<ErrorCode> {
  constructor(code: ErrorCode, additional_message?: string) {
    super(code, additional_message);

    this.name = 'SdkError/AbiCoder';
  }
}
```
And the same in other packages (`ProviderError`, `ContractError`, ...).

This would strike a middle line between excessive stub error classes like `TransactionNotFoundError` and having one class to rule them all `SdkError` that knows more than it should know.

**Comment by arboleya** [comment]
Let's not worry about code ownership; it will only worsen the problem.

Having everything condensed is easier to maintain.

Error handling can be simple.

---

Single package:
```
packages/errors
└── src
    ├── error-codes.ts
    └── index.ts
```

Single enum:
```ts
export enum ErrorCodes {
  // provider
  INVALID_URL = 'invalid-url',

  // wallet
  INSUFFICIENT_BALANCE = 'insufficient-balance',

  // coder
  // ...
}

```

Single class:
```ts
import { ErrorCodes } from './error-codes';

export * from './error-codes';

export class FuelError extends Error {
  static readonly CODES = ErrorCodes;
  static parse(e: unknown) {
    return e as FuelError;
  }

  code: ErrorCodes;
  constructor(code: ErrorCodes, message: string) {
    super(message);
    this.code = code;
  }
}
```

---

Internal usage:
```ts
import { FuelError, ErrorCodes } from '@fuel-ts/error';

export function singleImport() {
  throw new FuelError(FuelError.CODES.INVALID_URL, 'Invalid URL');
}

export function multipleImports() {
  throw new FuelError(ErrorCodes.INVALID_URL, 'Invalid URL');
}

```
---
External usage:
```ts
import { FuelError, Provider } from 'fuels';

type Locale = 'PT_BR' | 'BS_BA';

const currentLocale: Locale = 'PT_BR';

const i18nDict = {
  PT_BR: {
    [FuelError.CODES.INVALID_URL]: 'Endereço inválido',
    [FuelError.CODES.INSUFFICIENT_BALANCE]: 'Saldo insuficiente',
  },
  BS_BA: {
    [FuelError.CODES.INVALID_URL]: 'Nevažeća adresa',
    [FuelError.CODES.INSUFFICIENT_BALANCE]: 'Nedovoljan balans',
  },
};

function translateError(e: unknown) {
  const { code } = FuelError.parse(e)
  return i18nDict[currentLocale][code];
}

(function main() {
  try {
    const p = new Provider('0004:tƨoʜlɒɔol//:qttʜ');
    console.log(p);
  } catch (e) {
    const prettyError = translateError(e);
    console.log({ prettyError });
  }
})();
```
