### ISSUE TITLE
Remove ability to get function via signature?

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1111]
Do we need to expose a function's signature to the user at all? How I understand it from https://specs.fuel.network/master/abi/fn-selector-encoding.html, it's only being used as a means of getting the function selector necessary for identifying the function on the VM.

As far as user experience goes, the users will be accessing functions on an `Interface` either via dot notation or `getFunction(fnName)` method :
```ts
const myFn_dot_notation =  abiInterface.functions.array_of_structs;
const myFn_array_of_codes = abiInterface.getFunction('array_of_structs');
```
 I don't see a user ever composing function signatures to get functions via them:
```ts
const myFn = abiInterface.getFunction('array_of_structs(a[s(str[3],e(u64,bool,bool));3]')
``` 
But this is what we're currently giving the user the ability to do.

So, the name of the function is what the user will be using to interact with programs/interfaces, and the encoded selector is what will be used where encoding is necessary. If the user wants to do their own thing with encoding, they have selectors available that we expose on a `FunctionFragment`. However, I don't see a user ever needing the signatures and I'd remove them altogether from the `FunctionFragment` and just calculate them on `FunctionFragment` creation to get the selector which is the end goal. One less thing to expose, one less thing to test in `interface.test.ts`.

**Comment by arboleya** [comment]
I don't see any problems with this suggestion, but it is also not causing problems.

I will close this for now; feel free to re-open it as a discussion if it becomes relevant.
