### ISSUE TITLE
The 'versions' section in our docs is incorrect sometimes

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1119]
As reported in #1093, with some releases, the versions section in our docs shows incorrect versions (in this case - 0.0.0 everywhere). The current release seems to be fine, but this should be investigated regardless.

![](https://user-images.githubusercontent.com/9806174/252155456-6d0869e5-477f-4739-a592-5c1750d003c2.png)

**Comment by arboleya** [comment]
Perhaps this was a transient error when integrating with the `@fuel-ts/versions` package before all fixes from https://github.com/FuelLabs/fuels-ts/pull/1055 were incorporated. I might be wrong, so it's good to watch it closely.

Another possible reason would be the timing that things occur on the related workflow.

> cc @Torres-ssf

**Comment by Torres-ssf** [comment]
Yes, @arboleya this error was fixed on #1075. But the release (when docs are published) only happened at #1099. 

I also agree that it is worth watching closely.
