### ISSUE TITLE
Move assertions outside of code snippets

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1138]
I would like to see assertions moved outside of the code snippet. I believe they add unnecessary noise and complexity to a code snippet where the purpose is to add context to documentation.

For example in [the following commit ](https://github.com/FuelLabs/fuels-ts/pull/1136/commits/75bc7c3445ed481ddcc4a27703e746dbd6f31040#diff-c8952cab6fb342bdde35bb2a860cd47653527b1c519b210798deae7355564e10) the assertion is being used to explain the output of the function call. However this may not be immediately obvious to someone not familiar with jest assertion syntax.

Should we need to display the function output, this could be done by adding a comment to the snippet (as I believe is more common in other documentation): 

```ts
    // #region read-only-call-1
    const { value } = await contract.functions.echo_u8(15).get();
    // 15
    // #endregion read-only-call-1
    expect(value).toEqual(15);
```

So the documentation would show the following snippet:

```ts
    const { value } = await contract.functions.echo_u8(15).get();
    // 15
```

Rather than:

```ts
    const { value } = await contract.functions.echo_u8(15).get();
    expect(value).toEqual(15);
```

**Comment by danielbate** [comment]
@Torres-ssf any thoughts on this as I know you've worked alot with the docs and snippets

**Comment by nedsalk** [comment]
This makes sense. The "usage" examples shouldn't be showing something that's not representative of actual real-world usage.

**Comment by maschad** [comment]
Let's re-visit this once we've come to consensus around the [discussion here](https://github.com/FuelLabs/fuels-ts/discussions/2159#discussion-6556230)

**Comment by arboleya** [comment]
Closing — revamped snippets won't contain test assertions.
 - https://github.com/FuelLabs/fuels-ts/issues/2399
