### ISSUE TITLE
Make the `TransactionResponse.waitForResult` method private

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1146]
This is just a DX nit-pick:

I was building something using our SDK and came across this from the auto-complete when trying to log the response from a transaction:
![image](https://github.com/FuelLabs/fuels-ts/assets/39617427/88c674be-d11d-40c9-90c2-0d17f398cea4)

This can confuse new SDK users a little bit. I propose hiding the `waitForResult` method from the users since `wait` is just a wrapper around it anyways and calls `waitForResult` internally on top of some error handling. No one should ever need to _just_ call `waitForResult` in their code: https://github.com/FuelLabs/fuels-ts/blob/51d13e32c5de7cb59d615d610c1332d7b3da64fb/packages/providers/src/transaction-response/transaction-response.ts#L203C12-L212

**Comment by nedsalk** [comment]
I don't know the internals fully, but to me it feels a bit off to actually even have `.wait()` and `fetch()` on a `TransactionResponse` class. Shouldn't a `WhateverSomethingResponse` class be a result of some fetching that happened somewhere else and not be the one fetching? We should _maybe_ rethink the naming or, if the naming is actually correct, add some documentation on why this specific naming is correct.

**Comment by danielbate** [comment]
This has been superseded by the DX change in #2692.
