### ISSUE TITLE
Rename `createInstance` to `deployInstance` for scripts/predicates typegen factories

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1149]
Follow-up from #1093:

Since the `createInstance` method exposed by the factories for scripts and predicates _*deploys*_ a new instance of the respective script/predicate, and doesn't only _create_ an instance which could very well be local/already deployed - I think this renaming makes sense.

`deployInstance` much more accurately describes what this function does, IMO.

![image](https://github.com/FuelLabs/fuels-ts/assets/39617427/d0b213b7-ab11-4490-ab61-1a65b6b563a3)

Any thoughts? @FuelLabs/sdk-ts

**Comment by arboleya** [comment]
What do you mean? Scripts and Predicates are not deployable. 🤔

**Comment by Dhaiwat10** [comment]
Never mind, I think this naming makes sense they cannot really be deployed like contracts. And we don't have bytecodes for contracts included in the factories, so this isn't applicable there yet. Closing this!

**Comment by Dhaiwat10** [comment]
> What do you mean? Scripts and Predicates are not deployable. 🤔

Beat me to it 😅

**Comment by Dhaiwat10** [comment]
Will re-open this for contracts if we end up working on #1150
