### ISSUE TITLE
Refact `LiquidityPool` contract documentation page and tests

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1186]
Since after `fuel-core 0.20` we can no longer have `ContractId` and `AssetId` with identical values, we need to update the test case that makes use of the Liquidity Pool contract, and its related [documentation page](https://fuellabs.github.io/fuels-ts/guide/cookbook/deposit-and-withdraw.html).

> Follow-up from https://github.com/FuelLabs/fuels-ts/pull/1112

**Comment by arboleya** [comment]
Completed via #1591.
