### ISSUE TITLE
Support heap types (`Vector`, `Bytes`, `StdString`) return from scripts

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#1187]
### Motivation

Requirements:
- Vectors can be returned from Contracts https://github.com/FuelLabs/fuels-ts/issues/933
- Bytes can be sent and returned from Contracts https://github.com/FuelLabs/fuels-ts/issues/1188
- Vectors can be sent to Scripts https://github.com/FuelLabs/fuels-ts/pull/1046
- Bytes/RawSlices can be sent to Scripts https://github.com/FuelLabs/fuels-ts/issues/1274
- StdStrings can be sent and returned from Contracts https://github.com/FuelLabs/fuels-ts/issues/1276

See also: https://github.com/FuelLabs/fuels-rs/issues/866

### Possible implementations

- Add return for Vectors for Scripts
- Add return for Bytes for Scripts
- Add return for RawSlice for Scripts
- Add return for StdStrings for Scripts

**Comment by Dhaiwat10** [comment]
Partially blocked: https://github.com/FuelLabs/fuels-rs/issues/866#issuecomment-1695867986

**Comment by danielbate** [comment]
This was fixed by #2050. As @Voxelot mentions there is still an issue with `raw_slice`, however we have that tracked individually in #1344. So will close this issue.
