### ISSUE TITLE
Push API Documentation files to separate branch for access by Docs Hub

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1198]
**Issue**
The docs hub builds out pages by parsing documentation sub directories for each repository (SDKs, Sway etc) and generating pages for `.md` files _(very high level explanation)_. As the TS SDK doesn't commit API documentation to source, the docs hub must build the TS SDK during it's own build process in order to run TypeDoc and access the generated API documentation markdown files. This is prone to errors as the docs hub build process is then tightly bound to our own.

**Proposed Solution**
We should instead still be able to provide the required markdown files and `links.json` to the docs hub without committing them to source. I would like to add an additional step to the CI that pushes the files to an Amazon S3 bucket for a successful `master` build. Then also adding a script to the SDK that can retrieve the files and add them to `src` to be parsed by the docs hub, rather than built.

**Comment by arboleya** [comment]
Would it be easier to push the docs dir to a fixed `docs` branch?

IIRC, some frontend docs are also being pulled via git submodules.

**Comment by danielbate** [comment]
@arboleya That's a much better idea 👍🏻
