### ISSUE TITLE
Error handling: what to do with @ethersproject/logger?

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1207]
Follow-up after #1153.

What should we do with the usage of `@ethersproject/logger` for throwing errors? Currently, throwing errors is done in two ways inside of the SDK, either via throw new Error(...) or logger.throw(...). 

With the merging of #1153, we have a standardized way of throwing errors via `new FuelError(...)` and we need to start doing #1156. Should we just get rid of `@ethersproject/logger` as it was, as far as I can tell, only used in conjunction with our `versions` package to log the version alongside the error? Now `FuelError` has the SDK version info on it directly and I don't see the need for having the `@ethersproject/logger` dependency.

**Comment by danielbate** [comment]
I agree that following #1153 we should now deprecate the usage of `@ethersproject/logger` in place of using a `FuelError`

**Comment by Dhaiwat10** [comment]
I think we can move to `FuelError` completely
