### ISSUE TITLE
warning in console: `fragment with name receiptFragment already exists`

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#1218]
### What version of fuels-ts are you using?

0.53.0

### Steps to Reproduce

we have this warning in dapps when importing `fuels`

```
Warning: fragment with name receiptFragment already exists.
graphql-tag enforces all fragment names across your application to be unique; read more about
this in the docs: http://dev.apollodata.com/core/fragments.html#unique-names 
```

we already renamed fragments in dapp side to make sure wasn’t duplicated, but didn’t fix

it's a warning, not breaking the code, but it's worth fixing

**Comment by danielbate** [comment]
Are there any additional repro steps required? I have installed fuels 0.53.0 [here](https://github.com/danielbate/fuels-0.53.0-duplicate-fragment) but not receiving this warning.

**Comment by arboleya** [comment]
We should try replicating the problem in isolation with a unit test _or_ an empty application.

A unit would be best, but another easy way is to branch off from `master` and use the `apps/demo-nextjs` as our _guinea pig_.

**Comment by danielbate** [comment]
Same outcome in [this branch](https://github.com/FuelLabs/fuels-ts/tree/db/chore/next-app-0.53.0) of the SDK which I've added fuels 0.53.0 to `apps/demo-nextjs`

**Comment by arboleya** [comment]
I did it yesterday, too. No luck.

Maybe @LuizAsFight has the recipe to replicate the issue on this demo app.

**Comment by LuizAsFight** [comment]
it's happening in the wallet. the difference can be that the wallet also has a graphql setup, so you might need to add it in the project you're trying to repro

**Comment by danielbate** [comment]
May need some more info @LuizAsFight or can jump on a call.

I have a Next application running an Apollo GQL client querying a local testnet and can not reproduce as of yet.

**Comment by LuizAsFight** [comment]
can't reproduce this anymore, looks like something from 0.53.0 to now has fixed the issue 

I'm closing it, thank you guys for jumping in this one 🥇 

@danielbate @arboleya
