### ISSUE TITLE
Implement documentation version control

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1224]
Currently we are only displaying the latest versions of the documentation, we should also look to support other versions. This is important for users of the SDK to understand breaking changes, and especially on testnet as we are supporting multiple versions of the fuel core.

On new releases of the the TS SDK, we should also push to a version specific directory e.g. `apps/docs/src/versions/0.1.0/{guide,api,something}`. We can then look to support this within our Vitepress application. Currently Vitepress is running off the master branch, but we may want to move this to the `docs` branch that the docs hub is using, as this also commits the Typedoc generated markdown files to source.

**Note:** we still need to support `apps/docs/src/api` and `apps/docs/src/guide` for the latest version of our documentation otherwise we introduce breaking changes to the docs-hub.

The following tasks are required:

- [ ] Push built documentation to versioned directories in GitHub workflow
- [ ] Support the versioned directories in Vitepress application
- [ ] Retroactively push and support previous versions of the the SDK documentation

**Comment by danielbate** [comment]
cc @sarahschwartz not sure if this is something we'd want to support in the docs hub, but we'll ensure not to introduce breaking changes

**Comment by arboleya** [comment]
@danielbate Good one.

Even if breaking changes are needed, they would be minimal.

For example, having a `latest` dir added to the mix.

Not sure, though. I am just thinking out loud.

```shell
docs
└── dist
    ├── ...
    ├── 0.53.0
    ├── 0.54.0 # last version
    └── latest # symlink to 0.54.0?
```

**Comment by danielbate** [comment]
@arboleya this is true, I need to go take a look at the docs hub, it is definitely doing some kind of validation on our directory structure before importing files fro `src`.

Or yes, as you mention, we keep that completely separate and only push versions to `dist`.

**Comment by danielbate** [comment]
Closing this as the docs hub handles versioning via tagged submodules. Anything we implement needs to be supported by the wider eco system so this makes most sense for now.
