### ISSUE TITLE
Is there a way to get current gas price?

### ISSUE THREAD

**Issue by BladeRunner713** [FuelLabs/fuels-ts#1229]
### Motivation

Just like getFeeData() in Ethers.js

**Comment by digorithm** [comment]
Yes: see the `Provider` API, [this method does it](https://github.com/FuelLabs/fuels-ts/blob/master/packages/providers/src/provider.ts#L313).

For faster response from us, please use the [official forum](https://forum.fuel.network/) or our Discord server; we're always hanging out there!
