### ISSUE TITLE
Dry run fails `Error: Cannot read properties of undefined (reading 'status')`

### ISSUE THREAD

**Issue by sdankel** [FuelLabs/fuels-ts#1245]
### What version of fuels-ts are you using?

0.56.1

### Steps to Reproduce

When it's a dryRun we don't receive the gqlTransaction but only receipts

![image](https://github.com/FuelLabs/fuels-ts/assets/47993817/80dbed49-e667-46a5-9314-01aabd5db261)

1. On this branch: https://github.com/FuelLabs/sway-playground/pull/34
2. Run the app, set toolchain to `nightly` in the dropdown, and add this sample contract:

```
// ANCHOR: body
contract;

use std::hash::*;

////////////////////////////////////////
// Event declarations
////////////////////////////////////////
//
// Events allow clients to react to changes in the contract.
// Unlike Solidity, events are simply structs.
//
/// Emitted when a token is sent.
struct Sent {
    from: Address,
    to: Address,
    amount: u64,  
}

////////////////////////////////////////
// ABI method declarations
////////////////////////////////////////
/// ABI for a subcurrency.
abi Token {
    // Mint new tokens and send to an address.
    // Can only be called by the contract creator.
    #[storage(read, write)]
    fn mint(receiver: Address, amount: u64);

    // Sends an amount of an existing token.
    // Can be called from any address.
    #[storage(read, write)]
    fn send(receiver: Address, amount: u64);
}

////////////////////////////////////////
// Constants
////////////////////////////////////////
/// Address of contract creator.
const MINTER = Address::from(0x9299da6c73e6dc03eeabcce242bb347de3f5f56cd1c70926d76526d7ed199b8b);

////////////////////////////////////////
// Contract storage
////////////////////////////////////////
// Contract storage persists across transactions.
storage {
    balances: StorageMap<Address, u64> = StorageMap::<Address, u64> {},
}

////////////////////////////////////////
// ABI definitions
////////////////////////////////////////
/// Contract implements the `Token` ABI.
impl Token for Contract {
    #[storage(read, write)]
    fn mint(receiver: Address, amount: u64) {
        let sender = msg_sender().unwrap();
        let sender: Address = match sender {
            Identity::Address(addr) => {
                assert(addr == MINTER);
                addr
            },
            _ => revert(0),
        };

        // Increase the balance of receiver
        storage.balances.insert(receiver, storage.balances.get(receiver).try_read().unwrap_or(0) + amount);
    }

    #[storage(read, write)]
    fn send(receiver: Address, amount: u64) {
        let sender = msg_sender().unwrap();
        let sender = match sender {
            Identity::Address(addr) => addr,
            _ => revert(0),
        };

        // Reduce the balance of sender
        let sender_amount = storage.balances.get(sender).try_read().unwrap_or(0);
        assert(sender_amount > amount);
        storage.balances.insert(sender, sender_amount - amount);

        // Increase the balance of receiver
        storage.balances.insert(receiver, storage.balances.get(receiver).try_read().unwrap_or(0) + amount);

        log(Sent {
            from: sender,
            to: receiver,
            amount: amount,
        });
    }
}
// ANCHOR_END: body
```

3. compile and deploy this example contract to beta-4
4. In the right-side drawer, give the inputs:

receiver:
```
{
    "value": "0xd5579c46dfcc7f18207013e65b44e4cb4e2c2298f4ac457ba8f82743f31e930b"
}
```

amount:
`1`

<img width="696" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/47993817/3fc98ec5-b7d1-4b80-bbb4-8881ae353586">

5. make sure the toggle is set to DRY RUN
6. click call

### Expected Behavior

Expected an error that the script reverted because of an invalid address

### Actual Behavior

`Error: Cannot read properties of undefined (reading 'status')`

**Comment by Torres-ssf** [comment]
This appears to be the same error described on https://github.com/FuelLabs/fuels-ts/issues/1236

**Comment by arboleya** [comment]
It seems like the same problem is reported here:
 - https://forum.fuel.network/t/typeerror-cannot-read-properties-of-undefined-reading-status/3047

**Comment by Torres-ssf** [comment]
After doing some investigation I identified that the error is being thrown from here on line `132`:
https://github.com/FuelLabs/fuels-ts/blob/e49d63c0e4661df8d9e3c704347afe0f3685ea38/packages/program/src/contract-call-script.ts#L129-L134

It is coming from here on line `113`:
https://github.com/FuelLabs/fuels-ts/blob/e49d63c0e4661df8d9e3c704347afe0f3685ea38/packages/program/src/script-request.ts#L111-L120

This is happening because the `new ScriptResultDecoderError` tries to access `result.gqlTransaction.status`, but `result.gqlTransaction` does not seem to exist.

@camsjams I notice that this touches on one of your last PRs #1183, does it ring a bell?

I could not make sense of this error.

**Comment by Torres-ssf** [comment]
@camsjams Yes, I agree. A question; why do we throw an error if the  `result.code` is different than `0` ?
