### ISSUE TITLE
Method for setting the configurables on a predicate after instantiation

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuels-ts#1251]
### Motivation

When a new `Predicate` is created there is an optional param for configurables.

It would be nice to have a method similar to `setData` (which is used for the `main()` function of the predicate) to set the configurables.
This allows us to create a predicate and overwrite its config, to say, generate an address of the predicate, change the config, check the new predicate address rather than create a new instance each time with different configurables.

I believe the Rust SDK exposes a method which allows you to set the configurables after creating a new type.

### Usage example

Code reference can be found in the docs [here](https://fuellabs.github.io/fuels-ts/guide/predicates/predicate-with-configurable-constants.html#modifying-the-whitelist) (predicate-with-configurable-constants.html#modifying-the-whitelist)

### Possible implementations

Method (builder pattern?) for `.setConfigurables(args: Configurables)`.

**Comment by Dhaiwat10** [comment]
@Braqzen are you sure this is possible with the Rust SDK? I couldn't find anything

**Comment by Dhaiwat10** [comment]
@Braqzen yes but we are only setting the configurables during in the initialization of the predicate object in that example

**Comment by nedsalk** [comment]
@FuelLabs/sdk-ts closing this because updating the configurables of a predicate would affect its address, which is a can of worms best kept unopened.
