### ISSUE TITLE
Split up `processNodeInfoAndConsensusParameters`

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1259]
Follow-up from #1181 and [this comment](https://github.com/FuelLabs/fuels-ts/pull/1181/files#r1301926337)

It should be split in 2 functions that do its part completely and independently: `processNodeInfo`, `processChain`

**Comment by Torres-ssf** [comment]
Solved on https://github.com/FuelLabs/fuels-ts/pull/1181
