### ISSUE TITLE
Implement utility method for zero-padding EVM addresses in the Address class

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1262]
When converting an EVM address to a Fuel address, it's essential to pad zeros.

To simplify this process we need to add utility methods within the `Address` class that will automatically handle this zero-padding for us. This enhancement will reduce potential errors for all applications interacting with the EVM address.

**Comment by danielbate** [comment]
So we do have a couple of functions already implemented that do something similar, however not matching this exact developer experience. Our `Address.fromEvmAddress` currently expects a wrapped and padded address (to match our `EvmAddress` type) to obtain an `Address`.

The above use case is more appropriate, as an address would be returned from the EVM unwrapped and unpadded, requiring the user to do such to pass it to our function. I'll raise a PR to improve the dev ex of this function.
