### ISSUE TITLE
Investigate delays between submitting a transaction and subscribing to its status via `statusChange`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1308]
_Originally posted by @luizstacio in https://github.com/FuelLabs/fuels-ts/issues/1301#issuecomment-1739419372_

Adding some more context here. When a transaction response is built after we send the transaction, if we have a delay bigger than the broadcasting of the status change, the subscription will never finalize and will make the code freeze on this step. We should cover the test case below and add a timeout to the `statusChange` subscription.

One test example would be:
```ts
const {  id: transactionId } = await provider.sendTransaction(<transaction>);

//Wait 10 seconds for the transaction to be submitted
setTimeout(() => {
   const tx = new TransactionResponse(transactionId, provider);
   const result  = await tx.waitForResult();
   //With the current implementation, this will never be resolved.
   console.log(result);
}, 10_000);
```
This is also true if the submission outputs a error as the final status is normally faster reached.

**Comment by arboleya** [comment]
Is this still a thing?
