### ISSUE TITLE
Investigate `InputInvalidSignature` error

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1311]
_Originally posted by @Braqzen in https://github.com/FuelLabs/fuels-ts/issues/1301#issuecomment-1743441791_

Here are the findings:

1. Under the steps to replicate [here](https://github.com/FuelLabs/fuels-ts/issues/1301#issuecomment-1740687449) when the client is run with `--utxo-validation` we no longer hang and instead error out with `PredicateVerificationFailed` for 2 tests (expected) and `InputInvalidSignature` in 1 test (unexpected).
2. The test that fails is found in path `test/walletConnector.test.ts` with title `transfer when a different valid signer is passed in`.

Question: why does that test fail?

Context

The test is meant to perform a transfer from SOMETHING (could be a predicate, contract or EOA) to a `recipientWallet`. For ease of use we use a predicate that has been funded appropriately to pay for gas and send a different asset in the transfer to the `recipientWallet`.

When we perform this transfer we use our connector class to craft a brand **new** predicate which should have no relation to the one in the TEST.
This brand new predicate has a different configurable set (`predicateAccount2`). By all means, the connector predicate should validate because we set the witness data (business logic related to the predicate code) in accordance with `predicateAccount2`.
But the test fails...
And we can force it to pass if we set the TEST predicate to use `ethAccount2` for the variable `paddedAcc` instead of `ethAccount1`. Meaning, the TEST predicate is somehow related to the PRODUCTION predicate which only performs validation when we set the client to use utxo validation.

I don't understand what is happening. I'm pretty sure our connector is setting things up correctly to submit a Tx to the network. Without utxo validation all tests pass.
cc @FuelLabs/client . We can hop on a call and I can demonstrate the issue (or my misunderstanding of predicates and validation).

**Comment by Braqzen** [comment]
I'm a moron nvm. Resolved
