### ISSUE TITLE
Transaction summary fee not accounts for byte cost

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#1314]
### What version of fuels-ts are you using?

0.58.0

### Steps to Reproduce

Create a transfer transaction and use `getTransactionSummaryFromRequest`.
The fee returned will be normally `0.000000001` ETH but this amount is not considering the byte cost of the transaction.

### Temp solution I found
```ts
    transactionSummary.fee = bn(
      Math.ceil(
        bn(transactionBytes.length)
          .mul(gasPerByte)
          .add(transactionSummary.gasUsed.mul(transaction.gasPrice))
          .toNumber() / gasPriceFactor.toNumber()
      )
    );
```

### Expected Behavior

The fee should include the byte cost.

### Actual Behavior

The fee not include the byte cost

**Comment by Torres-ssf** [comment]
This was solved already on https://github.com/FuelLabs/fuels-ts/pull/1437
