### ISSUE TITLE
Move `estimateTxDependencies` method from `Provider` class to `Account` class

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1320]
The method `estimateTxDependencies` should be moved from the `Provider` class to the `Account` class.

Motivation:

- User-Defined Implementations: Users can now craft their versions of `estimateTxDependencies` to suit their specific requirements, offering flexibility and control over transaction request modifications.

- Avoiding Provider Class Modification: This change ensures that transaction requests are not modified within the `Provider` class.

**Comment by nedsalk** [comment]
> User-Defined Implementations: Users can now craft their versions of estimateTxDependencies to suit their specific requirements, offering flexibility and control over transaction request modifications.

I don't understand why we'd want to give the user control over _estimating_ the costs of a transaction. The costs aren't something the user has control over; rather, the node is the source of truth for a transaction's costs. The user does have control over a `TransactionRequest`, its inputs and outputs, used gas, etc., and they can set that as they please, but if they send a transaction which doesn't cover the costs that the node sets, the node will reject it.

Am I missing something?

**Comment by Torres-ssf** [comment]
@nedsalk,`estimateTxDependencies` was not created with the purpose of getting the transaction cost but rather to identify and add missing `Contract` inputs and outputs, and `Variable` outputs by executing a series of dry run calls and analyzing the outcome receipts.

This means that this method will always mutate the transaction request.

Later we made it to also estimate the gas used by predicates and to update the predicate `predicateGasUsed` inputs as well. I believe this logic was placed there because it was a convenient place, since `estimateTxDependencies` was being called before executing a transaction and also modifying the transaction request.

Having said that, even though `estimateTxDependencies` can prevent some transaction requests from reverting, it has a downside in that; it can cause excessive dry run calls.

Moving `estimateTxDependencies` to the `Account` was a suggestion from @luizstacio. 

If I am not mistaken, one of the motivations is that the user should have better control if he always wants to execute this method before submitting a transaction.

**Comment by luizstacio** [comment]
@Torres-ssf  I think we should keep `estimateTxDependencies ` at the Provider class, but we should not use it on the submit, call, and methods inside the provider, removing changes on the transaction when calling the provider methods that should not change the tx.

**Comment by Torres-ssf** [comment]
Closing this

> ref: https://github.com/FuelLabs/fuels-ts/pull/1321#issuecomment-1766252268
