### ISSUE TITLE
Scaffold CLI tool for creating new projects

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1330]
> _Fuels CLI integration requires `fuels.config.ts` file generation_ — #1291

Create a scaffolding tool for generating ready-to-go Fullstack Fuel dApps.

It should support templates and provide a single-command frictionless entry point for newcomers.

```console
npx create fuels@latest my-fuel-dapp
npx create fuels@latest my-fuel-dapp -t <template-name>
```

Companion frameworks example:

```console
npx create fuels@latest my-fuel-dapp -t next
npx create fuels@latest my-fuel-dapp -t nuxt
npx create fuels@latest my-fuel-dapp -t sveltekit
npx create fuels@latest my-fuel-dapp -t astro
npx create fuels@latest my-fuel-dapp -t qwik
```

Dead-simple instant quickstart:

```console
npx create fuels@latest my-fuel-quickstart
```

End goal:

- Single-command, no-brainer, frictionless entry point for Fullstack dApp engineers
- Get users prototyping Fuel dApps in _seconds_
- Fast development cycle

**Comment by Dhaiwat10** [comment]
Can I take up this one? @arboleya :)

**Comment by arboleya** [comment]
Sure!

I'd say let's try to have a first minimal draft template structure considering the quickstart/counter that we can brainstorm over, review, and expand from there. Also, most "companion" frameworks I mentioned in the issue description have excellent interactive scaffolding tools from which we can look and draw inspiration — _if_ we need interactivity, meaning that a first version with only CLI flags like `-t, --template` may work just fine.

The output of this task should also align with #1291/`fuels.config.ts`, so you'll need to use that branch as the base branch for moving in parallel. Remember that the former PR is fresh and subject to changes, so it's wise to be flexible and keep some open ends to avoid over-refactoring as we approach the end.

**Comment by Dhaiwat10** [comment]
@arboleya @FuelLabs/sdk-ts I have created the first draft for the template here if you want to have a look: https://github.com/Dhaiwat10/fuel-cli-starter-template

**Comment by arboleya** [comment]
@Dhaiwat10 I wonder if keeping the whole `contracts` directory inside `src` is the best option—more [here](https://github.com/FuelLabs/fuels-ts/pull/1291#discussion_r1365662364).

**Comment by arboleya** [comment]
@luizstacio What do you think about a hybrid approach, like a mix of `built-in` and `community` templates? My concern is that having all `built-in` templates scattered around in different repos could add unwanted _maintenance_ complexity for _us_.

**Comment by Dhaiwat10** [comment]
@arboleya I see. I agree about the nomenclature decision you took there. Do you want me to move the directory one level out to the root of the project?

**Comment by Dhaiwat10** [comment]
Agreed @arboleya, I think we should only have two or three 'official' templates at most - covering the most popular frontend frameworks. This would be sufficient for 99% of our users.

**Comment by danielbate** [comment]
Can we tie it in with the frameworks in the `apps` directory, that way we ensure they are kept up to date.

**Comment by Dhaiwat10** [comment]
@danielbate good idea. Let me see if I can pull that together.

**Comment by Dhaiwat10** [comment]
btw one thing that I found when working on this issue was that `npx create fuels` won't work. That syntax only works with `pnpm`. Let's take the example of `create-next-app`.

As you can see in the [package.json](https://github.com/vercel/next.js/blob/canary/packages/create-next-app/package.json), the package's name is `create-next-app`. This means that the syntax for it would work like this:

npm - `npx create-next-app`
pnpm - `pnpm create next-app`

__create__ has to be a part of the name of the package. `npx create next-app` doesn't work.

For our tool, I think we should just add another command called `create` so it works like this:

`npx fuels create` and `pnpm fuels create`

Thoughts?

**Comment by arboleya** [comment]
> Just leaving a ref. of what we spoke here.

I believe all these may work:

 - `npx create-next-app`
 - `npm create next-app`
 - `pnpm create next-app`

**Comment by luizstacio** [comment]
I think it is the other way around, but by allowing the community to build the templates, we can reduce our management coverage. We just need to ensure on the install to use the lock inside the template etc...

Also, we incentivise people to build templates for other languages otherwise is going to be in our hands only to create these templates.

**Comment by Dhaiwat10** [comment]
I propose we create a repo similar to [this one by Next.js](https://github.com/vercel/next.js/tree/canary/examples) where we can store our templates. To start with, we can add two or three 'official' templates. The community can then keep adding templates to this repo via PRs.

**Comment by arboleya** [comment]
That makes sense.

Should we also move our demos to this repo? It could remove a lot of the bloat.

- `demo-nextjs`
- `demo-nodejs-esm`
- `demo-react-cra`
- `demo-react-vite`

My only concern is that these demos are currently used to validate that the SDK compiles correctly using each tool. If we move them outside, it'd be great to keep these validations. Perhaps some CI automation could do it.

Have you thought about it?

**Comment by Dhaiwat10** [comment]
@arboleya 
Definitely doable. I think the demos would also become redundant. The templates and demos both serve the same purpose. The only difference is that the templates will also include integrations with the `fuels` CLI and maybe the wallet SDK.

Maybe it would be a good idea to tackle this transition separately after this PR?

**Comment by arboleya** [comment]
Yes, it might be better to do it in separate PRs.

**Comment by arboleya** [comment]
@digorithm Is there any procedure we need to follow for creating new repos?
