### ISSUE TITLE
Inaccurate Offset Calculation for a Decoded Transaction witnesses

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1331]
There appears to be an inconsistency in decoding the Transaction `witnesses` data. 

The `witnesses` data is the last part of an encoded transaction. Because of this, an accurate offset calculation can be done through the following simple expression:

```ts
const witnessesLength = transaction.witnesses.reduce((total, w) => total + w.dataLength + 8, 0)

const witnessesOffset = transactionBytesLength - witnessesLength
```

However, while debugging `fuel-core` locally and running tests with many different transactions, I've noticed that the offset calculation is not always accurate. While the calculation is correct in some instances, there are discrepancies ranging from 4 to 20 in others. Could this be an indication that something is off when decoding the transaction `witnesses`?

## Steps to Reproduce
1. Run `fuel-core` locally in debug mode.
2. Within `fuel-core` external libraries look for the `fuel-vm` file: `fuel-tx/src/transaction/fee.rs`
3. Add breakpoints on function `checked_from_values` and watch the value of `metered_bytes` variable.
4. Submit different types of transactions: simple transfers, contract deployments, coin mintings, contract calls, and multi-contract calls.

**Comment by nedsalk** [comment]
I tried calculating the `witnessesOffset` value in the way you presented above inside of `calculateTxChargeableBytes` and all the `packages/fuel-gauge/src/fee.test.ts` tests passed. Does that mean that this is not an issue anymore or are the `fee.test.ts` tests not testing all possible scenarios?

**Comment by Torres-ssf** [comment]
@nedsalk Not sure what you mean by tests not testing all possible scenarios. I have added tests for all sorts of transactions.

The `packages/fuel-gauge/src/fee.test.ts` tests are meant to validate that the fee is being properly handled. Which has nothing to do with this corner case.

The error above does not happen on every execution. I couldn't determine why.

**Comment by nedsalk** [comment]
> Not sure what you mean by tests not testing all possible scenarios. I have added tests for all sorts of transactions.
> 
> The packages/fuel-gauge/src/fee.test.ts tests are meant to validate that the fee is being properly handled. Which has nothing to do with this corner case. 

Sorry, the second reproduction step you mentioned _(2. Within fuel-core external libraries look for the fuel-vm file: fuel-tx/src/transaction/fee.rs)_ and me stumbling upon this issue while investigating #1428 swayed me into thinking that the `fee.test.ts` covers this as well :sweat_smile:. 

> The error above does not happen on every execution and not with every type of transaction. I couldn't determine why.
>
> I will investigate and one corner case example here

Great! It would be best if you could open a PR and add it to master as a _skipped_ test and reference this issue in the test, just so that we have something to work with.
