### ISSUE TITLE
Restore Raw Slice as input test pending Sway changes

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#1344]
### Motivation

As part of https://github.com/FuelLabs/fuels-ts/pull/1343, some tests for raw slice inputs with scripts were disabled.

Either this gets fixed:
https://github.com/FuelLabs/sway/issues/5145

Or the tests need to be rewritten

**Comment by danielbate** [comment]
@arboleya could you confirm whether this should still have `epic` labelled, and this should no longer be blocked on the fuel project board.

**Comment by arboleya** [comment]
Labels and milestones updated.
