### ISSUE TITLE
Write manual release notes for important releases

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1347]
Opening this issue just to track the progress of figuring out a decent way to make sure that there are manual release notes whenever we put out a release with some breaking changes or some important new features.

**Comment by arboleya** [comment]
@Dhaiwat10 What was the outcome of this issue?

**Comment by Dhaiwat10** [comment]
@arboleya I will be writing manual release notes for any major releases from now on. I discussed this with Rodrigo before the beta-5 work. Example: https://github.com/FuelLabs/fuels-ts/releases/tag/v0.63.0

I will do something similar for our next big release - which I guess will be beta-5 support. I will just go and edit the automated release generated by CI.

**Comment by Dhaiwat10** [comment]
What we consider a 'big' release is a bit up in the air but I think we can start with any releases containing breaking changes and significant new features for now.

**Comment by arboleya** [comment]
I don't think we should necessarily go 100% manual here, but try to get these done instead:
 - https://github.com/FuelLabs/fuels-ts/issues/1028
 - https://github.com/FuelLabs/fuels-ts/issues/970

If the automated changelog becomes more readable, we can start being more conscientious about changelog notes and write them more appropriately. This should be enough for 95% of scenarios, and then we can deal with the last 5% manually.

> _cc @FuelLabs/sdk-ts_

**Comment by Dhaiwat10** [comment]
@arboleya Regarding the two issues that you linked, I was just about to write a comment on them that my efforts on adding these things had been very unsuccessful. I don't think the `changesets` automated changelog generation framework lets us customize the setup to this level. I've kept them open if someone else wants to have a go.

This is why I thought writing manual release notes, like Rodrigo does for the Rust SDK, would add a lot of value without too much effort. But I do agree with you on the fact that we should only do this when necessary.
