### ISSUE TITLE
GAS_PRICE_TOO_LOW vs GAS_LIMIT_TOO_LOW - Incorrect error being thrown

### ISSUE THREAD

**Issue by haardikk21** [FuelLabs/fuels-ts#1349]
https://github.com/FuelLabs/fuels-ts/blob/f6fb12b7fbc5c4ef4ed0b7471ae6749468b84a96/packages/providers/src/provider.ts#L479C4-L489C6

The error being thrown is switched upside down here

**Comment by danielbate** [comment]
Good catch 🦊
