### ISSUE TITLE
Improve docs examples with `minGasPrice`

### ISSUE THREAD

**Issue by haardikk21** [FuelLabs/fuels-ts#1351]
### What version of fuels-ts are you using?

0.62.0

### Steps to Reproduce

- Install latest version of `fuels`
- Get an unlocked wallet with some base asset (ETH) on it
- attempt to do a `wallet.transfer` with `txParams` undefined as it is optional

### Expected Behavior

SDK should be able to set gas price automatically and transfer should go through

### Actual Behavior

Error: gas price 0 is below required minimum 1

---

p.s. the official documentation for asset transfers doesn't include `txParams` object

**Comment by haardikk21** [comment]
> Allowing a transaction to inherit gas price from the network could introduce unexpected and unwanted behaviours IMO 🤔 If you are comfortable with a gas price of `x` then this should specified on the transaction.
> 
> Indeed `txParams` are optional and a network setting a `gasPrice` of 0 is still is still a valid scenario. The configuration we use for our local networks to run integration tests allows a `gasPrice` of 0.
> 
> Potentially the only action here is to ensure documentation examples contain a gas price greater than 0, but as mentioned above this is a valid scenario.

Whether or not i'm comfortable with a gas price of `x` though is not the question. Is there an option to set a `maxGasPrice` somewhere that I missed? and if I do that, will it fetch gas price automatically and have the txn go through as long as it's below that value?

Alternatively, is there a way to fetch the current gas price that I should be setting?

For my use case, I had no idea what to set the gas price to. I set it to 1 to get by the error, and my transactions kept getting stuck in a 'submitted' state and never becoming successful. It's fairly common to have support for automatically figuring out gas price with an optional max limit set on it, or at least have a way to fetch the current gas price so I can set it myself. 

I don't think hardcoding a fixed gas price value is the solution either and shouldn't be considered expected behaviour. everytime gas price fluctuates i don't want to responsible for redeploying my app, for example.

**Comment by Torres-ssf** [comment]
@haardikk21 When not informed, `gasPrice` value will be undefined and this basically means is going to be zero.

This issue is happening because the beta-4 configuration for the minimum gas price is `1`.

A safe way to avoid running into this error is to set the `gasPrice` using the `minGasPrice`, which carries the value of the minimum gas price accepted by the node.

In a similar approach, you can also use the `maxGasPerTx` for the tx `gasLimit`

```ts
const { minGasPrice, maxGasPerTx } = provider.getGasConfig();

const txParams = {
  gasPrice: minGasPrice,
  gasLimit: maxGasPerTx,
}

```

**Comment by haardikk21** [comment]
> @haardikk21 When not informed, `gasPrice` value will be undefined and this basically means is going to be zero.
> 
> 
> 
> This issue is happening because the beta-4 configuration for the minimum gas price is `1`.
> 
> 
> 
> A safe way to avoid running into this error is to set the `gasPrice` using the `minGasPrice`, which carries the value of the minimum gas price accepted by the node.
> 
> 
> 
> In a similar approach, you can also use the `maxGasPerTx` for the tx `gasLimit`
> 
> 
> 
> ```ts
> 
> const { minGasPrice, maxGasPerTx } = provider.getGasConfig();
> 
> 
> 
> const txParams = {
> 
>   gasPrice: minGasPrice,
> 
>   gasLimit: maxGasPerTx,
> 
> }
> 
> 
> 
> ```

Thank you!
