### ISSUE TITLE
Improvements and questions from SwaySwap development

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#136]
## Improvements and questions

- [x] Transaction error returns are not detailed enough; We need to debug binaries, etc.
- [x] Transfer coins need to have a script id. It's possible to use a script already implemented on the Core; we 
have used the id `0x24400000 `, but it would be nice to have some table with available scripts and what they do.
- [x] `scriptData` needs to have random data every time to make transactions different. **known issue**.
- [ ] It's challenging to work with amounts; we should have something like https://docs.ethers.io/v5/api/utils/display-logic/#utils-parseUnits
- [x] Empty values were not parsed, resulting in `type is not found` on the ts SDK. #134 should fix it.
- [x] #183
   - [x] The readme is not clear it should install the dependencies;
   - [x] I had the dependency `fuels` on the project and had to install the specific dependencies or change manually on the generated file. Maybe we should check if the `fuels` is installed and use it or If it is not possible to check. We could use `fuels` as a preferable dependency.
 - [x] We don't have a tutorial explaining how to do a full demo; we could use `swayswap` to create something like this.

**Comment by digorithm** [comment]
About

> Transfer coins need to have a script id. It's possible to use a script already implemented on the Core; we
have used the id 0x24400000 , but it would be nice to have some table with available scripts and what they do.

I just implemented it here: https://github.com/FuelLabs/fuels-rs/pull/110. Maybe that could help you with this point!
