### ISSUE TITLE
Consider ignoring patches in versions comparison

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1363]
https://github.com/FuelLabs/fuels-ts/blob/0068f54d1baadc493423a00f7776e3378ea9b530/packages/versions/src/lib/compareSystemVersions.ts#L19-L21

Brought up in this comment:
 - https://github.com/FuelLabs/fuels-ts/pull/1291/files#r1363178371

Related:
 - https://github.com/FuelLabs/fuels-ts/issues/1323

**Comment by danielbate** [comment]
Closing as unnecessary. This level of strictness is not heeding anything/anyone. It only benefits us/them to remain completely up to date and in sync, even at patch level IMO.

**Comment by arboleya** [comment]
Good catch. It was also addressed via:
 - https://github.com/FuelLabs/fuels-ts/issues/2207
