### ISSUE TITLE
Not able to run sdk linked local with fuels-portal project

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#1387]
### What version of fuels-ts are you using?

0.65.0

### Steps to Reproduce

setup [portal](https://github.com/FuelLabs/fuels-portal) locally

setup it to link with fuels-ts locally (ping me on slack if you don't know how to)

maybe can be related to [this](https://github.com/ethers-io/ethers.js/issues/3703)  ?

### Expected Behavior

should run the portal with the local sdk

### Actual Behavior

it's breaking 
<img width="1703" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/8636507/37ff49ea-6e94-4536-a888-d5a176e1edd2">

**Comment by danielbate** [comment]
I will investigate as it is likely related to #1255
