### ISSUE TITLE
Investigate `pretest` cache miss

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1404]
We're somehow losing the turborepo's cache on the `pretest` pipeline.

This started happening on:
 - https://github.com/FuelLabs/fuels-ts/pull/1235

A new step was added for running `pretest` [here](https://github.com/FuelLabs/fuels-ts/actions/runs/6338662126/job/17216232320#step:6:1).

However, the `pretest` runs again as part of the `pnpm test` [here](https://github.com/FuelLabs/fuels-ts/actions/runs/6338662126/job/17216232320#step:12:239).

Since `prestet` ran already, this second run should be nearly instantaneous (cache hit).

However, it's running full-on again (cache miss), hence why our CI time increased ~2.5 mins after this [PR](https://github.com/FuelLabs/fuels-ts/pull/1235) got merged.

**Comment by nedsalk** [comment]
I didn't find a solution to it, but this seems to be something related to the `ArtiomTr/jest-coverage-report-action@v2` action that's used in the `Run tests and post reports to PR` step.

For example, [this](https://github.com/FuelLabs/fuels-ts/actions/runs/6338662126/job/17216232320#step:12:1) is the test run which doesn't reuse the turbo cache. 
On the other hand, all master branch pipelines reuse turborepo's cache (e.g. [this run](https://github.com/FuelLabs/fuels-ts/actions/runs/6846953860/job/18614368895#step:9:1)).

The difference between PR and master branch pipelines is that PR pipelines run the `Run tests and post reports to PR` step, whereas master branch pipelines run the `Run tests and collect coverage` step.

**Comment by nedsalk** [comment]
Cache reuse now happens in `rc/salamander` ([1](https://github.com/FuelLabs/fuels-ts/actions/runs/7307635111/job/19913524508?pr=1495#step:9:27), [2](https://github.com/FuelLabs/fuels-ts/actions/runs/7307635111/job/19913524508?pr=1495#step:9:27)), so this issue will be solved when `rc/salamander` gets merged into `master`.

**Comment by arboleya** [comment]
@nedsalk That's great! Do you know what fixed it?

@danielbate Perhaps something you did with Vitest or the CI Actions?
