### ISSUE TITLE
Improve `getOperations` logic and validations

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1411]
The `getOperations` function and all associated helper functions currently require refactoring and improvements in their logic.

1. For instance, there is a (potential) recurring issue where the operation variable is reassigned during each iteration of the loop, as can be seen in the following snippet:

https://github.com/FuelLabs/fuels-ts/blob/3c1920e72d1459acb802952562c8dd6878153d9c/packages/providers/src/transaction-summary/operations.ts#L317-L323

It is crucial to ascertain whether this logic properly handles cases like a single transaction that involves the transfer of multiple assets among various addresses. 

We can also improve the logic here and stop reassigning the `operations` variable if only one operation is expected.

2. Additionally, it is necessary to validate whether transactions of the `Create` type can in fact generate a `Transfer Asset` operation:

https://github.com/FuelLabs/fuels-ts/blob/3c1920e72d1459acb802952562c8dd6878153d9c/packages/providers/src/transaction-summary/operations.ts#L408-L413

Proper validation will ensure the reliability and maintainability of this code.

**Comment by arboleya** [comment]
Completed via #1400.
