### ISSUE TITLE
Share test utility across all integration tests

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1439]
We have a few testing utilities scattered around, some very repetitive. We should try to condense them all in a single place _(`packages/utils`)_ to reduce the noise and improve maintenance.

[This](https://github.com/FuelLabs/fuels-ts/blob/d608f3e25f305b58d2da9c34ccc2ac7b9b533ede/apps/docs-snippets/src/utils.ts#L58-L73) seems like a good start <sup>([usage](https://github.com/FuelLabs/fuels-ts/blob/d608f3e25f305b58d2da9c34ccc2ac7b9b533ede/apps/docs-snippets/src/guide/contracts/index.test.ts#L4-L11))</sup> — although we need more options and flexibility, I like the simplicity of it.

We can draw inspiration and requirements from `fuel-gauge` and similar **_integration_** tests.

**Comment by maschad** [comment]
Related https://github.com/FuelLabs/fuels-ts/issues/1751

**Comment by arboleya** [comment]
I briefly spoke with @nedsalk about the location of test utilities (wrt to https://github.com/FuelLabs/fuels-ts/pull/1356), and it might not be that easy to move everything around like this. This is something we need to talk about.

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/FuelLabs/fuels-ts/issues/1820
