### ISSUE TITLE
Improve DX for `Script` class

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1458]
It should follow the same DX we have on `Contract`, supporting things like:

 - `txParams`
 - `callParams`
 - `getTransactionRequest`
 - Etc.

This increases flexibility and ease of use, giving users complete control of everything.

Related:
 - https://github.com/FuelLabs/fuels-ts/issues/1457

**Comment by danielbate** [comment]
Given we already have access to the invocation scope for a `Script` in the same way we'd expect to access it for a `Contract` (i.e. `script.functions.main(argument)`), we already have access to the same transaction preparation DX. However we should look to improve the documentation on this.
