### ISSUE TITLE
Standardize shell commands in the docs

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1459]
1. Remove `yarn` from all examples
 2. Ensure all examples have two variations:
    - `npm`
    - `pnpm`
 3. Use tab-component just like in [Installation](https://fuellabs.github.io/fuels-ts/getting-started.html#installing-the-fuels-ts-library).

Examples:
 - [Typegen](https://fuellabs.github.io/fuels-ts/guide/abi-typegen/generating-types-from-abi.html) `yarn`
 - [Fuels CLI](https://fuellabs.github.io/fuels-ts/guide/cli/) `npm`

**Comment by richardgreg** [comment]
Hi @arboleya, the task sounds straightforward. I'm making the updates.

Out of curiosity, why is yarn being sunsetted?

**Comment by arboleya** [comment]
We're just cleaning up, `yarn` was the tool of choice initially, but that hasn't been the case for a long time already.
