### ISSUE TITLE
Typegen - Improve `bytecode` compression

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1462]
Today, we read binaries after `forc build` and `hexilify` them.

The `hex` string is then embedded within the `typegen` generated Typescript factory class.

However, @luizstacio reported achieving a 70% size reduction using the method below:
 1. Read binaries
 1. Convert to Byte Array
 1. Gzip the Byte Array
 1. Encode the result using Base64

The reverse must be done for decoding, and the reduction is _considerable_.

We should look into that.

Refs:
 - https://www.npmjs.com/package/pako
 - https://www.npmjs.com/package/fflate

**Comment by dmihal** [comment]
Just thought of this during your presentation today @arboleya, would be a nice simple improvement to reduce code size.
