### ISSUE TITLE
Tool for Automated API Migration and Deprecation Handling

### ISSUE THREAD

**Issue by gww-fuel** [FuelLabs/fuels-ts#1464]
The project aims to enhance the developer experience by introducing a tool to assist with API migrations. This tool would identify deprecated API calls and automatically apply fixes to update the code to the latest API methods. Inspired by Rust's Clippy, the tool would provide a `openai migrate` command to streamline code compatibility with new API versions, reducing manual effort and improving code quality.
   
Main ambitions of this issue:

* [ ] Find a ways to automatically inform users that they use deprecated calls, and establish standardized way of annotating it.
* [ ] Develop or integrate a tool that can **automatically apply fixes to migrate deprecated API calls to the new methods**.

Action Items:

* [ ] Research and Evaluation:
   * [ ] Investigate existing tools in the JavaScript/TypeScript ecosystem that offer deprecation flagging and auto-fix capabilities.
   * [ ] Evaluate the feasibility of integrating such tools into our development workflow.
   * [ ] Consider the possibility of developing a custom solution if existing tools do not meet our requirements.
* [ ] Annotating Deprecation:
   * [ ] Implement a system to mark deprecated API methods within the codebase.
   * [ ] Ensure that developers are notified of deprecations during the build or development process.
   * [ ] Document the deprecation process and guidelines for developers.
* [ ] Applying Auto-fix for Deprecations (Breaking Change):
   * [ ] Develop or integrate a tool that can **automatically apply fixes to migrate deprecated API calls to the new methods**.
   * [ ] Create a command, such as `cargo clippy --fix`, to execute the migration process.
   * [ ] Test the tool to ensure it accurately identifies deprecations and applies the correct fixes.

Motivation:
The motivation for this tool is to emulate the functionality of `cargo clippy --fix` in the Rust ecosystem, which automatically applies fixes for deprecated functions. By providing a similar solution for JavaScript/TypeScript, we aim to simplify the migration process, maintain consistency across the codebase, and enhance overall developer productivity.

**Comment by danielbate** [comment]
TypeDoc, which we use for our autogenerated API documentation has the `deprecated` tag. This will inform the docs but not elsewhere.

**Comment by danielbate** [comment]
I'm not sure this is right for us right now.

API migration is a huge feature in it's own right, this may be something we want to visit from `v1` -> `v2` but our journey to `v1` seems like a much more natural progression that I don't think warrants the need for a tool. We've made massive improvements to our [release notes](https://github.com/FuelLabs/fuels-ts/releases/tag/v0.92.0) with migration in mind.

Tagging @FuelLabs/sdk-ts for comment.
