### ISSUE TITLE
Consolidate Tx Preparation for all program types

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1465]
Given improvements to DX for predicates and scripts:
- #1458
- #1457 

We will then have a similar DX flow regarding transaction preparation across all program types. However we should then look to DRY both our source code and documentation where possible, to provide a consistent approach to transaction preparation regardless of program type, rather than being specific to it.

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/FuelLabs/fuels-ts/issues/1457
