### ISSUE TITLE
Migrate snippets from `fuel-gauge`

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1505]
We currently have quite a few tests that references documentation from `fuel-gauge`. These scenarios are at times improperly formed in order to be more verbose and illustrate techniques rather than validate the end to end functionality of the SDK. As that is the intended usage of `fuel-gauge`, we should instead move `fuel-gauge/src/doc-examples.test.ts` to appropriate places in `apps/docs-snippets`. The documentation references will also need to be altered as the links will have been broken.

**Comment by petertonysmith94** [comment]
@danielbate pls

**Comment by danielbate** [comment]
Sorry meant to assign you @petertonysmith94

**Comment by petertonysmith94** [comment]
Notes:
- [`vector-4`](https://github.com/FuelLabs/fuels-ts/blob/master/apps/docs-snippets/src/guide/types/vector.test.ts#L46)
Doesn't show a return value in the documentation `// expect value` would be beneficial.

**Comment by mvares** [comment]
@petertonysmith94, should only the code-snippets be changed? (that it's with `// #region`)
