### ISSUE TITLE
Flaky tests throwing `not enough coins to fit the target`

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1510]
It seems there is a new flaky test happening both on the CI and locally.

Usually happens on the test suite `packages/fuel-gauge/src/contract.test.ts`, but I've seen happening in other places.

<img width="1728" alt="Screenshot 2023-12-12 at 16 20 36" src="https://github.com/FuelLabs/fuels-ts/assets/30977845/9ac9efb5-d698-4be2-9c54-6245f9e96356">

**Comment by arboleya** [comment]
This seems to be happening consistently on `master`.
