### ISSUE TITLE
Review UTXO caching logic

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1515]
We recently experienced [flaky tests](https://github.com/FuelLabs/fuels-ts/pull/1514) related to the [optional UTXO caching](https://github.com/FuelLabs/fuels-ts/pull/930) that happens on the Provider class.

This logic was added to solve an [issue](https://github.com/FuelLabs/fuels-ts/issues/865) that was happening on the test net (beta-3?).

Now that we are moving to a new test net, and have identified that something might be wrong with how the UTXOs are being cached, we need to reevaluate this logic and validate if it needs to be updated or if we could remove it enterely.

**Comment by arboleya** [comment]
What have we identified that might be wrong?

**Comment by Torres-ssf** [comment]
@arboleya I am unsure about what was causing this one.

I would need to investigate this further. I can take a look at it this week.
