### ISSUE TITLE
The fuels-forc / fuels-core packages don't install the binaries when used via bun

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1522]
If we use bun to install the SDK, it doesn't install the binaries served via `@fuel-ts/fuels-forc` and `@fuel-ts/fuels-core` which are supposed to be installed via the `install` script.

We are not sure if this is a bug on our end, or an issue with bun. This needs to be investigated.

**Comment by Jarred-Sumner** [comment]
@Dhaiwat10 this is caused by Bun not running postinstall scripts for packages not in the list of default-enabled trusted dependencies

Adding the package name to `"trustedDependencies": ["@fueld-ts/fuels-core"]` may do it, when in the root project's package.json
