### ISSUE TITLE
Make `Provider` optional for `Wallet`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1539]
The idea is to make it possible to use the `Wallet` methods that don't need a `Provider`. We should validate the `Provider` when needed and throw an error if it's not there.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by petertonysmith94** [comment]
I believe this is a duplicate of #1444?

**Comment by arboleya** [comment]
@petertonysmith94 Good catch.

Closing in favor of #1444.
