### ISSUE TITLE
Migrate `bn.js` to `bignumber`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1542]
Suggestions were made to replace one library with the other.

Ideally, we should have a pros and cons list before deciding.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by nedsalk** [comment]
Based on [this discussion](https://github.com/ethers-io/ethers.js/discussions/2710) and ethers v6 using native bigint in their maths "package" ([see here](https://github.com/ethers-io/ethers.js/blob/6ee1a5f8bb38ec31fa84c00aae7f091e1d3d6837/src.ts/utils/maths.ts#L14)), it seems like ethers got rid of big-number libraries altogether and went completely in favor of native bigint.

**Comment by LuizAsFight** [comment]
just to add more context: #280 #468 

it's interesting to take a look at those to understand why `bn` was chosen at first place and what problems it solves

**Comment by nedsalk** [comment]
Related to the `JSON.stringify`, we could fix it by defining our own `BigInt.prototype.toJSON` (based on [this comment](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-953187833)):
![image](https://github.com/FuelLabs/fuels-ts/assets/17943891/00d4a732-9cb9-4fca-8bcd-bef7e01c5a07)

It would solve the issue across the board. Although messing with the prototype is risky as it can cause collisions ... what's the chance that two libraries would be adding this same method? Also, as the comment I linked to above mentioned, [MDN also recommends it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json), although in the image I'm serializing into hex, not a stringified number.

**Comment by LuizAsFight** [comment]
> Related to the `JSON.stringify`, we could fix it by defining our own `BigInt.prototype.toJSON` (based on [this comment](https://github.com/GoogleChromeLabs/jsbi/issues/30#issuecomment-953187833)): ![image](https://private-user-images.githubusercontent.com/17943891/293673025-00d4a732-9cb9-4fca-8bcd-bef7e01c5a07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTY1NDIsIm5iZiI6MTcwNDk1NjI0MiwicGF0aCI6Ii8xNzk0Mzg5MS8yOTM2NzMwMjUtMDBkNGE3MzItOWNiOS00ZmNhLThiY2QtYmVmN2UwMWM1YTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2NTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViYWMyOTQyMzdlOTk1OTZjOWYxMzZjZWE1YmZkYjAwZjQwYjRhODYxM2Y4NmYzZDIyNDk1M2FiOTJlZDVjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKLDtn0rAuCMMqFgF0IWGBoMiCr4t-hI8XX9cK-xhIQ)
> 
> It would solve the issue across the board. Although messing with the prototype is risky as it can cause collisions ... what's the chance that two libraries would be adding this same method? Also, as the comment I linked to above mentioned, [MDN also recommends it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json), although in the image I'm serializing into hex, not a stringified number.

when you stringify again, it's not a BigInt anymore

**Comment by nedsalk** [comment]
> when you stringify again, it's not a BigInt anymore

Stringifying `BN` has the same behavior and we lose context that it was a `BN` before. `BN` doesn't add the `0x` prefix so we could get rid of it as well if we go with the custom `BigInt.prototype.toJSON` proposal for compatibility's sake.

**Comment by danielbate** [comment]
I was not there when `bn.js` was chosen, however from my understanding it solved problems for developers trying to build for environments where a native `BigInt` was not yet supported. As the `[ethers discussion](https://github.com/ethers-io/ethers.js/discussions/2710)` reads (who migrated from `BN` to `BigInt` in `v6`),  Node `v12` was EOL in April 2022 (did not support `BigInt`) and all later versions of Node do, and all modern browsers do. Therefore the case for not using it for that reason is now pretty void. 

For our own purposes, I believe this has come from reported inaccuracies when using `BN` for calculations (can't find anything to link but I believe @Torres-ssf reported this?). Additionally, there is an opportunity to reduce the SDK size  through the removal of `BN` to a natively supported type, as @nedsalk is investigating in #1592.

**Comment by nedsalk** [comment]
After taking a look at it with @danielbate, replacing `BN` with native `bigint` seems like a ton of relatively easy work, but it'll be a breaking change with all our consumers and we have to make that known.

The benefits, as mentioned by @danielbate above, are:
- Fixing reported inaccuracies when using BN? (@Torres-ssf)
- Reducing the non-treeshakeable SDK size by > 22kB (#1592),
- Using a native primitive

Besides that, we've already got a precedent for it with `ethers` so it wouldn't come as a big shock to anybody.

The cons at this moment are:
- A breaking change for all ts-sdk consumers, most notably the Fuel's frontend team

@FuelLabs/frontend @FuelLabs/sdk-ts It would be great to get additional input from everyone.

**Comment by nedsalk** [comment]
As of the time of writing, there is no consensus in the team for moving forward with this issue so I'm removing my assignment from it. I won't be closing it as it's a valid issue and something that should probably be done in the future for package size benefits.

**Comment by nedsalk** [comment]
Related to package size reduction, by doing an in-depth analysis of `bn.js` we could maybe exclude its unnecessary dependencies from our build via rollup and squeeze out some kilobytes that way. `bn.js` itself isn't tree-shakeable.

**Comment by danielbate** [comment]
Closing this for now. Contextually tree-shaking is being discussed in #1592 so that can be resolved there. The proposal that this issue makes we have not got a consensus on so therefore doesn't seem right for us at the moment.
