### ISSUE TITLE
Consider implementing Provider throttling

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1543]
Maybe just some docs would be enough.

This could be further discussed with @FuelLabs/devrel.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by hummusonrails** [comment]
Are there any resources currently published/unpublished on the topic?

**Comment by arboleya** [comment]
@hummusonrails You mean internally? Probably not, but I bet we can find some external articles on the topic. I just don't have anything at hand to share atm.

@nedsalk Now that I'm looking at this, I wonder if this wouldn't be a small variation of the `retrier` you did _(no `maxRetries` tho)_. I may be oversimplifying it. Let me know what you think.

**Comment by nedsalk** [comment]
>  but I bet we can find some external articles on the topic. 

Here's a great one from the SRE book: https://sre.google/sre-book/handling-overload/. The section of most interest for us would be "Client-Side Throttling".

> Now that I'm looking at this, I wonder if this wouldn't be a small variation of the retrier you did (no maxRetries tho). 

Yeah, that would probably be the place to do it, just that the logic would be kinda inverse to the retry functionality so one would have to take care to properly implement the interplay between these two functionalities.

This throttling would be an internal detail not modifiable by the user, right? I don't see why we'd allow users access to it, but I wanted to throw this question out there.

As for the implementation, I see two ways that we can go about throttling:
1. Reject the request locally and throw an error,
2. Store the request locally and delay its sending for some time

--------

But just to take a step back, do we actually need client-side throttling on the SDK level? The only error I found on the fuel node that might benefit from client-side throttling is the [TooManyTransactions error](https://github.com/FuelLabs/fuel-core/blob/622e38bb33b942213cc173e93bbb9eb663d375e0/crates/types/src/services/executor.rs#L252), but it's thrown when the max u16 value of transactions in a block is reached (65535 transactions), so maybe we're prematurely optimizing here. To me it seems like we neither need docs nor implementation here.

**Comment by arboleya** [comment]
> [..] do we actually need client-side throttling on the SDK level?

I don't think so. We are just evolving the topic here.

This seems more pertinent to the user domain, so maybe some mention in the docs will be enough, especially if we have more information about the `fuel-core` rate-limiting (not sure if we have these details yet).

**Comment by nedsalk** [comment]
>  especially if we have more information about the fuel-core rate-limiting (not sure if we have these details yet).

Could somebody from @FuelLabs/client chime in on this?

**Comment by nedsalk** [comment]
Closing this issue as not planned because it's not in the domain of the SDK.
Referencing the @FuelLabs/devrel team because they might want to evolve this topic further from the docs side.
