### ISSUE TITLE
Too much padding in the API docs

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1558]
This one is largely for @sarahschwartz but there is too much padding in the generated API docs for the TS SDK, I'd consider revising and look at the appropriate amount that other docs references use, even the original ts-sdk docs were better here.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1545

**Comment by arboleya** [comment]
@SilentCicero Are you referring to:
 1. The Docs Hub Portal
    - https://docs.fuel.network/docs/fuels-ts/
 1. TS SDK Docs:
    - https://fuellabs.github.io/fuels-ts/

Do you have any page in particular to be used as a reference?

That could be helpful.

**Comment by sarahschwartz** [comment]
This should be solved now.

**Comment by arboleya** [comment]
Thanks. 🙌
