### ISSUE TITLE
Introduce `submitAndAwait` graphql endpoint support

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1563]
Submitting a transaction and getting its results is currently a two-step process:
1. Submit the transaction,
2. Get its results via the `TransactionResponse` class

This is the default workflow and should remain the default one because a transaction can take an indefinite amount of time to execute on the node and using `submitAndAwait` as the default would block our users from executing anything on their side until the node executes the transaction.

However, we should allow our users to submit _and_ await the results of the transaction execution in one call if they wish to do so. The main benefit of this single call over splitting it into two calls (submit and and subscribe to `statusChange`) is that the transaction might fail or be squeezed out in-between the submitting and subscribing, which would result in the subscription call never getting an update and thus never ending. This would be because the node immediately deletes a failed and squeezed-out transaction and us requesting that deleted transaction would hang to infinity.

A possible implementation of this would be to expand the current `ProviderSendTxParams` type:
```ts
export type ProviderSendTxParams = EstimateTransactionParams & {
  awaitExecution: boolean;
}

export class Provider {
// ...
  async sendTransaction(..., params: ProviderSendTxParams) {
  // ...
    if (params.awaitExecution) {
    const subscription = await this.operations.submitAndAwait({encodedTransaction});
    for await (const statusAndReceipts of subscription) {
      if(statusAndReceipts.type === "SubmittedStatus") continue;
      const transactionId = hashTransaction(encodedTransaction);
      return TransactionResponse(transactionId, statusAndReceipts);
    }
  }
  const { submit: { id: transactionId } } = await this.operations.submit({ encodedTransaction });
  return TransactionResponse(transactionId, this);
  }
}
```

These `ProviderSendTxParams` can then be forwarded via `FunctionInvocationScope.call()`, `Account.transfer()` and the like so the user can set the desired behavior through a flag, e.g.: 
```ts
const response: TransactionResponse = await my_contract
  .functions
  .my_fn()
  .call(..., {awaitExecution: true});
```

**Comment by arboleya** [comment]
Blocked by:
 - https://github.com/FuelLabs/fuels-ts/issues/1530
