### ISSUE TITLE
Implement `relayMessage` and `waitForMessage`

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1568]
Also, make improvements to the `withdraw to base layer` tests.

Refer to the bridge repo:
 - https://github.com/FuelLabs/fuel-bridge/

Important for mainnet.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by arboleya** [comment]
@Dhaiwat10 Do you remember what this is about, and is it something we should still look into?

**Comment by Dhaiwat10** [comment]
@arboleya I faintly remember these two being some helper/utility methods in the bridge codebase. Not sure if it is something that we still need to work on. Might be worth asking the frontend/bridge team

**Comment by arboleya** [comment]
It looks like a lot changed in the bridge, let's close for now and reopen if necessary.
