### ISSUE TITLE
Improve GraphQL utilities

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1570]
We need to enhance our GraphQL API by implementing custom resolvers that manipulate the data returned from the queries to match the specific data types and structures required by the SDK and its consumers. 

A prime example is the GraphQL type for UTXOs: `InputCoin` which needs to be [manipulated](https://github.com/FuelLabs/fuels-ts/blob/53dafb1c6e5e02e47f805c111a8f348278101a5f/packages/providers/src/provider.ts#L898-L927) to the corresponding SDK type: `Resource`.

We need to make this change to improve things not only for the internal use of the SDK but also for the SDK consumers. 

Having said that, a deep analysis should be made not only in the SDK but also on the [block explorer](https://github.com/FuelLabs/fuel-explorer) to identify all possible resolvers that can be created to reduce the data manipulation after queries, as the block explorer executes a lot of GraphQL queries.

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by nedsalk** [comment]
Do you mean that we write resolvers such that e.g. a call to `provider.operations.getCoinsToSpend` would give the same result as the current `provider.getCoinsToSpend`?

**Comment by Torres-ssf** [comment]
> Do you mean that we write resolvers such that e.g. a call to `provider.operations.getCoinsToSpend` would give the same result as the current `provider.getCoinsToSpend`?

@nedsalk Not exactly. These resolvers should take care only of the data manipulation that happens before returning the data. For this specific case I believe would be this part https://github.com/FuelLabs/fuels-ts/blob/53dafb1c6e5e02e47f805c111a8f348278101a5f/packages/providers/src/provider.ts#L898-L927. 

In this specific case, it could be a little different, I did not go deep into it.
