### ISSUE TITLE
Implement GraphQL custom scalars

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1572]
Implement GraphQL custom scalars for Efficient Data Type Conversion.

We need to make use of GraphQL custom scalars to automatically handle simple data parsing.

For instance, consider the parsing from a `String` to `BN`. 

Currently, all `BN` data retrieved via GraphQL is in string format, always requiring a manual conversion to `BN`.

Implementing custom scalars will eliminate the need for these repetitive manual conversions. Below is an illustrative example:

> [!WARNING]
> _This code is provided as an example and should not be considered the final solution._

```ts
// Implementation of the BigNumber scalar
const bigNumberScalar = new GraphQLScalarType({
  name: 'BN',
  description: 'A custom scalar type for BN',
  serialize(value) {
    // Converts BN to a string for the response
    return value.toString();
  },
  parseValue(value) {
    // Transforms an incoming string into BN
    return bn(value);
  },
  parseLiteral(ast) {
    if (ast.kind === 'StringValue') {
      return bn(ast.value);
    }
    return null;
  }
});

// Definition of resolvers
const resolvers = {
  BN: bigNumberScalar,
  // Additional resolvers can be defined here
};
```

> [!NOTE]
> - Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1537

**Comment by arboleya** [comment]
@Dhaiwat10 @Torres-ssf Do you know if there is any overlapping between this issue and #1570?

**Comment by Torres-ssf** [comment]
@arboleya There is no overlapping between these 2

1 - I will close and create another issue in favor of this one today. I've misinterpreted how the problem presented by the FE feedback could be solved on our side. It seems that implementing a custom scalar can only be done on the server side. I will write the specs for the new issue later today.

2 - https://github.com/FuelLabs/fuels-ts/issues/1570 is not related to this one. However, It needs some investigation to validate if graphQL `resolvers` can be used on a `node` client-side application.

**Comment by Torres-ssf** [comment]
Closing this issue since it is not possible to define Custom Scalars on a GraphQL client-side Node application.
