### ISSUE TITLE
Disallow transferring `<= 0` of an asset

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1577]
The code below succeeds:
```ts
await wallet.transfer(
      destination.address,
      -1,
      BaseAssetId,
      { gasPrice, gasLimit: 10_000 }
    );
```
We shouldn't allow such inputs. Negative and zero values are generally allowed to be passed as values - they're just numbers after all, but our `transfer` method shouldn't be able to transfer `<= 0` of an asset.

**Comment by petertonysmith94** [comment]
Taking a look into this @nedsalk
