### ISSUE TITLE
Possible issue with `getTransactionSummary`

### ISSUE THREAD

**Issue by mpoplavkov** [FuelLabs/fuels-ts#1578]
> `getTransactionSummary` uses current chain configuration for fee calculation. Even for old transactions.

### What version of fuels-ts are you using?

master

### Steps to Reproduce

Just call the [getTransactionSummary](https://github.com/FuelLabs/fuels-ts/blob/53dafb1c6e5e02e47f805c111a8f348278101a5f/packages/providers/src/transaction-summary/get-transaction-summary.ts#L25) method. 

It takes the parameters such as `gasPriceFactor` and `gasCosts` at the time of Provider creation, not the time of transaction execution: [proof](https://github.com/FuelLabs/fuels-ts/blob/53dafb1c6e5e02e47f805c111a8f348278101a5f/packages/providers/src/transaction-summary/get-transaction-summary.ts#L48-L50). Those parameters are later [used](https://github.com/FuelLabs/fuels-ts/blob/53dafb1c6e5e02e47f805c111a8f348278101a5f/packages/providers/src/transaction-summary/assemble-transaction-summary.ts#L68-L78) for fees calculation.

### Expected Behavior

The SDK will use consensus parameters at the time of transaction execution, not the current time.

### Actual Behavior

Current consensus parameters are used for fee calculation of all transactions. If those parameters change, the fees for previous transaction change as well. But those fees should remain the same

**Comment by maschad** [comment]
I'm not sure there's much that we can do right now because the gas price and other related parameters cannot be fetched for a given period of time, we only have access to the current values. Maybe this can be solved with the indexer?
