### ISSUE TITLE
Ensure Windows support

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1611]
Incoming from the forum:
 - https://forum.fuel.network/t/3938

Potential causes inside the `install` script for `forc` and `fuel-core`:
 1. Use of `tar` _([here](https://github.com/FuelLabs/fuels-ts/blob/df3222d5cd98fd87faee7e9197d17e7a0d274da5/packages/forc/lib/install.js#L56) and [here](https://github.com/FuelLabs/fuels-ts/blob/df3222d5cd98fd87faee7e9197d17e7a0d274da5/packages/fuel-core/lib/install.js#L66))_
    - Consider using: https://www.npmjs.com/package/tar

 1. Use of `rm -rf` _([here](https://github.com/FuelLabs/fuels-ts/blob/df3222d5cd98fd87faee7e9197d17e7a0d274da5/packages/fuel-core/lib/install.js#L55) and [here](https://github.com/FuelLabs/fuels-ts/blob/df3222d5cd98fd87faee7e9197d17e7a0d274da5/packages/fuel-core/lib/install.js#L72))_
    - Consider using `rmSync` _([example](https://github.com/FuelLabs/fuels-ts/blob/df3222d5cd98fd87faee7e9197d17e7a0d274da5/packages/forc/lib/install.js#L59))_

> A full checkup is necessary.

**Comment by arboleya** [comment]
As @danielbate pointed out, a nice addition to this would be to run our test suite on a Windows image.

**Comment by arboleya** [comment]
Good catch. Yes, a quick mention in the docs can be good.

Could detect if the underlying system is not supported and give users a proper error message?

**Comment by Dhaiwat10** [comment]
@arboleya we already have some code for that in place, but it doesn't seem to throw the error properly. The script probably throws before this line is even reached:

https://github.com/FuelLabs/fuels-ts/blob/master/packages/forc/lib/shared.js#L25-L27

**Comment by Dhaiwat10** [comment]
I will make it so that it throws right at the beginning of the install script if Windows is detected.
