### ISSUE TITLE
Remove dependency for external fonts within the CI

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#1639]
Currently `apps/demo-nextjs` (maybe a few others) reaches out to an external provider to retrieve **fonts** (**Google**).
We should't rely on external services for our pipelines, so that we have a resilient process.

```sh 
demo-nextjs:pretest: FetchError: request to https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap failed, reason: 
demo-nextjs:pretest: src/app/layout.tsx
demo-nextjs:pretest: `next/font` error:
demo-nextjs:pretest: Failed to fetch `Inter` from Google Fonts.
demo-nextjs:pretest:  ELIFECYCLE  Command failed with exit code 1.
```

[[Source](https://github.com/FuelLabs/fuels-ts/actions/runs/7501006291/job/20420793150)]

**Comment by petertonysmith94** [comment]
@danielbate pls assign

**Comment by arboleya** [comment]
Read my mind.
