### ISSUE TITLE
Use receipts from `TransactionStatus`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1644]
### Discussed in https://github.com/FuelLabs/fuels-ts/discussions/1588

<div type='discussions-op-text'>

<sup>Originally posted by **nedsalk** December 15, 2023</sup>
Post `fuel-core v0.22.0`, the node now returns receipts with a `TransactionStatus`, so we can use them right away instead of running another fetch. From my understanding, this will only become relevant after #1374 is merged, because we're currently using the `getTransactionWithReceipts` endpoint.</div>

The way to go about implementing this is to use the `TransactionRequest` sent to the node in `provider.sendTransaction` because it contains the same transaction as the one that's fetched from the node inside of `TransactionResponse` via `getTransactionWithReceipts`, only that after fetching it from the node the receipts are there as well. 

Because the receipts can now be received from the subscription directly, the same transaction summary can be generated based off of the `TransactionRequest` and the receipts received from the subscription. A working implementation can be found on [this branch](https://github.com/FuelLabs/fuels-ts/tree/ns/feat/subscription-receipts).

**Comment by nedsalk** [comment]
Blocked by merge of #1415 and #1615.

**Comment by arboleya** [comment]
The only utility for a discussion is to discuss something _before_ it becomes an issue.

**Comment by arboleya** [comment]
So the discussion is not needed anymore.

**Comment by nedsalk** [comment]
Blocked by:
- https://github.com/FuelLabs/fuel-core/issues/1724

**Comment by arboleya** [comment]
Unblocked by:
 - https://github.com/FuelLabs/fuel-core/pull/2061
