### ISSUE TITLE
Re-work and improve `markdown-link-check` workflow

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1681]
I often get errors on the `markdown-link-check` workflow _(examples [here](https://github.com/FuelLabs/fuels-ts/actions/runs/7637918332/job/20808299398?pr=1680) and [here](https://github.com/FuelLabs/fuels-ts/actions/runs/7637916209/job/20808309173?pr=1679))_.

Sometimes, I need to re-run the workflow several times until it passes.

I'm unsure of the issue since the error doesn't say much.

It'd be great if we could have this working reliably.

**Comment by danielbate** [comment]
1st step might be to get the logs coming through? Can't say I see this _that often_, but when I have locally, it was usually due to connection time outs. If that is the case we may need to rethink our approach here. Also if we are validating this in the docs hub also we are duplicating efforts.

**Comment by arboleya** [comment]
All PRs are currently broken, which I'd consider often _enough_ for _today_. 😆
