### ISSUE TITLE
Ensure dry runs request only necessary data

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1706]
To lower bandwidth, we should ensure dry runs query only necessary data from GQL API, as they probably don't need all fields.

For example, here is one receipt payload on the sway marketplace:

![fieds](https://github.com/FuelLabs/fuels-ts/assets/26660/ef3161e6-8224-49ce-ab06-0bb517ffc9d9)

**Comment by arboleya** [comment]
One idea is to add a receipt filter to the query args to just return a specific log or script.

This would require changes on `fuel-core`.

**Comment by Voxelot** [comment]
There's also other data that's likely irrelevant to the ts sdk when fetching consensus params:

### latest block tx ids
![image](https://github.com/FuelLabs/fuels-ts/assets/794823/9ebba3e6-edd6-4945-b936-94182a45b2db)


### gas costs
![image](https://github.com/FuelLabs/fuels-ts/assets/794823/5e3bf615-7a37-49a5-9b78-afb52f530da8)

**Comment by Voxelot** [comment]
We also don't need salt and the **full contract bytecode** on every receipt from a contract:

![image](https://github.com/FuelLabs/fuels-ts/assets/794823/e547330c-216c-448f-afe4-4381c68d0a80)

If a contract has multiple receipts, and the full contract bytecode gets logged on every receipt from that contract, the response is going to be super huge!
