### ISSUE TITLE
message: 'Unknown type "TxParameters"',

### ISSUE THREAD

**Issue by sajshuai** [FuelLabs/fuels-ts#1716]
### What version of fuels-ts are you using?

0.72.0

Node version
20.0.0

### Steps to Reproduce

await Provider.create("https://beta-4.fuel.network/graphql")

### Actual Behavior

<img width="1061" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/3991932/71563413-1130-4573-973b-bc4796ba6bff">

**Comment by arboleya** [comment]
Just as mentioned [here](https://github.com/FuelLabs/fuels-ts/issues/1663#issuecomment-1898463349), for connecting to Beta-4 you can't use any version beyond `0.69.1`.

Could you please try that and let me know if that worked?

**Comment by sajshuai** [comment]
I downgraded to 0.69.1 and it works now, thanks
