### ISSUE TITLE
Add minified version in CDN

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1728]
We should provide a minified version together with the normal one.

This is a follow-up issue on top of:
 - https://github.com/FuelLabs/fuels-ts/issues/1397

**Comment by petertonysmith94** [comment]
Blocked until release of:
- https://github.com/FuelLabs/fuels-ts/pull/2762

Then:
- Make to changes CDNJS configuration file ([fuels.json](https://github.com/cdnjs/packages/blob/master/packages/f/fuels.json)):
  ```json
  {
    ...,
    "autoupdate": {
      "source": "npm",
      "target": "fuels",
      "fileMap": [
        {
          "basePath": "dist",
          "files": ["browser.mjs", "browser.min.mjs"]
        }
      ],
      "ignoreVersions": [
        "0.0.0-*"
      ]
    },
    ...,
  }
  ```
  (Add minified bundle (`browser.min.mjs`) and `ignoreVersions`)

**Comment by petertonysmith94** [comment]
PR is in review
- https://github.com/cdnjs/packages/pull/1852

**Comment by petertonysmith94** [comment]
Will mark this as closed as CDNJS configuration has now been merged:
- https://github.com/cdnjs/packages/pull/1852

We should monitor the release of https://github.com/FuelLabs/fuels-ts/pull/2863 to ensure the minified version is present.
