### ISSUE TITLE
Fetch latest gas price from `fuel-core` node

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1738]
The PR below introduces a new GQL endpoint, which we must integrate:
 - https://github.com/FuelLabs/fuel-core/pull/1649

This is part of a conversation around Transaction Fee:
 - https://github.com/FuelLabs/fuel-core/issues/1606

Related:
 - https://github.com/FuelLabs/fuel-core/issues/1653

**Comment by MitchTurner** [comment]
To query the future gas prices, you'll actually need this endpoint: https://github.com/FuelLabs/fuel-core/pull/1650
