### ISSUE TITLE
Error Web Link - 404 Found

### ISSUE THREAD

**Issue by stguller** [FuelLabs/fuels-ts#1743]
### What version of fuels-ts are you using?

https://www.fuel.network/

### Steps to Reproduce

https://docs.fuel.network/docs/indexer/
link has an errror page.

### Expected Behavior

Please add indexer page on web page.

### Actual Behavior

https://docs.fuel.network/docs/indexer/
link has an errror page.

**Comment by ilyassBZ** [comment]
i wanna work on ity but can u explain moore Please add indexer page on web page. ??

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/FuelLabs/docs-hub/issues/177
