### ISSUE TITLE
Add formatter to `templates/nextjs`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1758]
There is currently no formatter in our `templates/nextjs` which leads to a less "out of the box" experience when using it via `pnpm create fuels`. We should add some formatter like `prettier` or `biome`.

**Comment by Dhaiwat10** [comment]
Isn't that expected though? 🤔 If you look at `create-next-app`, it doesn't ship with a formatter or a config built in.

**Comment by nedsalk** [comment]
@Dhaiwat10 I was under the impression that adding some formatter would improve upon the "out of the box" experience. Whenever I was starting something, it was a bigger hassle to add a formatter than to remove it. If it's generally the norm that it's up to the user though, then let's not do the issue.

**Comment by Dhaiwat10** [comment]
@nedsalk I totally understand your reasoning, but like you said, let's follow the norm here and not include one.
