### ISSUE TITLE
Simplify Provider

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#176]
Provider contains methods and/or tests for deploying/calling contracts and transferring coins. Code related to contracts should be moved to `@fuel-ts/contract` and code related to coin transferring should be moved to `@fuel-ts/wallet`.

**Comment by QuinnLee** [comment]
I agree with this - I think the tests between contract, abi and provider packages got fragmented and led to some regressions.  This would help consolidate it and remove unnecessary duplication too
