### ISSUE TITLE
Transparent Tracking and Transaction Verification

### ISSUE THREAD

**Issue by Hman-ux** [FuelLabs/fuels-ts#1766]
### Motivation

Implement a blockchain-based system to transparently track and verify carbon offset transactions. This ensures the integrity and authenticity of offset credits and Implement a transaction verification mechanism to ensure that only tokens from verified projects can be traded on the platform.

### Usage example

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./CarbonOffsetToken.sol";
import "./VerificationContract.sol";

contract CarbonOffsetMarketplace {
    CarbonOffsetToken public carbonOffsetToken;
    VerificationContract public verificationContract;

    constructor(address _carbonOffsetTokenAddress, address _verificationContractAddress) {
        carbonOffsetToken = CarbonOffsetToken(_carbonOffsetTokenAddress);
        verificationContract = VerificationContract(_verificationContractAddress);
    }

    // Function to buy carbon offset tokens
    function buyToken(uint256 _tokenId) external {
        // Check if project is verified
        require(verificationContract.isVerified(carbonOffsetToken.offsetDetails(_tokenId).owner), "Project not verified");

        // Transfer token ownership
        carbonOffsetToken.transferFrom(carbonOffsetToken.ownerOf(_tokenId), msg.sender, _tokenId);
    }
}

### Possible implementations

In this example, the CarbonOffsetToken contract defines the properties and functionalities of carbon offset tokens, including minting new tokens with offset details. The VerificationContract contract allows for the verification of offset projects by third-party organizations. The CarbonOffsetMarketplace contract facilitates the buying of carbon offset tokens, ensuring that only tokens from verified projects can be traded.

These contracts provide a transparent and secure platform for tracking carbon offset transactions on the Fuel Labs network, promoting accountability and trust among participants

**Comment by Dhaiwat10** [comment]
Spam
