### ISSUE TITLE
Pay for transactions

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#177]
Currently everything is considered free, which allows us to structure things in ways we shouldn't. We did this because we lacked the primitives to do it proper, but we are ready to move on and actually start paying for transactions.

We should first move contract calling and such out of Provider (https://github.com/FuelLabs/fuels-ts/issues/176 is tracking this) since contract calling requires payment, which requires coin management, which bloats the Provider.

Then we should extend our code to pay for transactions using real coins from wallets.

Note: This would fix https://github.com/FuelLabs/fuels-ts/issues/159 as a side effect.

**Comment by AlicanC** [comment]
Initial work (paying only 1 for transactions) was implemented in #182.

Further work must be done to estimate gas and byte costs to insert actual amounts.

**Comment by adlerjohn** [comment]
The _price_ does not require estimation in the same say as the _limit_. Note that there is no byte limit, as the size of a tx is completely known. It's only the gas limit that need to be estimated.

Also note that the set of contract inputs also needs to be estimated similar to the gas limit.

**Comment by AlicanC** [comment]
Edited my comment to be more clear.

---

I think what we basically need is to satisfy this `verify_gas()` function here: https://github.com/FuelLabs/fuel-core/blob/c69cf223cc7cae4af824322798f49377027a601c/fuel-core/src/executor.rs#L317-L359

For calculating bytes we are missing `Transaction::metered_bytes_size()` and I think we should generally make sizes more accessible since it looks like we will have to make calculations like `fee_to_add = metered_bytes_size() + input_size + output_size + witness_size` to know how many bytes the transaction will be after adding the fee.

---

Fuel v1 fee management for reference: https://github.com/FuelLabs/fuel-js/blob/master/packages/wallet/src/index.js#L1031-L1105

**Comment by adlerjohn** [comment]
Aside, but witnesses shouldn't be included in the paid-for size since witness data is malleable by the block producer.

**Comment by luizstacio** [comment]
Now we can estimate the transaction fee, by executing a `dryRun` and using the returned `gasUsed`
