### ISSUE TITLE
Browser tests on CI are broken

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1770]
All recent browser test runs on CI are reporting this error:

```md
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Failed downloading chromedriver v121.0.6167.184: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.184/linux64/chromedriver-linux64.zip, retrying ...
```

Link to logs: https://github.com/FuelLabs/fuels-ts/actions/runs/7953245787/job/21708971853?pr=1768#step:9:29

**Comment by petertonysmith94** [comment]
Seems like the URLs have changed for the chromedriver distrubution [new urls](https://googlechromelabs.github.io/chrome-for-testing/).

Probably worth install the package to reduce reliance on external dependencies:
https://www.npmjs.com/package/chromedriver

Happy to take it on @Dhaiwat10 :)
