### ISSUE TITLE
Refactor the `ABI Coder` package

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#1795]
This issue should act as the epic with other issues spun off from here. 

The goals of this refactor are to:

- Reduce the coder touch points number of specific coder classes
- Decouple `encode` / `decode` and length validation logic
- Introduce a more functional approach (especially including any functionality covered by [private methods](https://github.com/FuelLabs/fuels-ts/blob/master/packages/abi-coder/src/coders/v1/enum.ts#L49))
- Improve error handling eminating from coders to enable #1552 
- Rethink the public entry points for `ABI Coder`
- Complete E2E testing for all supported types (_could_ be based on #2466)
- Deprecate `JsonAbiOld`
- Deprecate `UtxoIdCoder`

**Comment by nedsalk** [comment]
If changes happen to coders so that they don't return the `offset` value anymore, we should also update the `Interface.decodeLog` and `Interface.decodeFunctionResult` methods accordingly. See #2514.

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/FuelLabs/fuels-ts/issues/3031
