### ISSUE TITLE
Implement structs and enums from `type: contract` Fuel spec

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#18]
Currently, `function` is only one supported.

With more custom data types, abi of type `contract` with struct definitions will be added. https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/abi.md#json-abi-format

Implement `contract` type

**Comment by luizstacio** [comment]
Doing `swayswap-demo` has been a pain point as the returns are not strong typed but instead returning a `any` type. It's true for `ContractId`, `Address`, and custom structures.

### Use case;

Contract ABI
```
fn withdraw(amount: u64, asset_id: ContractId);
```

Types definition from the `typechain`
```
withdraw(
      amount: BigNumberish,
      asset_id: any,
      overrides?: Overrides & { from?: string | Promise<string> }
): Promise<any>;
```

Typescript implementation
```
const return = await swayswap.functions.just_return(1, {
      value: REACT_APP_TOKEN_ID
});
```
