### ISSUE TITLE
Subscriptions not closing after done

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1806]
Subscriptions that are not manually cancelled (e.g. with a break in a `for-await-of` loop) do not end when the underlying stream closes.
This is because the current implementation with the `FuelSubscriptionStream` stream transformer ignores the value which signifies stream completion `{value: undefined, done: true}`, as explained on the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader/read#return_value):
> If the stream becomes closed, the promise will be fulfilled with an object of the form `{ value: undefined, done: true }`.

**Comment by arboleya** [comment]
Related:
https://forum.fuel.network/t/failed-to-deploy-contract-using-typescript-sdk/4440
