### ISSUE TITLE
Add `randomUUID` into `@fuel-ts/crypto`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1807]
It's part of both the browser `crypto` package and the node `crypto` package, and we're already using it in e.g. [`launchNode`](https://github.com/FuelLabs/fuels-ts/blob/4bee7751f89c88f5e623c676b157b4a4a515b09b/packages/account/src/test-utils/launchNode.ts#L145).

**Comment by nedsalk** [comment]
For reference, there was already a PR that tried doing this but we didn't go with it: github.com/FuelLabs/fuels-ts/pull/1608

**Comment by mvares** [comment]
hey @danielbate! I can work on this issue?

**Comment by maschad** [comment]
Hey @mvares I see that you currently have two unblocked in-flight PRs 

- https://github.com/FuelLabs/fuels-ts/pull/2573
- https://github.com/FuelLabs/fuels-ts/pull/2549

It's best to see those through to completion before beginning any other work.

**Comment by mvares** [comment]
> Hey @mvares I see that you currently have two unblocked in-flight PRs
> 
> * [docs: unify wallet transfer docs #2573](https://github.com/FuelLabs/fuels-ts/pull/2573)
> * [chore: replacing all generic errors with `FuelError` #2549](https://github.com/FuelLabs/fuels-ts/pull/2549)
> 
> It's best to see those through to completion before beginning any other work.

Of course! But can you confirm whether this issue is blocked due to this [issue](https://github.com/FuelLabs/fuels-ts/pull/1608) or not?

**Comment by maschad** [comment]
It's currently not blocked but having read through that PR thread, I'm removing the `good first issue` because of the work that was involved. Sorry about that.
