### ISSUE TITLE
Trying to Deploy contract on Fuel ts using Ubuntu but it keeps failing 

### ISSUE THREAD

**Issue by Xammie2002** [FuelLabs/fuels-ts#1811]
### What version of fuels-ts are you using?

Version IV

### Steps to Reproduce

Please make it work ...reload a better contract 

### Expected Behavior

Should deploy smoothly when fixed 

### Actual Behavior

Keeps failing 
![IMG-20240220-WA0361](https://github.com/FuelLabs/fuels-ts/assets/117604094/234600ea-40ab-4aff-a649-99fee8cc8961)

**Comment by arboleya** [comment]
`Forc` says it couldn't fetch from Github.

Can you reset your connection and try again?

**Comment by arboleya** [comment]
Closing. If the problem persists, please reopen with additional details.
