### ISSUE TITLE
'@fuel-ts/account' contains conflicting star exports for the name 'TransactionType'

### ISSUE THREAD

**Issue by okanakdemirr** [FuelLabs/fuels-ts#1845]
### What version of fuels-ts are you using?

0.75.0

### Steps to Reproduce

Add "fuels": "^0.75.0", to your project dependencies and run it.

### Expected Behavior

It should run without fuels giving error about conflicting star exports for name.

### Actual Behavior

It gives this error:
ERROR in ./node_modules/fuels/dist/index.mjs 32:0-33
The requested module '@fuel-ts/account' contains conflicting star exports for the name 'TransactionType' with the previous requested module '@fuel-ts/transactions'

**Comment by arboleya** [comment]
I couldn't replicate this here; there are no conflicting type names.

These are similar but different.

https://github.com/FuelLabs/fuels-ts/blob/950f9be3856bbd00ee11c1d41f38729e0ea9c653/packages/transactions/src/coders/transaction.ts#L22-L26

https://github.com/FuelLabs/fuels-ts/blob/950f9be3856bbd00ee11c1d41f38729e0ea9c653/packages/account/src/providers/transaction-summary/types.ts#L29-L33

**Comment by arboleya** [comment]
Closing — If the problem persists, please reopen the issue with more information and a reproduction of the issue.
