### ISSUE TITLE
Improve `Predicate` class's type inference

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1851]
> Note: This issue was created after some findings from https://github.com/FuelLabs/fuels-ts/pull/1826 and needs for it to be merged before this can be worked on

When you instantiate a `Predicate` without providing a generic type argument like this:

```ts
const predicateParams: PredicateParams = { bytecode, provider, inputData: ['0xabc'] }
const predicate = new Predicate(predicateParams);
```

The `predicate` instance's type is inferred as `Predicate<string[]>`, whereas it should be `Predicate<[string]>`.

The internal type inference should be good enough to realize that there is only one input argument of `string`, rather than classifying the input data as an array of `string` elements of an unknown length.

**Comment by hrrl** [comment]
z

**Comment by hrrl** [comment]
z

**Comment by arboleya** [comment]
Since we expect the data to satisfy the `InputData[]` shape, I can't see how it could be a non-array.

Unless we'd define it as `InputData | InputData[]`, it all depends on how this is expected on the Sway side of things.

> cc @nedsalk

**Comment by nedsalk** [comment]
@Dhaiwat10 summed it up nicely in https://github.com/FuelLabs/fuels-ts/pull/1867#issuecomment-1993198460. Typescript inferring `string[]` instead of `[string]` for `['0xabc']` is default behavior, but it'd be superseded by the generated typegen type which would constrain it to `[string]`.

**Comment by arboleya** [comment]
I wonder if https://github.com/FuelLabs/fuels-ts/pull/1867 wouldn't also close this issue.

> _cc @petertonysmith94_

**Comment by petertonysmith94** [comment]
@arboleya It doesn't close this issue.

#1867 references added the known types from the given generated ABI, and I believe this is referencing _infer_ the types at a class level.

**Comment by petertonysmith94** [comment]
Out of curiosity - how often is the API consumed in this way - whereby, the user isn't using the typegen?

```ts
bytecode = fs.readFile(...)
new Predicate({ bytecode, ... })
```

**Comment by arboleya** [comment]
This is not recommended, so I'd say _almost_ never.

**Comment by petertonysmith94** [comment]
I'd favour not implementing this change.

The typegen is adding known types to the predicate, therefore, this change only benefits users on this alternative instantiation path. IMO the following type inference is adequate for non-typegen instantiation.

![Screenshot 2024-03-13 at 10 57 28](https://github.com/FuelLabs/fuels-ts/assets/16990131/c249e29d-ffb4-4aee-981f-f2a553653e5d)


or they may add the type themselves for a typed experience.

![Screenshot 2024-03-13 at 10 56 13](https://github.com/FuelLabs/fuels-ts/assets/16990131/581bffdf-d0bb-47a1-a4e8-45b37358f41d)

**Comment by arboleya** [comment]
@Dhaiwat10 @nedsalk Can we close this?

**Comment by nedsalk** [comment]
@arboleya yes, as @petertonysmith94 showcased `PredicateParams<T>` can already take in a generic which is used to type-constrain the inputs.
