### ISSUE TITLE
Add wallet connections to the `create-fuels` template

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1853]
> Incoming from https://github.com/FuelLabs/fuels-ts/discussions/1830

The `create-fuels` template app doesn't utilize the Wallet SDK and hence users cannot connect any account of their choice using a wallet extension like the Fuel Wallet. 

This is a crucial feature that we need if we want to let people deploy their create-fuels apps to testnet and eventually mainnet.

This issue should be worked on once #1852 has been solved.

**Comment by Bamiboygraphics** [comment]
Please, Merge this pr so we can test this feature. Thank you
