### ISSUE TITLE
Bump version in package.json and package-lock.json

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/fuels-ts#186]
The version in package.json and package-lock.json should match the latest version.

**Comment by sdankel** [comment]
It looks like this is already done using [multi-semantic-versions](https://github.com/FuelLabs/fuels-ts/blob/66f25194e10ba926f68babdd894bb4b8f30f2f8e/.github/workflows/sematic-release.yaml#L41). Is there something else needed here?

**Comment by pedronauck** [comment]
This was solved on this pull request #242 

https://github.com/FuelLabs/fuels-ts/blob/master/package.json#L3
https://github.com/FuelLabs/fuels-ts/blob/master/scripts/utils/changePackages.ts#L9-L16
