### ISSUE TITLE
New flaky test failling with test timeout

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1862]
We have a new flaky test: https://github.com/FuelLabs/fuels-ts/actions/runs/8248315155/job/22558365399?pr=1861#step:9:547

Maybe it is just a matter of increasing the test [timeout](https://github.com/FuelLabs/fuels-ts/blob/41aa6a1c198567f54c54be3cf33b93548cb40d63/packages/fuel-gauge/src/transaction-response.test.ts#L280)

UPDATE
This same test failure was also mentioned [here](https://github.com/FuelLabs/fuels-ts/issues/1755), but most likely it is not related

**Comment by arboleya** [comment]
Should this mention go as a comment on https://github.com/FuelLabs/fuels-ts/issues/1755?
