### ISSUE TITLE
Potential issue with CORS

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1869]
Incoming from @lzhabo:

> hey guys, we have started to run into 429 errors and cors errors for beta 5 massively
have you changed limits?

![cors](https://github.com/FuelLabs/fuels-ts/assets/26660/7822fb51-ce4a-4992-8ca4-58616670e3ca)

> cc @chlenc @EchoDex @Pobepto

**Comment by EchoDex** [comment]
Yes, that was my post. However, the issue I described on the forum was something I experienced. The CORS error, on the other hand, occurred to another developer on their machine.

**Comment by lzhabo** [comment]
@PaulZhemanov who had this problem. Please provide details abt where do you get this errors with more details abt ur computer and other

**Comment by arboleya** [comment]
Blocked - awaiting more information.

**Comment by luizstacio** [comment]
The CORS error happens once the user reaches the rate limit, the correct error is the 429 on the screenshot.
