### ISSUE TITLE
Vitepress plugins broken for integrated docs 

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#1879]
The follow two features are _not_ being rendered by the integrated docs, but are in the TypeScript docs. See below.
- Auto-generated imports.
- "Code in context" button.

### Integrated Docs

https://docs.fuel.network/docs/fuels-ts/wallets/private-keys/
<img width="698" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/16990131/124647c2-aa65-4e6b-b5d8-1ac3dc2072df">

### TypeScript Docs

https://fuellabs.github.io/fuels-ts/guide/wallets/private-keys.html

<img width="786" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/16990131/cc026831-589a-4234-a1b6-80cb692ca71d">

**Comment by arboleya** [comment]
Is it something to be fixed on our side or implemented in the docs hub?

**Comment by petertonysmith94** [comment]
@arboleya from what I can see, the documentation hub will pull our documentation as raw markdown. It then rebuild the markdown using their [custom plugin](https://github.com/FuelLabs/docs-hub/blob/7f19221824e6ab0287b2db42132c5ceaa17ca292/src/lib/plugins/plugins.ts#L95), which will disregard all Vitepress plugin functionality.

We could look at integrating our plugins into doc-hubs - however, haven't look too far into this solution.
