### ISSUE TITLE
`InsufficientFeeAmount` error resulted from a Predicate Transaction

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#1894]
Incoming from this forum post:
https://forum.fuel.network/t/insufficientfeeamount-error-when-dealing-with-predicate/4879/1

**Comment by arboleya** [comment]
Blocked by:
 - https://github.com/FuelLabs/fuels-ts/issues/1117

**Comment by Torres-ssf** [comment]
Blocked by https://github.com/FuelLabs/fuels-ts/pull/1895

**Comment by Torres-ssf** [comment]
Initially, I suspected this issue was due to an error during the dry run for estimating gas usage. However, the actual reason is simpler: insufficient resources allocated to the transaction to cover the fee.

This error could be prevented with the code snippet provided within this [comment](https://forum.fuel.network/t/insufficientfeeamount-error-when-dealing-with-predicate/4879/4?u=torres-ssf) 

Since there is nothing to fix within the SDK here, I'm closing this issue
