### ISSUE TITLE
NPM registry clean up

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#1896]
## Summary

- Documentation packages we currently maintain and actively publish to.
- Identify packages that are no longer maintained or published to.
- Look at deprecation or archiving of packages that are no longer maintained or published to.

### No longer maintained

We have the following published packages, in NPM under our workspace ([@fuel-ts/](https://www.npmjs.com/search?q=%40fuel-ts%2F)).

https://www.npmjs.com/package/@fuel-ts/predicate
https://www.npmjs.com/package/@fuel-ts/wallet
https://www.npmjs.com/package/@fuel-ts/hdwallet
https://www.npmjs.com/package/@fuel-ts/providers
https://www.npmjs.com/package/@fuel-ts/wordlists
https://www.npmjs.com/package/@fuel-ts/mnemonic
https://www.npmjs.com/package/@fuel-ts/signer
https://www.npmjs.com/package/@fuel-ts/wallet-manager
https://www.npmjs.com/package/@fuel-ts/keystore
https://www.npmjs.com/package/@fuel-ts/example-contract
https://www.npmjs.com/package/@fuel-ts/merkle-shared
https://www.npmjs.com/package/@fuel-ts/asm
https://www.npmjs.com/package/@fuel-ts/sparsemerkle
https://www.npmjs.com/package/@fuel-ts/merklesum
https://www.npmjs.com/package/@fuel-ts/constants
https://www.npmjs.com/package/@fuel-ts/testcases

---
## Fuel Frontend

- `@fuels/connectors`
Status: Active
Package: https://www.npmjs.com/package/@fuels/connectors
Source: https://github.com/FuelLabs/fuel-connectors/blob/main/packages/connectors/package.json

- `@fuels/react`
Status: Active
Package: https://www.npmjs.com/package/@fuels/react
Source: https://github.com/FuelLabs/fuels-npm-packs/blob/main/packages/react/package.json

### No longer maintained

- `@fuel-wallet/react`
Migrated to `@fuels/react`

**Comment by SEEDART007** [comment]
can i work on this?

**Comment by petertonysmith94** [comment]
@SEEDART007 No - I don't believe it would be possible.

There are plenty of other [issues](https://github.com/FuelLabs/fuels-ts/issues) you could pick up 😄

**Comment by arboleya** [comment]
@petertonysmith94 Should we also close this one?

**Comment by petertonysmith94** [comment]
> @petertonysmith94 Should we also close this one?

I personally think depreciating all old and unmaintained packages from NPM is a worthwhile exercise. What do you think?

I would think it makes most sense after (the following), so maybe we can close and revisit:
- https://github.com/FuelLabs/fuels-ts/issues/2493

**Comment by arboleya** [comment]
Agreed.
