### ISSUE TITLE
Improve `launchTestNode` docs to point to relevant typedocs

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#1898]
Due to the problem explained in #1897, I could not link the `launchTestNode` docs to its relevant typedoc as explained in https://github.com/FuelLabs/fuels-ts/pull/1356#discussion_r1527923432.

Blocked by:
- #1356
- #1897

**Comment by maschad** [comment]
Blocked by https://github.com/FuelLabs/fuels-ts/issues/2919
