### ISSUE TITLE
Docs: Testing > Launching Nodes

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1915]
Describe all of its options and provide different examples covering multiple use cases.

 - Short-Lived Nodes? / Launching Nodes
   - Options
   - Examples

> _Consider documenting options like [this](https://fuellabs.github.io/fuels-ts/guide/cli/config-file.html), as it is superior to the auto-generated Typedocs._

**Comment by arboleya** [comment]
@nedsalk Is this still a thing? Or has it been resolved in #1356?

**Comment by nedsalk** [comment]
@arboleya It's still a thing and right now I'm taking a look at slimming down `launchNode` in general post-#1356 and was planning on taking this issue. I'll assign it to myself now.

**Comment by nedsalk** [comment]
> No problem, but this issue is just about testing, correct?

Oh, you're right! Then this issue as it is named is resolved. However, we still haven't documented the `launchNode` utility itself anywhere. Should we just rename this issue to `Docs: Launching Nodes Programmatically`? Would the `p0` still remain?

**Comment by arboleya** [comment]
Created a fresh issue here to reduce the noise:
 - https://github.com/FuelLabs/fuels-ts/issues/2572
