### ISSUE TITLE
Docs: Testing > Launching Test Nodes

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1916]
Describe all of its options and provide different examples covering multiple use cases.

 - Short-Lived Test Nodes? Launching Test Nodes
   - Options
   - Examples

> _Consider documenting options like [this](https://fuellabs.github.io/fuels-ts/guide/cli/config-file.html), as it is superior to the auto-generated Typedocs._

**Comment by nedsalk** [comment]
Blocked by:
- #1356

That PR already has documentation that this issue requests and it might be enough. I'll reevaluate once it's merged.

**Comment by nedsalk** [comment]
Resolved in https://github.com/FuelLabs/fuels-ts/pull/1356.
