### ISSUE TITLE
Docs: Testing > Generating Test Wallets

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#1917]
Improve what we already [have](https://fuellabs.github.io/fuels-ts/guide/wallets/test-wallets.html), re-targeting the tone to go nicely with the other testing pages.

 - Generating Test Wallets
   - Options
   - Examples

> _Consider documenting options like [this](https://fuellabs.github.io/fuels-ts/guide/cli/config-file.html), as it is superior to the auto-generated Typedocs._

**Comment by nedsalk** [comment]
Blocked by:
- #1356

That PR introduces `WalletConfig` for testing with `launchTestNode` and this issue should be done after it's merged.

**Comment by nedsalk** [comment]
Resolved in #1356.
