### ISSUE TITLE
Docs: native types don't link anywhere

### ISSUE THREAD

**Issue by great9** [FuelLabs/fuels-ts#1925]
### What version of fuels-ts are you using?

0.77

### Steps to Reproduce

Try to find any documentation mentioned under "AssetId", they link to contract-types.md which is non-existant
https://github.com/FuelLabs/fuels-ts/blob/v0.77.0/apps/docs/src/guide/types/native-parameters.md

### Expected Behavior

There should be a file at least

### Actual Behavior

Nothing.

**Comment by arboleya** [comment]
You need to access the rendered docs to see the _rendered_ code snippets:
 - https://fuellabs.github.io/fuels-ts/guide/types/native-parameters.html#assetid
