### ISSUE TITLE
Create a Stackblitz dev container for `create-fuels`

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1927]
It could be worth having a Stackblitz template for the create-fuels template app. This will be a fullstack Fuel dev container that works fully in the browser.

We should mention this in our docs if we create one such container, as well as using it in the [bug issue template](https://github.com/FuelLabs/fuels-ts/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug.yaml).

**Comment by maschad** [comment]
We will probably want to have this running against a Testnet fuel node, so I can re-address it once that's live.

**Comment by danielbate** [comment]
We can unblock this now due to devnet.

**Comment by arboleya** [comment]
Ideally, we should be able to run `fuel-core` and `forc` node on [Stackblitz](https://stackblitz.com/). 🙃 

Simple things:

```ts
// package.json
{
  "devDependencies": {
    "@fuels/forc": "0.60.0",
    "@fuels/fuel-core": "0.30.0",
  }
}
```

If we'd cross-publish `fuelup`:

```ts
// package.json
{
  "scripts": {
    "install": "fuelup default testnet",
  },
  "devDependencies": {
    "@fuels/fuelup": "0.26.0"
  }
}
```

```toml
# fuel-toolchain.toml
[toolchain]
channel = "testnet"

[components]
forc = "0.60.0"
fuel-core = "0.30.0"
```

We should consider approximating the Rust and NodeJs ecosystems.

Cross-publishing some crates to NPM could be a start. 🙂

**Comment by arboleya** [comment]
Yes, we should consider approximating the Rust and NodeJs ecosystems.

Cross-publishing crates to NPM could be a good start. 🙂

Just like it happens with `fuel-asm` ([source](https://github.com/FuelLabs/fuel-vm/blob/56d7deb66a70964d2b22de80299585f2b5d36fab/.github/workflows/ci.yml#L298-L325)).

**Comment by danielbate** [comment]
Marking as blocked as this topic is being investigated by product.

**Comment by arboleya** [comment]
Let's close for now.
