### ISSUE TITLE
`create-fuels` add an option for plain JS or another popular JS framework

### ISSUE THREAD

**Issue by cold-briu** [FuelLabs/fuels-ts#1945]
### Motivation

Help developers initialize a full stack Fuel dApp with minimal friction

### Usage example

`npm create fuels -vue`

**Comment by danielbate** [comment]
Added as a low priority for `1.0.0` as a candidate around the additional templating discussion.

**Comment by danielbate** [comment]
This will be solved by #2838, which will introduce a simpler `create fuels` template. I haven't seen much demand for JS and I don't think supporting it is worth the demand level. Can reopen this as support for a JS template if that changes. But I'd encourage users to adopt TS to benefit from the e2e type support with their smart contracts that TS offers.

**Comment by danielbate** [comment]
This will be solved by #2838, which will introduce a simpler `create fuels` template. I haven't seen much demand for JS and I don't think supporting it is worth the demand level. Can reopen this as support for a JS template if that changes. But I'd encourage users to adopt TS to benefit from the e2e type support with their smart contracts that TS offers.
