### ISSUE TITLE
The fuels CLI `dev` process gets stuck sometimes

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#1951]
The process sometimes gets stuck on this message after we change a program's code:

`Generating types...`

It doesn't even let you quit the process if you hit cmd C.

Possibly related:
 - https://github.com/FuelLabs/fuels-ts/issues/1886

> Incoming from and for repro: https://github.com/FuelLabs/docs-hub/pull/203

**Comment by danielbate** [comment]
Closing in favour of #1886
