### ISSUE TITLE
Number can only safely store up to 53 bits during decoding of logs

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/fuels-ts#1971]
Hi guys, we are still playing around the Envio indexer and for now, I found some edge case

I have created a repo that emits event and decodes a logs
https://github.com/compolabs/orderbook-indexer-synchronizer

And with one case I have faced into a error

`Number can only safely store up to 53 bits`

You can reproduce this 

1. **Clone the Repository and install dependencies**
   ```
   git clone git@github.com:compolabs/orderbook-indexer-synchronizer.git
   cd orderbook-indexer-synchronizer
   npm i
   ```

2. **Create a `.env` File**
   Add your private key to the `.env` file.
   ```
   echo "ALICE=<YOUR PRIVATE KEY>" >> .env
   ```

3. **Build Contracts**
   Compile the smart contracts.
   ```
   forc build
   ```

4. **Make sure you have this contract in addresses.json**
```
{"contractId":"0xe1631771301d5ba38fb7dc51b2815e9d29ef12cae10c6aa7e492008093cde318","blockNumber":8268037}

```

5. **Run "should decode data" Test**

**Comment by danielbate** [comment]
Hey @chlenc, think I'm missing some additional config.

```sh
 FAIL  tests/data_encode.test.ts
  ● Test suite failed to run

    DB_NAME is required

       7 |   const result = process.env[name];
       8 |   if (result == null && !optional) {
    >  9 |     throw new Error(`${name} is required`);
         |           ^
      10 |   }
      11 |   return result;
      12 | }
```

**Comment by danielbate** [comment]
@maschad this doesn't seem to have gone `stale` yet 🤔

**Comment by maschad** [comment]
@danielbate based on the CI action job it needs to be [14 full days](https://github.com/FuelLabs/fuels-ts/pull/2199/files#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894R21)
