### ISSUE TITLE
Replace all occurrences of `Error` to `FuelError`

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2001]
Change all instances of `new Error`, and replace with a FuelError with an appropriate error code.

For context, please reference this [issue](https://github.com/FuelLabs/fuels-ts/issues/1556).

**Comment by kartikey315** [comment]
Hey @petertonysmith94, I want to work on this issue please guide me.

**Comment by maschad** [comment]
Hey @kartikey315 thanks for your interest in taking this on! 

Essentially there are some instances of the [standard Error](https://github.com/FuelLabs/fuels-ts/blob/master/packages/utils/src/test-utils/expectToBeInRange.ts#L7) still being thrown which we would like to convert to our custom [FuelError](https://github.com/FuelLabs/fuels-ts/blob/master/packages/errors/src/fuel-error.ts#L5) class with it's own set of [error codes](https://github.com/FuelLabs/fuels-ts/blob/master/packages/errors/src/error-codes.ts#L4) 

Feel free to review our [Contributing guide](https://github.com/FuelLabs/fuels-ts/blob/master/CONTRIBUTING.md#L0-L1) to get started.

**Comment by kartikey315** [comment]
Thanks @maschad. I will get started with this.

**Comment by maschad** [comment]
Hey @kartikey315 have you been able to make any progress on this?

**Comment by VedantGonnade** [comment]
Hey @petertonysmith94 I would like to work on this task.

**Comment by arboleya** [comment]
@VedantGonnade I just noticed we already have an ongoing PR for this issue:
 - https://github.com/FuelLabs/fuels-ts/pull/2549

Please consider picking up another `good first issue` if you want. 🙂 

Thank you for your interest in contributing to the project.

**Comment by msensys** [comment]
At the moment, I'm working to close this issue 💯

**Comment by arnavbee** [comment]
Hello, has this issue been resolved?

**Comment by maschad** [comment]
Hey @arnavbee no it hasn't yet. If you are interested feel free to begin working on it.

**Comment by petertonysmith94** [comment]
Hey @arnavbee 👋🏼 

Apologies - @mvares already had a branch and this should now be address:
- https://github.com/FuelLabs/fuels-ts/pull/2879

You can check out our [Good First Issues](https://github.com/FuelLabs/fuels-ts/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) for good places to start or let us know if something else peeks your interests :)
