### ISSUE TITLE
Merge `forc-projects-experimental` with `forc-projects` in `fuel-gauge`

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#2005]
Based off of [comments](https://github.com/FuelLabs/fuels-ts/pull/1832#discussion_r1547627395) in #1832, we merge `forc-projects-experimental` and `forc-projects` within `fuel-gauge`. This work should no longer be considered experimental.

This should include the following changes:
- Merge the forc project directories
- Have a version prefix inside `forc-projects` (i.e. `v0` and `v1`)
- Integrate this with the `getFuelGaugeForcProject` utility function and incorporate it in the experimental tests

**Comment by arboleya** [comment]
This should probably go after:
 - #2017
