### ISSUE TITLE
Error handling for programs

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2023]
The documentation on errors and/or handling of errors for different program types ([contracts](https://docs.fuel.network/docs/nightly/fuels-ts/contracts/), [scripts](https://docs.fuel.network/docs/nightly/fuels-ts/scripts/) and [predicates](https://docs.fuel.network/docs/nightly/fuels-ts/predicates/)) seems sparse. It would be worthwhile noting what error codes might be expected, under what conditions and best practices for handling these erroneous conditions:

- Methods of debugging these errors.
- Methods to resolve common problems.
- Any clean up process that might need to occur.

We could link back to [error codes](https://docs.fuel.network/docs/nightly/fuels-ts/errors/error-codes/#error-codes) and explain the resolutions there, or add sections for error handling to each program type.

---

These were the resources that I found on errors:

**Contracts**
> https://docs.fuel.network/docs/nightly/fuels-ts/contracts/call-parameters/#gas-limit-parameter

Small section on the `gasLimit` related error.

**Scripts**
> https://docs.fuel.network/docs/nightly/fuels-ts/scripts/instantiating-a-script/#instantiating-a-script

Small snippet error handling around the script request.

**Predicates**
> https://docs.fuel.network/docs/nightly/fuels-ts/predicates/#debugging-predicates
Small section on debugging predicate

> https://docs.fuel.network/docs/nightly/fuels-ts/predicates/send-and-spend-funds-from-predicates/#spending-entire-predicate-held-amount

Small section on the error messages

**Comment by arboleya** [comment]
Could you please elaborate further on _"error handling for different program types"_?

Maybe I'm missing context and what exactly led you to this conclusion.
