### ISSUE TITLE
chore: Remove unused files and exports 

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2027]
Running `knip` reports the following 

### unused files
<img width="544" alt="Screenshot 2024-04-08 at 11 51 28 AM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/e28b7397-e1c8-4934-88f4-6fdf8f94d050">

### unused exports
<img width="849" alt="Screenshot 2024-04-08 at 11 51 57 AM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/03627bd0-feef-46dd-b79b-73f63276026b">

### unused export types
<img width="874" alt="Screenshot 2024-04-08 at 11 52 38 AM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/ef76818c-4f4e-4a76-a63b-1468b8a2fbef">

I suspect there may be some more configuration to be done to get this to be more accurate.

Once #2024 is resolved this can be done.

**Comment by maschad** [comment]
Agreed @arboleya I think we will have to add a bit of [manual configuration ](https://knip.dev/features/rules-and-filters) around the _unused export_ [issue type](https://knip.dev/reference/issue-types) to ensure we don't remove those. It will be quite a bit of grunt work upfront unfortunately.

**Comment by arboleya** [comment]
If I'm following the idea here (and on https://github.com/FuelLabs/fuels-ts/pull/2026), the introduction of `knip` is to automate and make up for [manual] things we can forget and may go unnoticed. However, considering the configuration exceptions will also be manual, can go outdated, and be somehow forgotten, will it still be an improvement over the current scenario?

**Comment by maschad** [comment]
That's a good point, but I don't think that it applies to `unused files` or `unresolved imports` or `duplicate exports`, as we shouldn't seek to introduce anymore of those.

The manual configuration applies primarily  to the `unused exports` issue type , **but** considering that in an _ideal_ scenario, all the exported constants that would be consumed by external libraries would be distributed across `constants.ts` files, we could then rationalize that other constants would unused. As you rightly point out this will still be manual but I think it reduces the overall manual overhead considering the points mentioned above.

**Comment by webpro** [comment]
Apologies in advance for my unsolicited feedback here.

> What is considered an unused export?
> 
> For instance, we don't want to stop exporting constants meant to be used externally.

By default, exports of entry files are not reported as unused (this is configurable though). In other words, in this case, you could add `constants.ts` as an entry file and call it a day. 

> However, considering the configuration exceptions will also be manual, can go outdated, and be somehow forgotten, will it still be an improvement over the current scenario?

This is a great point. For example, ESLint disable-line comments, rules or even plugins might no longer be necessary at some point too. This type of maintenance is almost inevitable. Knip tries to be [as unobtrusive as possible](https://knip.dev/explanations/why-use-knip#unobtrusive). For instance, as a solution for the same issue, exports can be JSDoc-tagged `@public`, serving as (internal) documentation at the same time.

AMA! There's some ways to go about configuration, I'm sure there's a way to knip it ✂️

**Comment by maschad** [comment]
Thanks for creating this awesome library @webpro 🚀  , and also thanks for your input, really appreciate your direction on this 😄 . I think right now all the reported unused files and exports are misreported for us, and so the configuration would be disproportionately more than the size savings. 

- For instance [`BYTES_32` and a number of other constants](https://github.com/FuelLabs/fuels-ts/blob/master/packages/abi-coder/src/utils/constants.ts#L36) are reported as **Duplicate exports** even though they aren't duplicates but rather re-used.

- All these [`ErrorCode`s](https://github.com/FuelLabs/fuels-ts/blob/master/packages/errors/src/error-codes.ts#L101) are reported as unused as well, and we wouldn't want to set that file as our entry file, rather if it could determine that the fact it's exported via the [index entry point](https://github.com/FuelLabs/fuels-ts/blob/master/packages/errors/src/index.ts#L1) that would be useful.

- All the reported unused files are actually configuration files such as [vitest test configs](https://github.com/FuelLabs/fuels-ts/blob/master/apps/docs/src/vite.config.ts#L0-L1) for example. 

I think we can revisit this issue in the future as `knip` matures.
