### ISSUE TITLE
chore: ensure consistent dependency versions across packages

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2028]
We have some [multiple packages requiring the same dependency with different the versions](https://github.com/FuelLabs/fuels-ts/blob/master/pnpm-lock.yaml#L7689-L7698) it would be useful to sync them using something like [syncpack](https://github.com/JamieMason/syncpack)

**Comment by maschad** [comment]
Awesome! Thanks for looking into this.

**Comment by JamieMason** [comment]
I can try and help @richardgreg, what are you trying to configure?

**Comment by JamieMason** [comment]
No problem @richardgreg. If you can give me some information on which packages you are expecting to change but don't, I'll do my best to try and help you.

**Comment by JamieMason** [comment]
When I search for `@typescript-eslint/types` in your branch [chore/packages-dependency-consistency](https://github.dev/richardgreg/fuels-ts/tree/chore/packages-dependency-consistency) there are no results?

![](https://github.com/FuelLabs/fuels-ts/assets/320492/a5accea2-baa1-46fc-bf49-a8c39b1fedb0)

**Comment by JamieMason** [comment]
Ok great, let me know if you have any questions or you notice something which you don't think is right and I can try and help you. You're not using `@typescript-eslint/types` in your project so I'm guessing whatever that was is resolved.
