### ISSUE TITLE
Top up button for `create-fuels` doesn't refresh balance

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2048]
## Summary

When clicking the `Top-up Wallet` button, the balance doesn't refresh.

### Expected

The current balance to be updated with the new balance.

### Actual

The balance does not change.

**Comment by Dhaiwat10** [comment]
This used to work fine but now this seems to be a theme in almost all interactions where the balance needs to be re-fetched. It is indeed re-fetched but for some reason the update isn't coming in time. The query is almost too 'fast'. This should absolutely be investigated
