### ISSUE TITLE
Consider reevaluating the documentation tool

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2074]
The idea here is to evaluate whether it'd be wise to move away from Vitepress to something like [MDBook](https://github.com/rust-lang/mdBook).

Such a move could be a step towards a more standardized documentation approach that aligns more with all Rust repos.

If MDBook doesn't work well, we could try enforcing a similar structure instead of switching to it.

Whatever direction we go, we must keep all the snippet functionalities we currently have.

**Comment by arboleya** [comment]
cc @sarahschwartz @petertonysmith94

**Comment by danielbate** [comment]
@arboleya given #2651 do we still want to do this?

**Comment by arboleya** [comment]
I don't think so, not for now, at least.

Changing the tool would be a colossal effort anyway, right?

Adding preview links to our PRs may be a quicker way of shortening the feedback loop for the time being.

**Comment by maschad** [comment]
Closing in favour of https://github.com/FuelLabs/fuels-ts/pull/2651
