### ISSUE TITLE
Update SDK for Sway's change to use IR by default.

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#208]
Tracking https://github.com/FuelLabs/fuels-rs/issues/201 for the TS side

**Comment by mohammadfawaz** [comment]
`forc v0.10.0` is now [available](https://github.com/FuelLabs/sway/releases/tag/v0.10.0).

**Comment by mohammadfawaz** [comment]
There are still discussions around the best way forward with the handling of complex types that fit in a word (e.g. `array[1]`, `struct { x: u64 }`, `str[8]`, etc). There is no need to change anything on the TS side until that's resolved.

**Comment by digorithm** [comment]
@QuinnLee @AlicanC What's the current state of this issue?

**Comment by AlicanC** [comment]
Looks like this boils down to following the table here: https://github.com/FuelLabs/sway/issues/1368

That was done on: https://github.com/FuelLabs/fuels-ts/pull/290
