### ISSUE TITLE
Remove `v0` encoding logic

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#2109]
Once #2050 has been merged and [sway encoding improvements](https://github.com/FuelLabs/sway/issues/5727) to `v1` have been completed, we should remove all `v0` specific logic:

- Encoding should now fallback to `v1`, strategy can remain in place for future custom encoding
- Remove redundant `v0` coders, some redistribution may be required for anything still being used by transactions
- Remove `v0` function selector encoding and contract call script
- Remove heap pointer logic
- Remove heap type validation for multicalls
- Remove experimental tests
- Ensure documentation type support is up to date

**Comment by arboleya** [comment]
@danielbate I think we can start this right after https://github.com/FuelLabs/fuels-ts/pull/2050, regardless of https://github.com/FuelLabs/sway/issues/5727.

Only v1 will be accepted anyway, and the stabilization should be transparent.

**Comment by danielbate** [comment]
Agreed 👍🏻
