### ISSUE TITLE
Set up Community Standards

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2129]
We should complete [the community standards](https://github.com/FuelLabs/fuels-ts/community) for the repo.

**Comment by mvares** [comment]
Currently, we haven't completed all tasks from the Community Standards. To complete one of these, we need to add a CODE_CONDUCT file that meets our needs as an open-source project.

I was searching for some codes of conduct common in open-source projects, and I found this quite interesting:

https://www.contributor-covenant.org/
