### ISSUE TITLE
Remove stale binaries from repository

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#213]
Remove stale binaries from the project and also static dependencies.
The main purpose is to keep projects aligned with the latest versions of the Fuel ecosystem (compiler, libs, etc...).

Add on CI
- Install `forc` latest version
- Install contract dependencies
- Build contracts
- Run tests

**Comment by digorithm** [comment]
Same issue being tracked on `fuels-rs`: https://github.com/FuelLabs/fuels-rs/issues/210.

**Comment by luizstacio** [comment]
For install `forc` we now have a `forc-bin` package and also a GitHub action to help; https://github.com/marketplace/actions/install-fuel-toolchain

**Comment by luizstacio** [comment]
This is already implemented on the current CI.
