### ISSUE TITLE
Markdown validation not validating markdown link fragments

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2141]
We have links to sections on a page `#typegen` (see [example](https://github.com/FuelLabs/fuels-ts/blob/c9597f91c05e4f2320958d4de33e8f26652cff57/apps/docs/src/guide/fuels/commands.md?plain=1#L70-L71)). There is currently no validation to check that they exist and therefore, are broken.|

We should add validation to ensure that, all our links work as expects, so the user can navigate the documentation with ease.

**Comment by maschad** [comment]
Might be worth adding a CI job with a markdown link checker such as https://github.com/tcort/markdown-link-check

**Comment by arboleya** [comment]
Like this one? [.github/workflows/md-lint.yaml](https://github.com/FuelLabs/fuels-ts/blob/master/.github/workflows/md-lint.yaml)

cc @Dhaiwat10
