### ISSUE TITLE
Multiple contract calls in a single transaction

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#216]
if it's possible to write a script that can call multiple contract/contracts methods/calls on a single TX. Would be amazing if the SDK provide a simple API to build these actions in a bundle TX.

# Use case

On swayswap to create liquidity between two pairs, you need to follow steps 1, 2, and 3 in sequence. This executes 3 transactions but would be nicer to build all 3 method calls, combine and send in a single TX.

1. Deposit coin A
2. Deposit coin B
3. Create liquidity

<img width="500" alt="Screen Shot 2022-04-13 at 6 03 06 PM" src="https://user-images.githubusercontent.com/3941923/163222523-bba9e1b6-a0f9-4bd8-a81f-fcae6ca7da74.png">

**Comment by AlicanC** [comment]
Update:

I finally got Multicall script to work today, but a lot needs to happen before we can merge it:
- It currently works with Forc@master. Forc with the features we need must be stable.
- The `@fuel-ts/contract` API still only supports single calls. (@camsjams' #303 has `prepareCall` that will be useful for this.)
- The script works with the heap so it needs `std::alloc` and `std::ptr`: https://github.com/FuelLabs/sway/pull/1627
- The script uses generics so it needs this fixed: https://github.com/FuelLabs/sway/issues/1628 (PR: https://github.com/FuelLabs/sway/pull/1671)

Some good-to-haves would be:
- https://github.com/FuelLabs/sway/issues/1077 (PR: https://github.com/FuelLabs/sway/pull/1118)
- https://github.com/FuelLabs/sway/issues/1188
- https://github.com/FuelLabs/sway/issues/1585
