### ISSUE TITLE
chore: remove `sway-libs` dependency

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2160]
`sway-libs` doesn't keep compatibility with `forc`, resulting in [broken code snippets](https://github.com/FuelLabs/fuels-ts/pull/2045/files#diff-1a11e2c177f1f12253aa42005f3290260aa32da5c9362433ee63dadd2aa5c5fa) during `forc` upgrades 

_Originally posted by @arboleya in https://github.com/FuelLabs/fuels-ts/pull/2045#discussion_r1578445319_

**Comment by arboleya** [comment]
I am already doing this as part of #2042. 👋

**Comment by arboleya** [comment]
Relevant places to change should involve the ones included in these commits:
 - https://github.com/FuelLabs/fuels-ts/pull/2045/commits/47c511eb3fe19e7cd1b39f0948649cd47f4c3e0a
 - https://github.com/FuelLabs/fuels-ts/pull/2045/commits/be3accd9594a4b2be5d061fbfdf0b8451d802cb2
