### ISSUE TITLE
Create dry-tun transaction enabling tx preview

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#217]
We should be to preview transactions before signing/sending them.

**Comment by QuinnLee** [comment]
@luizstacio do you have an example of this? should this be a method that returns json?

**Comment by QuinnLee** [comment]
following https://github.com/FuelLabs/fuels-rs/issues/200

**Comment by luizstacio** [comment]
> following [FuelLabs/fuels-rs#200](https://github.com/FuelLabs/fuels-rs/issues/200)

Yeah, I think the discussion there is what we should do here also.

In this direction, we have extracted the logic already to [build the transaction](https://github.com/FuelLabs/fuels-ts/blob/0177b66291463b3053afc02e9f1156c848502b87/packages/contract/src/contract.ts#L37), when we add the `transformRequest`.

Maybe we should add a way to call it from a contract instance, something like; `contract.<simulate | transitions | ????>.<method>`?

**Comment by QuinnLee** [comment]
> In this direction, we have extracted the logic already to [build the transaction](https://github.com/FuelLabs/fuels-ts/blob/0177b66291463b3053afc02e9f1156c848502b87/packages/contract/src/contract.ts#L37), when we add the transformRequest.

We have `prepareCall` and `dryRun` - I think we can close the issue.

**Comment by luizstacio** [comment]
@QuinnLee I think this is more a `simulate` transaction. I think we need to run `dryRun` using `utxo_validation`.
