### ISSUE TITLE
Replace `eslint` and `prettier` with `biome`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2195]

**Comment by maschad** [comment]
I've been experiencing some strange errors with eslint locally and also [on ci](https://github.com/FuelLabs/fuels-ts/actions/runs/8914039554/job/24480786358) despite not upgrading it, running `biome` I am already impressed with it's performance and it's output, so I'll push forward with this.
<img width="835" alt="Screenshot 2024-05-01 at 2 41 33 PM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/79f56dbd-a1c1-4707-abe7-fde4e93fdaa4">

**Comment by maschad** [comment]
I think we can revisit this in the future but I wouldn't say this adds value at the moment based on the description https://github.com/FuelLabs/fuels-ts/pull/2219

**Comment by danielbate** [comment]
@FuelLabs/sdk-ts I'd like to propose we close this for now.

**Comment by arboleya** [comment]
Agreed.
