### ISSUE TITLE
Use Better Error Codes For GraphQL Client Errors

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2208]
We need to improve the error codes used when a GraphQL query/mutation/subscription throws an error from the client. This should be done on:

1 - [FuelGraphqlSubscriber](https://github.com/FuelLabs/fuels-ts/blob/cfc4fde37a2f2d58a4c97d81dfe9f00756068669/packages/account/src/providers/fuel-graphql-subscriber.ts#L50-L54)

2 - [Provider.createOperations](https://github.com/FuelLabs/fuels-ts/blob/bb8789274f14988502e9ffe6ea4b4c62d442ee53/packages/account/src/providers/provider.ts#L463-L468)

This involves analyzing the `errors` array returned from the graphQL response. An error entry looks similar to this:
```ts
  {
    message: 'not enough coins to fit the target',
    locations: [ { line: 2, column: 3 } ],
    path: [ 'coinsToSpend' ]
  }
```  

In this case, we can identify that the error was caused by the query `coinsToSpend`, and the error message is  `not enough coins to fit the target`.

When implementing this error handling, is essential to identify what was the path ( query/mutation/subscription ) and use a proper [FuelError](https://github.com/FuelLabs/fuels-ts/blob/master/packages/errors/src/fuel-error.ts#L5) code

> Related to this [comment](https://github.com/FuelLabs/fuels-ts/pull/2128#discussion_r1584909181)

**Comment by arboleya** [comment]
The scope of this issue seems a bit open.

What should one do here exactly?

**Comment by Torres-ssf** [comment]
@arboleya I believe we just need to use more specific error codes. 

For instance, if we validate that the used `path` was the mutation `submit` or even the subscription `submitAndAwait`, 

```ts
{
  message: 'error message here',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'submit' ] // or ['submitAndAwait']
}
```

Then we can use a more appropriate error code, like: `TRANSACTION_FAILED`, because we know for sure that these 2 are used only when submitting a transaction.

```ts
throw new FuelError(
  FuelError.CODES.TRANSACTION_FAILED,
  graphQlResponse.errors[0].err.message)
);
```

We do not need to treat messages, since we can use the same ones thrown by the client.

Perhaps we should start using better error codes only for transaction submission failure. If we the extracted `path` is not related to transaction submission, we can use the generic error code `INVALID_REQUEST`

**Comment by petertonysmith94** [comment]
Is this related to or the same as?
- https://github.com/FuelLabs/fuels-ts/issues/2467

**Comment by petertonysmith94** [comment]
Going to unassign myself from this for now.

**Comment by Torres-ssf** [comment]
Closing this in favor of https://github.com/FuelLabs/fuels-ts/issues/2467
