### ISSUE TITLE
Export [test] utilities in umbrella package

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2223]
We should export all secondary entry points (utilities) using dedicated entry points in the `fuels` umbrella package.

For example:
 - `fuels/test-utils` — all `test` utilities from all sub-packages
 - `fuels/cli-utils` — all `CLI` utilities from all sub-packages

The idea is that each of these would consolidate all utilities of the same group.

A few examples I grabbed from the codebase:

```ts
import { generateTestWallet } from '@fuel-ts/account/test-utils';
import { expectToThrowFuelError } from '@fuel-ts/errors/test-utils';
import { findBinPath } from '@fuel-ts/utils/cli-utils';
```

The umbrella package should be the only thing users should have to deal with.

**Comment by nedsalk** [comment]
[Related comment](https://github.com/FuelLabs/fuels-ts/pull/1356/files#r1530301679). That PR has the implementation for the infrastructure part of this PR so one can take inspiration from it.
