### ISSUE TITLE
Add variable outputs when calling a contract

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#223]
## Description

When calling a contract that does a transfer of coins, we need to also add a new [variable output](https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/tx_format.md#outputvariable) to inform that something will be created from that method call.

### Example

```rust
fn transfer_coins_to_output(coins: u64, asset_id: ContractId, recipient: Address) {
    transfer_to_output(coins, asset_id, recipient);
}
```

**Comment by adlerjohn** [comment]
Note that without simulating the tx, there's no way to know how many variables outputs you need. Therefore it should simply be let up to the user to append as many as they want. The Rust SDK does this.
