### ISSUE TITLE
Stop silencing errors during `launchNode` startup

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2248]
When using the `launchNode` utility, some node startup errors derived from improper configs are silenced.

This makes debugging issues tricky and prevents the utility from working as expected.

> Reported by @LuizAsFight

**Comment by nedsalk** [comment]
@LuizAsFight it would be great if you could give an example here for us to have something concrete to work with.

**Comment by nedsalk** [comment]
@petertonysmith94 it might be because the child's `stdout` and `stderr` are [piped](https://github.com/FuelLabs/fuels-ts/blob/0a09fa7d1440787ed28a179b0534369cb48471ab/packages/account/src/test-utils/launchNode.ts#L243) into the corresponding `process` methods.

**Comment by arboleya** [comment]
Could it be resolved together?

**Comment by LuizAsFight** [comment]
I don't have one example now @nedsalk , but I remember I got this by informing incorrect chainConfig or incorrect initialization params, then the error produced by the node when starting it was not being shown

**Comment by nedsalk** [comment]
@arboleya yeah, I'll do it in #2483. I'll put that PR into draft mode until I cover everything there.
