### ISSUE TITLE
Move fix values to constants package

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#225]
We have some constants around the system that can be moved to the package constants or better organized inside the package.

Ref.: https://github.com/FuelLabs/fuels-ts/pull/224#discussion_r853256590

**Comment by Dhaiwat10** [comment]
Can pick this one up! @luizstacio

**Comment by arboleya** [comment]
@Dhaiwat10 I think this touches on a slightly deeper aspect: our `env` files should expose `async` functions and not only static variables, making it possible to evaluate async values. Although most things are static, some must be fetched from elsewhere (like nodes). IIRC, one of those things is the **_gas fee_**.

This point was brought to my attention by @LuizAsFight last week, and even though I'm unaware of all implementations, I'm sure of the repercussions of it: A LOT of heavy refactoring.

Adding async elements on a codebase that wasn't prepared for it will require adding a lot of async/await directives everywhere and, ideally, standardizing everything that reads from env in an async block initialization.

You may focus on organizing things statically as a first step, which is good enough. But after reviewing the current implementations, could you please create a new issue to make this `sync->async` change repo-wide?

I presume you'll have a broader view of it by then.

**Comment by arboleya** [comment]
Oh, my bad. The issue already exists:
 - https://github.com/FuelLabs/fuels-ts/issues/784

**Comment by arboleya** [comment]
I want to touch on one final detail, which is how this issue might move on:

 1. Concentrating all constants for all packages in a single place _(`packages/constants`)_
 2. Having individual `env.ts` files for each package _(or similar)_

The first approach is more suitable for _apps_, IMO.

So I'd vote for the **_second_** one, as it feels more detached and intuitive<sup>(1)</sup>.

The `constants` package could also be deleted if we go with individual files.

> <sup>(1)</sup> _Take [this PR](https://github.com/FuelLabs/fuels-ts/pull/814/files#diff-94f9cfab511e2a324b4d2e32c178029c205ddc83c32d462bfccf7edfd8e4d4b7R26) for example, it feels natural that the `MNEMONIC_SIZES` constant would live close to the `mnemonic` implementation, whereas if we'd move it to a distant package it could create unnecessary roundtrips_.

**Comment by arboleya** [comment]
Pseudocode to illustrate an idea.

```ts
// packages/*/src/env.ts

export const getEnv = async (params: {
  source: Record<string, string),
  provider: Provider,
}) => {

  const { source, provider } = params

  return {
    NODE_ENV: source.NODE_ENV,                     // env data
    MY_STATIC_VALUE: 123,                          // static data
    MY_ASYNC_VALUE: await fetchFromNode(provider), // remote data
  }

}


// consumer.ts

const doSomething = async () => {

  const env = await getEnv({
    source: proces.env,
    provider: new Provider("..."),
  })

  console.log({ env })

}
```

**Comment by Dhaiwat10** [comment]
@arboleya After looking at the example PR that you linked, I'm also leaning more towards having individual files instead of having a single `constants` package for the whole repo.

**Comment by Torres-ssf** [comment]
I also believe the second approach is the way to go.
