### ISSUE TITLE
contract call not considering `txParams`

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2257]
### What version of fuels-ts are you using?

0.84.0

### Steps to Reproduce

![image](https://github.com/FuelLabs/fuels-ts/assets/8636507/390e8da7-ec41-4375-992d-2c4825efa011)

execute a contract function and try to inform `txParams`

### Expected Behavior

SDK should respect the value that user sends

### Actual Behavior

`gasLimit` and `maxFee` are calculated and set no matter what you pass

**Comment by arboleya** [comment]
Possible duplicate of https://github.com/FuelLabs/fuels-ts/issues/2243.
