### ISSUE TITLE
Dependabot workflows permissions

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2260]
Dependabot workflows appear to run in a less privileged state (with [read only permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)). 

This is causing issues where the coverage report can't be [posted](https://github.com/FuelLabs/fuels-ts/actions/runs/8983190744/job/24688699112?pr=2253#step:11:15).

## Dependabot permissions
<img width="300" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/16990131/beb00d5f-331b-4eb9-9a6a-2af4e8b78772">

[source](https://github.com/FuelLabs/fuels-ts/actions/runs/8983190744/job/24688699112?pr=2253#step:1:16)

## Standard CI permissions
<img width="300" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/16990131/ca4395d4-93b1-487a-8f2c-aa06f937293d">

[source](https://github.com/FuelLabs/fuels-ts/actions/runs/8997548184/job/24716376098?pr=2166#step:1:16)

_Originally posted by @petertonysmith94 in https://github.com/FuelLabs/fuels-ts/issues/2259#issuecomment-2099975413_

**Comment by maschad** [comment]
This also affects our ability to create the changesets for the dependabot PRs as well

**Comment by arboleya** [comment]
@maschad @petertonysmith94 Do we know what the solution is here? There may be settings I could configure in the repo.

As I mentioned in the last sync, we must address all those dependabot PRs to clear the clutter.

**Comment by maschad** [comment]
@arboleya let's pair on this to resolve it.

**Comment by maschad** [comment]
@petertonysmith94 the dependabot PRs don't need to report coverage tbh, so we may not need to add permissions, let's just disable that step for dependabot PRs

**Comment by maschad** [comment]
> @maschad does it not require the permissions for the [create-changeset](https://github.com/FuelLabs/fuels-ts/pull/2295/files#diff-245392b692a50c38ecab4381b118862db514035c10983f3bd4f4b7f1f4be4692R185) job?

That job is completed by the Github bot and so it shouldn't to the best of my knowledge, but otherwise yes we would need to add it to the [secret as you suggested](https://github.com/FuelLabs/fuels-ts/issues/2260#issuecomment-2102638722)
