### ISSUE TITLE
Improve node incompatibility warnings

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2283]
> [!NOTE]
> Incoming from the forum:
> - https://forum.fuel.network/t/fuels-typescript-sdk-error/5266

---

We do have [checks in place](https://github.com/FuelLabs/fuels-ts/blob/fb972e31debf4f94da02d6dc6a5efc36b7e80aa9/packages/account/src/providers/provider.ts#L479-L492), but we call [fetchChain](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/provider.ts#L468) before the check occur.

A possible solution would be to make an additional request only for the node's version before the rest.

It requires some consideration. Also, we'd need to cache this result to avoid unnecessary requests.

**Comment by nedsalk** [comment]
I'm not sure if it makes sense anymore to do this now that `fuel-core` releases are backwards compatible and errors such as the one reported in the linked forum post shouldn't be happening anymore. This would mean an additional request towards the network whenever a `Provider.create` call is done for the first time and I don't think it's worth it. @FuelLabs/sdk-ts

**Comment by arboleya** [comment]
Makes sense — priority decreased.

**Comment by arboleya** [comment]
We should keep it because things like the [graphql] API can change and [break stuff](https://github.com/FuelLabs/fuels-ts/pull/2717#discussion_r1667374284). 

Better have a warning to be safe.
