### ISSUE TITLE
Add a internal logger for debugging

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2298]
### Motivation

When completing the [`Utf8ToString` implementation](https://github.com/FuelLabs/fuels-ts/pull/2297/files#diff-f75cdafd4b7c1effacb9a274350a1116bd4ad166848a80bd11482ba89b2d0bf3R55) I realize we don't log some warnings.

We have [deprecated  `@ethersproject/logger`](https://github.com/FuelLabs/fuels-ts/pull/1153) but it may still be useful to log some  potential inconsistencies as warnings, debug or info logs. 

### Usage example

```typescript

	import  { logger } from '@fuel-ts/logger'

	function warnUser( 
	  reason: string,
	  offset: number,
	  bytes: Uint8Array,
	) {
	
		logger.warn(`invalid codepoint at offset ${offset}; ${reason}, bytes: ${bytes}`);
		return offset
	}

	// Maximum code point
	if (res > 0x10ffff) {
      	i += warnUser('OUT_OF_RANGE', i - 1 - extraLength, bytes, result, res);
      	continue;
    }
```

### Possible implementations

We could create a simple custom logger on top of a tool like [debug](https://www.npmjs.com/package/debug)

Related: https://github.com/FuelLabs/fuels-ts/issues/1360

**Comment by arboleya** [comment]
While I understand the motivation behind something more robust with multi-level logging (log, info, warn, etc.) I usually lean more towards simplicity, a territory where `debug` shines.

I don't have a hard opinion on this, but having a first proposal and execution plan could be good here to gather people's opinions before spending too much time on such a thing, as it can be time-consuming to apply across the whole codebase.

cc @Dhaiwat10 - since you mentioned this wrt to the `fuels` CLI.

**Comment by maschad** [comment]
Right @arboleya so I my initial proposal is just create a logger package e.g. `@fuel-ts/logger`  which would just have an interface  which would

```typescript
export interface Logger {
  (formatter: any, ...args: any[]): void
  error(formatter: any, ...args: any[]): void
  warn(formatter: any, ...args: any[]): void
  info(formatter: any, ...args: any[]): void
  enabled: boolean
}
```

and this would have some default methods to create a logger per package e.g.:

```typescript
/**
 * Creates a logger for the passed package name.
 *
 * @example
 *
 * ```TypeScript
 * import { logger } from '@fuel-ts/logger'
 *
 * const log = logger('account')
 * log.info('hello world')
 * // logs "account: hello world"
 * ```
 */
export function logger (name: string): Logger {
  // trace logging is a no-op by default
  let trace: debug.Debugger = createDisabledLogger(`${name}:trace`)

  // look at all the debug names and see if trace logging has explicitly been enabled
  if (debug.enabled(`${name}:trace`) && debug.names.map(r => r.toString()).find(n => n.includes(':info')) != null) {
    info = debug(`${name}:info`)
  }

  return Object.assign(debug(name), {
    error: debug(`${name}:error`),
    trace
  })
}
```

We could also have some useful default methods such as a wallet logger

```typescript
/**
 * Create a component logger that will prefix any log messages with a truncated
 * wallet address.
 *
 * @example
 *
 * ```TypeScript
 * import { walletLogger } from '@fuel-ts/logger'
 * import {HDWallet} from 'fuels'
 *
 * const hdwallet = HDWallet.fromSeed('seed')
 * const logger = walletLogger(hdwallet)
 *
 * const log = logger.forComponent('account')
 * log.info('hello world')
 * // logs "0x…21243:account hello world"
 * ```
 */
export function walletLogger (HDWallet: wallet, options: Partial<WalletLoggerOptions> = {}): ComponentLogger {
  return prefixLogger(truncateWalletAddress(wallet, options))
}
```
and one per fuel node for instance.
```typescript
/**
 * Create a component logger that will prefix any log messages with the passed
 * string.
 *
 * @example
 *
 * ```TypeScript
 * import { prefixLogger } from '@fuel-ts/logger'
 *
 * const logger = prefixLogger('my-fuel-node')
 *
 * const log = logger.forComponent('account')
 * log.info('hello world')
 * // logs "my-fuel-node:account hello world"
 * ```
 */
export function prefixLogger (prefix: string): ComponentLogger {
  return {
    forComponent (name: string) {
      return logger(`${prefix}:${name}`)
    }
  }
}
```

**Comment by danielbate** [comment]
In the interest of reducing rather than increasing packages, could this go inside `utils` re #1517?

**Comment by maschad** [comment]
> Out of curiosity, how did you envision the formatter field being used?

The formatter would be useful for displaying different types of debug info - for instance `%b` could be for displaying a `b256` address, this is because generally you don't want to add extra compute to debug logs _by default_ so essentially that formatting / conversion would only be done when logs are enabled (which would not be the case in prod of course).

> In the interest of reducing rather than increasing packages, could this go inside utils re https://github.com/FuelLabs/fuels-ts/discussions/1517?

I am open to that, my preference on having this as a separate package is that it decouples it from other utilities, I generally find that `utils` directories lend themselves to bloat as they tend to be too ambiguous.
