### ISSUE TITLE
Using node test version 20.10.0 causes CI to hang

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2307]
[Changed](https://github.com/FuelLabs/fuels-ts/pull/2294/commits/69a1344687e1816c718f58c934104a47ba5357a3) the the CI node environment from version `20` to `20.10.0` (to align with the wider workspace).

This resulted in `vitest` hanging with the following [error](https://github.com/FuelLabs/fuels-ts/actions/runs/9086125898/job/24984464781#step:10:1277):
```console
Failed to terminate worker while running /home/runner/work/fuels-ts/fuels-ts/apps/docs-snippets/src/guide/types/raw-slice.test.ts. 
See https://vitest.dev/guide/common-errors.html#failed-to-terminate-worker for troubleshooting.
Tests closed successfully but something prevents Vite server from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```

**Comment by arboleya** [comment]
Is this still happening?
