### ISSUE TITLE
Thorough example for Predicates

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2311]
Our documentation lacks a thorough example for predicates (as stated from a [forum post](https://forum.fuel.network/t/is-there-any-complete-client-side-integration-example-of-predicates-using-fuels-ts-sdk/5301/1)).

> Is there any complete client side integration example of predicates using Fuels TS-SDK?

**Comment by arboleya** [comment]
@maschad This may be a good one to start digging into predicates.

**Comment by danielbate** [comment]
One idea could be to add to [next-steps](https://docs.fuel.network/docs/fuels-ts/creating-a-fuel-dapp/#next-steps) with how to extend the "Creating a Fuel dApp" docs to both predicates and scripts. So we are not duplicating efforts to much and it should flow quite nicely.

**Comment by arboleya** [comment]
Sure, but let's also consider making the docs around `Predicates` more complete in isolation, as we have for `Contract`.

For instance, if I had a `Predicate` question, I'd usually search for the `Predicate` section in the docs.

The `create fuels` can also cross-link to other parts, as it'll be more of an "all-in-one" thing.

**Comment by maschad** [comment]
I think @danielbate idea about next steps would directly address this issue. @arboleya the only addition I could see necessary for predicates relative to completeness would be a description of the various methods, which [I've added](https://github.com/FuelLabs/fuels-ts/pull/2345/files#diff-8f528b24de2456d5421a8cd534e5d9d63d73c009665a62461f5c9565aa6b72ea) in #2345
