### ISSUE TITLE
Fix flaky `TransactionResponse` test

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2318]
https://github.com/FuelLabs/fuels-ts/actions/runs/9112255896/job/25051134389?pr=2291#step:5:709

![image](https://github.com/FuelLabs/fuels-ts/assets/17943891/d964b17f-1ab8-4f11-b031-5acb03ac6988)

We're currently skipping this test as it's failing across the board and breaking our workflows.

**Comment by arboleya** [comment]
@nedsalk Should this go in https://github.com/FuelLabs/fuels-ts/issues/1755 instead?

**Comment by nedsalk** [comment]
@arboleya it can be put there, I guess. I put it separately because I wanted to track it in isolation.

**Comment by arboleya** [comment]
Is this a duplicate of the below? cc @maschad 
 - https://github.com/FuelLabs/fuels-ts/issues/2200

**Comment by maschad** [comment]
Looks so @arboleya I think the original issue got closed by https://github.com/FuelLabs/fuels-ts/pull/2268 but it has resurfaced and thus #2200 was re-opened. Closing this as a duplicate.
