### ISSUE TITLE
Update contributing guide

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2326]
Update contributing guide on how to work with unreleased `forc` and `fuel-core` functionality.

One needs to edit either file:
 - `packages/forc/VERSION`
 - `packages/fuel-core/VERSION`

And instead of a version number like `0.59.0`, use the desired branch:

```
git:some/branch-name
```

Then `pnpm install` and `pnpm build` all again.

**Comment by arboleya** [comment]
Another thing we could be documenting is how to turn e2es for devnet on and off. cc @danielbate
