### ISSUE TITLE
Implement Transaction Queue Support

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2361]
The TS SDK should support queuing of transactions. This feature would allow developers to queue multiple transactions and ensure they are executed sequentially. For example, once transaction X is completed, transaction X+1 should automatically start, and so on. (i.e. once X tx is done, do X + 1, etc).

This feature is particularly useful in scenarios where a series of dependent transactions need to be processed in a specific order. It simplifies the workflow for developers who otherwise would have to manually handle the sequencing and execution of transactions.

> Extracted from: https://github.com/FuelLabs/fuels-ts/issues/161

**Comment by nedsalk** [comment]
Would this cover using the outputs of one transaction as inputs for the next?

**Comment by Torres-ssf** [comment]
@nedsalk I believe it would, but the funding of transaction X + 1 should happen after transaction X is processed (In case X + 1 needs to use UTXOs created by X). 

Since this approach is designed to wait for X to be processed in order to submit X + 1, any output produced from X (UTXOs or even a deployed contract) will be usable on X + 1.

**Comment by maschad** [comment]
I think we need should consider the various scenarios that could arise by introducing a queue as this is more complex than stated in the issue. I've [opened a discussion](https://github.com/FuelLabs/fuels-ts/discussions/2678) to address this, we can then re-adjust the issue based on the outcome of that discussion.

**Comment by danielbate** [comment]
Closing for now so all comms can move to #2678, we can reopen this should we have a resolution from that discussion.
