### ISSUE TITLE
Proposal to Simplify `Provider.getTransactionCost`

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2362]
We should consider refactoring [Provider.getTransactionCost](https://github.com/FuelLabs/fuels-ts/blob/7c08593037e65ce6256c6cc63a8d0a2fe2f6c0b8/packages/account/src/providers/provider.ts#L1064) by removing the responsibility of adding fake funds to the `TransactionRequest` before the dry-run to get the `gasUsed`. 

This change will delegate this task to the caller of `getTransactionCost`, therefore reducing unnecessary parameter flags.

The current implementation of `getTransactionCost` handles multiple tasks, including adding fake funds for transaction requests. 

By offloading the fake fund's addition to the caller, we can eliminate the need for specific parameter flags associated with the funding step:

1. [resourcesOwner](https://github.com/FuelLabs/fuels-ts/blob/7c08593037e65ce6256c6cc63a8d0a2fe2f6c0b8/packages/account/src/providers/provider.ts#L1066): Represents the `Account` instance that owns the fake resources and it is also used to validate if it is a predicate, which is required for populating the `predicate` and `predicateData` for the fake resources.
2. [quantitiesToContract](https://github.com/FuelLabs/fuels-ts/blob/7c08593037e65ce6256c6cc63a8d0a2fe2f6c0b8/packages/account/src/providers/provider.ts#L1066): This includes the `amount` and `assetId` of a coin that could be forwarded to a contract.

**Comment by mvares** [comment]
hey @petertonysmith94, is this issue still on your radar? 🦅
