### ISSUE TITLE
Unpublish NPM versions

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2377]
### Summary

Work was carried out to improve the functionality around unpublishing package versions (https://github.com/FuelLabs/fuels-ts/pull/2495):

- Allow the passing of a particular version.
- Show a more appropriate message on dry runs.

Due to issues with our package hierarchy (outlined [here](https://github.com/FuelLabs/fuels-ts/issues/2377#issuecomment-2176002303)), we couldn't unpublish these versions automatically. Once we have migrated to a single `fuels` package (https://github.com/FuelLabs/fuels-ts/issues/2493), we should revisit this functionality to see if unpublishing is possible.

After we can confirm this functionality, we should [contact support](https://docs.npmjs.com/policies/unpublish#issues) to clean up old NPM versions that are more than 72 hours old.

---

- Blocked by https://github.com/FuelLabs/fuels-ts/issues/2493
- Related to #2119

**Comment by arboleya** [comment]
Yes, let's do that and stop publishing PRs automatically.

When we merge a PR to `master`, we publish an update to the `next` tag.

We could move our `npm installs fuels@next` checks to happen at this point.

This way, we can stop publishing PRs while keeping the validation.

**Comment by arboleya** [comment]
Considering the CDN thing was addressed, should we close this?

**Comment by petertonysmith94** [comment]
@arboleya I think given the constraints that NPM has, we won't be able to unpublished until https://github.com/FuelLabs/fuels-ts/issues/2493 is concluded. For that reason, I'll close this until we have that resolved, then can could potentially revisit this.
