### ISSUE TITLE
CDNJS not updating to our latest version

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2385]
### Summary

We currently have `fuels` in [CDNJS](https://cdnjs.com/libraries/fuels) which is lagging being our actual version (see [investigation](https://github.com/FuelLabs/fuels-ts/issues/2385#issuecomment-2182767421)).

As we publish preview versions to NPM, CDNJS struggles to keep up with the backlog of versions. The proposed solution is to switch over to autoupdate from GItHub release assets.

## Solution

- Upload our distribution to GitHub releases assets.
- Once released, alter CDNJS package to autoupdate from [GitHub](https://cdnjs.com/api), rather than NPM.
  - https://github.com/cdnjs/packages/blob/master/packages/f/fuels.json

**Comment by Torres-ssf** [comment]
@petertonysmith94  It seems the problem is happening because their last [update sync](https://github.com/cdnjs/cdnjs/blob/master/last-sync) happened on May 14:
<img width="258" alt="Screenshot 2024-05-27 at 12 53 57" src="https://github.com/FuelLabs/fuels-ts/assets/30977845/c1fbe875-8dca-4c11-b8a3-3635de1992c1">

`0.86.0` got released on the same date: 
<img width="793" alt="Screenshot 2024-05-27 at 12 53 15" src="https://github.com/FuelLabs/fuels-ts/assets/30977845/96bc1e33-2c92-44c1-ae4b-4942e934359e">


So I reckon their update/sync happened just before our release.

**Comment by Torres-ssf** [comment]
> @Torres-ssf the history for the last sync looks off to me, it appears to occur multiple times daily and then just [stop](https://github.com/cdnjs/cdnjs/commits/master/last-sync?before=1ddef8c2406cabfdf55e2c43120b6bf464f1f698+35).
> 
> It appears the `sync` their end is [failing](https://github.com/cdnjs/cdnjs/actions/workflows/sync.yml).
> 
> It also appears that it's now onto [`0.87.0`](https://github.com/cdnjs/logs/commits/prod/packages/f/fuels).

@petertonysmith94 You're right. This sync timestamp appears unrelated to their updates.

But the fact that they have just released `0.87.0` is an indication that the problem is not on our side.

**Comment by Torres-ssf** [comment]
> I have a hunch that this issue will be alleviated once we disable publishing on every E2E test (#2489).

@petertonysmith94 How come?

**Comment by arboleya** [comment]
Sounds like a plan.

**Comment by petertonysmith94** [comment]
Found an undocumented `ignoreVersions` argument with the `autoupdate` feature (will add this to our CDNJS config):

- https://github.com/cdnjs/packages/blob/3b586a540b9689bae47547236ba3e4da9ffbc8f2/packages/r/react.json#L36

Planning on rolling this out with the following:
- https://github.com/FuelLabs/fuels-ts/issues/1728

Two birds one stone :)

**Comment by arboleya** [comment]
Awesome!

**Comment by petertonysmith94** [comment]
Blocked until release of:
- https://github.com/FuelLabs/fuels-ts/pull/2762

Then:
- Make to changes CDNJS configuration file ([fuels.json](https://github.com/cdnjs/packages/blob/master/packages/f/fuels.json)):
  ```json
  {
    ...,
    "autoupdate": {
      "source": "npm",
      "target": "fuels",
      "fileMap": [
        {
          "basePath": "dist",
          "files": ["browser.mjs", "browser.min.mjs"]
        }
      ],
      "ignoreVersions": [
        "0.0.0-*"
      ]
    },
    ...,
  }
  ```
  (Add minified bundle (`browser.min.mjs`) and `ignoreVersions`)

**Comment by petertonysmith94** [comment]
PR is in review
- https://github.com/cdnjs/packages/pull/1852

**Comment by petertonysmith94** [comment]
Will make this as complete as CDNJS configuration has now been merged:
- https://github.com/cdnjs/packages/pull/1852
