### ISSUE TITLE
Update `create-fuels` dApp to be denominated in ETH

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2388]
Right now the example [create fuels dApp](https://docs.fuel.network/docs/fuels-ts/creating-a-fuel-dapp/#creating-a-fuel-dapp) is denominated in the base asset denomination of the devnet, this creates friction in the UX because users have to add what may seem like an exorbitant amount to conduct basic transactions 
![Screenshot 2024-05-27 at 1 09 27 PM](https://github.com/FuelLabs/fuels-ts/assets/9755286/81f6a3ca-d1da-4ea3-950e-9e72808e27dd)

**Comment by Dhaiwat10** [comment]
Do you think we might wanna use ETH instead of gwei instead?
