### ISSUE TITLE
Review build error on `demo-wallet-sdk-react`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2397]
Getting this when trying to `pnpm build` on `master`, using a fresh clone:

<img width="1818" alt="build-error" src="https://github.com/FuelLabs/fuels-ts/assets/26660/175e68db-6cb4-4a76-b2e3-81907e6a0ef3">

**Comment by msensys** [comment]
That is likely because the code is being executed on the server-side. (**PS:** Due to this, the window variable isn't available)

Perhaps we can get a look at `Fuel Connector` code and send a PR to fix this bug.
