### ISSUE TITLE
Exceeding Maximum Number of Inputs When Funding a Transaction

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2420]
In a similar situation to [issue #2419](https://github.com/FuelLabs/fuels-ts/issues/2419), when funding a transaction in the [fund](https://github.com/FuelLabs/fuels-ts/blob/eb4d531046f58c03a31162ba3532cc7fc058c5e7/packages/account/src/account.ts#L264) method, we do not validate whether the number of inputs exceeds the maximum allowed for a transaction.

Action Required:

- Add validation to ensure the number of inputs does not exceed the maximum limit.
- Ensure an appropriate error is thrown if the limit is exceeded.

**Comment by mgrithm** [comment]
hi @Torres-ssf 

The maximum allowed for a transaction is the [maxFee](https://github.com/FuelLabs/fuels-ts/blob/eb4d531046f58c03a31162ba3532cc7fc058c5e7/packages/account/src/account.ts#L267)?

**Comment by Torres-ssf** [comment]
@mgrithm When calculated properly, the `maxFee` is the fee value charged when processing the transaction.

This issue is related to not exceeding the limit of inputs allowed within a transaction. This value is set within the [chain config](https://github.com/FuelLabs/fuels-ts/blob/889789c56636f34f4e1c1e400db5fe77a3926353/.fuel-core/configs/chainConfig.json#L7)

**Comment by mgrithm** [comment]
Now I understood it. Thanks
