### ISSUE TITLE
Seek better tooling integration by using `fuel-toolchain.toml`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2425]
It is possible to define a `fuel-toolchain.toml` file at the root of a project to use a specific `forc` and `fuel-core` version for that project and `fuelup` will pick it up and use it instead of the currently active global toolchain. Defining this file in our repo would make our internal `forc` and `fuel-core` packages obsolete and we could remove them altogether.

**Comment by arboleya** [comment]
I don't believe we can eliminate the internal packages, as they act as a backbone for development.

But if we can better integrate all the tools, we should.
