### ISSUE TITLE
Use `fuel-toolchain.toml` in our templates

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2426]
It is possible to define a `fuel-toolchain.toml` file at the root of a project to use a specific `forc` and `fuel-core` version for that project and `fuelup` will pick it up and use it instead of the currently active global toolchain. We can add this file in our `pnpm create fuels` templates and have it match the version supported by `fuels`.

**Comment by arboleya** [comment]
We should consider applying this approach only to the template dApp generated by `create fuels` but not to our internal tests and CI — for these, we should continue using our internal `forc` and `fuel-core` packages, which provide working with non-published versions and git branches.

**Comment by danielbate** [comment]
Going to pick this up as I've been working with create fuels templates this past week, would be helpful
