### ISSUE TITLE
Problem with a test of account

### ISSUE THREAD

**Issue by mgrithm** [FuelLabs/fuels-ts#2439]
### Steps to Reproduce

Run `pnpm test:filter packages/account/src/account.test.ts` on terminal

### Expected Behavior

pass all tests.

### Actual Behavior

![image](https://github.com/FuelLabs/fuels-ts/assets/88039515/1c656169-4e29-459d-abb5-e3b84df386ae)

I followed all the steps contained in `CONTRIBUTING.MD`, but another test failed

**Comment by mgrithm** [comment]
I ran all these commands, but it still didn't resolve

**Comment by mgrithm** [comment]
Additionally, when I run the test for `packages/account`, it throws a problem

![image](https://github.com/FuelLabs/fuels-ts/assets/88039515/6ee437ce-37d9-46c2-87c9-8e3e93505e05)

**Comment by maschad** [comment]
@mgrithm are you running the latest master? could you run [`node:clean`](https://github.com/FuelLabs/fuels-ts/blob/master/package.json#L48) command then run 

```
pnpm node:run
```

and then in a separate terminal re-run `pnpm test:filter packages/account/src/account.test.ts`

If there are still issues then you can push your changes to a draft PR and we can review them there.

**Comment by mgrithm** [comment]
Thank you @maschad. Now it's working!
