### ISSUE TITLE
Deploying a contract doesn't work with the metamask connector

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-ts#2443]
### What version of fuels-ts are you using?

0.89.1

### Steps to Reproduce

I'm using `@fuels/connectors` 0.5.0.  I have a repro [here](https://github.com/matt-user/metamask_connector_repro).  To run the repro, pnpm install, pnpm start, pnpm fuels:node, click connect, click deploy.

### Expected Behavior

The contract should deploy.

### Actual Behavior

The contract does not deploy and throws the error 
![Screenshot 2024-06-04 at 10 55 08 AM](https://github.com/FuelLabs/fuels-ts/assets/54373384/53e66f56-1077-459e-a395-0774ea8db1bf)

**Comment by Torres-ssf** [comment]
After some investigation, I could identify that the problem happens on the [[fuel-connectors](https://github.com/FuelLabs/fuel-connectors)](https://github.com/FuelLabs/fuel-connectors) side.

Therefore, I am closing this in favor of https://github.com/FuelLabs/fuel-connectors/issues/111
