### ISSUE TITLE
Pagination to `Account` methods

### ISSUE THREAD

**Issue by molives** [FuelLabs/fuels-ts#2446]
Each method provides only an `array` containing their items as a result (e.g., [coins](https://github.com/FuelLabs/fuels-ts/blob/889789c56636f34f4e1c1e400db5fe77a3926353/packages/account/src/account.ts#L148), [messages](https://github.com/FuelLabs/fuels-ts/blob/889789c56636f34f4e1c1e400db5fe77a3926353/packages/account/src/account.ts#L182), and [balances](https://github.com/FuelLabs/fuels-ts/blob/889789c56636f34f4e1c1e400db5fe77a3926353/packages/account/src/account.ts#L228)), and there are some comments in the code marked with`to do` proposing pagination for the results of these methods. My proposal is:

```ts
[{
  page: 1,
  coins: [{ ... }]
},
{
  page: 2,
  coins: [{ ... }] 
}]
```

Using the example above, too we could apply it to the other methods. Furthermore, maybe creating a reusable helper function would be helpful.

**Comment by arboleya** [comment]
Closing as duplicate of:
 - https://github.com/FuelLabs/fuels-ts/issues/302
