### ISSUE TITLE
`txSummary` not returning contract call operation in some cases

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2448]
### What version of fuels-ts are you using?

0.88.1

### Steps to Reproduce

- use the latest [fuel-wallet](https://wallet.fuel.network/docs/install/)
- access [connectors demo](https://connectors.fuel.network/) and connect your wallet
- click on `increment` button
- you will see this screen
<img width="352" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/8636507/085f0ef7-de04-4723-9998-8b39a78e5dfe">

### More details

The screen above tries to show the operations of the transaction for the user to check and confirm it. It's currently showing no operations.

Behind the scenes it's consuming  [`getTransactionSummary`](https://github.com/FuelLabs/fuels-ts/blob/7dfac30d3d12eb71bd59cf233f4959916b76298f/packages/account/src/providers/transaction-summary/get-transaction-summary.ts#L26C23-L26C44).
When this method tries to compute the [contract call operations](https://github.com/FuelLabs/fuels-ts/blob/7dfac30d3d12eb71bd59cf233f4959916b76298f/packages/account/src/providers/transaction-summary/operations.ts#L235), it tries to identify who called the contract [using the assetId](https://github.com/FuelLabs/fuels-ts/blob/7dfac30d3d12eb71bd59cf233f4959916b76298f/packages/account/src/providers/transaction-summary/operations.ts#L255) returned from the receipt.

The problem is that the receipt returns `0x0000...`, as there was no assetId in the contract call made. The previous code was working only because the baseAssetId was the same, and the input would have the correct assetId.

### Solution
When the receipt returns `assetId: 0x0000...`, consider getting the input that has the current `baseAssetId`, meaning that who payed the fee will be identified as the contract caller.

### fuel-core https://github.com/FuelLabs/fuel-core/issues/1941
I think this is something that could be changed in the VM, it could return `null` instead of `0x0000...`, but it doesn't change the solution above

**Comment by maschad** [comment]
I think the more permanent fix for this should involve `fuel-core` determining what the correct response is based on https://github.com/FuelLabs/fuel-core/issues/1941

In the interim we have released a [patch](https://github.com/FuelLabs/fuels-ts/pull/2479#issuecomment-2155160152) which solves this.

**Comment by LuizAsFight** [comment]
@maschad 
makes sense to close this issue? the bug in this issue is fixed.

the change on VM may or may not happen haha, can it be tracked in another issue as an `improvement` instead of a `bug` ? 

cc @arboleya

**Comment by maschad** [comment]
I agree @LuizAsFight this particular issue closed since both 
- https://github.com/FuelLabs/fuels-ts/issues/2530 
- https://github.com/FuelLabs/fuels-ts/issues/2449

have been created to address this on our end going forward, if https://github.com/FuelLabs/fuel-core/issues/1941 gets integrated  on `fuel-core` then we can create another issue to make accommodations for that.
