### ISSUE TITLE
CallReceipt is returning wrong `from` property

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2449]
### Motivation

Contract Call receipts are getting a [from property](https://github.com/FuelLabs/fuels-ts/blob/7dfac30d3d12eb71bd59cf233f4959916b76298f/packages/account/src/providers/utils/receipts.ts#L76)
I think `from` is not correct for this receipt. It should be `id` like in other `case` inside that same `switch`, or it should be removed.

reasons according to [spec](https://docs.fuel.network/docs/specs/abi/receipts/#call-receipt) :
1- shows `Call` contracts prop already have a `from` prop
2- there is no `contractId` and no `id` in `CallReceipt`, which means the `from` being provided by this method will be always `0x0000...`

### UPDATE

To fix this, we need to ensure that the TS SDK's [receipts types](https://github.com/FuelLabs/fuels-ts/blob/master/packages/transactions/src/coders/receipt.ts) are in alignment with the [Fuel specs](https://github.com/FuelLabs/fuel-specs/blob/master/src/abi/receipts.md)

# Spec changes

* **ReceiptCall**
  *

**Comment by danielbate** [comment]
I believe #2530 and #2448 are related.

**Comment by Torres-ssf** [comment]
@LuizAsFight there is no error here.

First, we cannot rename `from` to `id` on the `CallReceipt` type as on the [specs](https://docs.fuel.network/docs/specs/abi/receipts/#call-receipt) for this receipt the property name is `from` and not `id`.

Also, the property `from` does not exist within the [raw receipt](https://github.com/FuelLabs/fuels-ts/blob/f3453b9ea669575e3cf97ee50512bc9039845e0c/packages/account/src/providers/fuel-core-schema.graphql#L1086-L1119) type returned by `fuel-core`. 

That is why its value is being extracted from `id`.

The value for `from` will be null/undefined most of the time. Just like it is said within the [specs](https://docs.fuel.network/docs/specs/abi/receipts/#call-receipt):

> from: Hexadecimal string representation of the 256-bit (32-byte) contract ID of the current context if in an internal context; null otherwise.

This property will only be defined in case of a contract that is calling another contract. When this is not the case, it will be null. That is why in most cases its value is `0x0000...`

**Comment by arboleya** [comment]
@Torres-ssf Can this be closed?

**Comment by Torres-ssf** [comment]
@arboleya I am not enterely sure.

I may have misunderstood @LuizAsFight statement, so I am waiting for his confirmation

**Comment by arboleya** [comment]
@luizasfight Gentle ping — any input here?

**Comment by LuizAsFight** [comment]
@arboleya @Torres-ssf 

the problem here is returning things different from spec.

for instace this is what the spec says about "from" field in Call receipts:
```
from: Hexadecimal string representation of the 256-bit (32-byte) contract ID of the current context if in an internal context; null otherwise.
```

and this is what the sdk returns from "from" field
```
from: hexOrZero(receipt.id || receipt.contractId),
```

problem 1: "from" returned by sdk doesn't reflect the real "from" from spec
problem 2: "from" is not returned anywhere inside of callReceipt, so users don't have access to it
problem 3: "contractId" doesn't exist on spec for Call receipt


-----

Instead of returning the above I believe the sdk should return it parsed but don't manipulate the fields, something like:
```
from: hexOrZero(receipt.from),
id: hexOrZero(receipt.id),
```

**Comment by Torres-ssf** [comment]
@LuizAsFight I am closing this as it was addressed on https://github.com/FuelLabs/fuel-specs/pull/610

**Comment by petertonysmith94** [comment]
@torres-ssf should we be closing this one? I'd of thought we'd need to sync with the specification?<br><br>For my understanding of the [spec](https://github.com/FuelLabs/fuel-specs/pull/610) PR, it now appears that we're not aligned with the specification:

* e.g. ReceiptCall in the [spec](https://github.com/FuelLabs/fuel-specs/pull/610/files#diff-6129d05df8b9455d4c13ad7fb590a53ba0dff1a3be134c8bf5803372e8f55a29L94-R94) has changed from `from` to `id` , and we still maintain this as `from` ([here](https://github.com/FuelLabs/fuels-ts/blob/84a6c1047c7f09142abbd7e7fabaae6857399365/packages/transactions/src/coders/receipt.ts#L29-L31)).

**Comment by Torres-ssf** [comment]
> @Torres-ssf should we be closing this one? I'd of thought we'd need to sync with the specification?For my understanding of the [spec](https://github.com/FuelLabs/fuel-specs/pull/610) PR, it now appears that we're not aligned with the specification:
> 
> * e.g. ReceiptCall in the [spec](https://github.com/FuelLabs/fuel-specs/pull/610/files#diff-6129d05df8b9455d4c13ad7fb590a53ba0dff1a3be134c8bf5803372e8f55a29L94-R94) has changed from `from` to `id` , and we still maintain this as `from` ([here](https://github.com/FuelLabs/fuels-ts/blob/84a6c1047c7f09142abbd7e7fabaae6857399365/packages/transactions/src/coders/receipt.ts#L29-L31)).

@petertonysmith94 You are correct
