### ISSUE TITLE
Remove `[skip ci]`  from dependabot workflow

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2454]
We should ensure that our dependabot CI jobs pass before skipping the CI in the changeset commit. We can achieve this by committing the changesets and allowing the CI to run afterwards.

**Comment by nedsalk** [comment]
This is the user info set for the changesets PR: https://github.com/luizstacio/changesets-action/blob/6a46d2c28377497e64763ba5f1faeabbd3d88c33/src/gitUtils.ts#L4
