### ISSUE TITLE
Stop silencing errors during `fuels init` command

### ISSUE THREAD

**Issue by dmihal** [FuelLabs/fuels-ts#2483]
I was starting a new TS workspace and ran `pnpm fuels init`, which kept failing to create any output.

Eventually I noticed an error was briefly flashing on my terminal before being erased. Using a screen recorder, I could see the following error was flashing:

```Error: required option '-w --workspace <path>' not specified```

First of all, [the docs](https://docs.fuel.network/docs/fuels-ts/fuels-cli/#next-step) should provide more information about the required flags.

Second, the CLI should make sure errors like this are visible to the user (without needing a screen recorder 😁).

**Comment by arboleya** [comment]
It shouldn't require a screen recorder, indeed! 😆 

The docs page you mentioned contains the URL for the `init` command docs though:

![nmext-step](https://github.com/FuelLabs/fuels-ts/assets/26660/02bd6d92-31c2-45d0-bd23-b306b32c491c)

Here it is:
 - https://docs.fuel.network/docs/fuels-ts/fuels-cli/commands/

Please let me know if you think something feels off.

**Comment by Dhaiwat10** [comment]
@arboleya To be fair, that link can look like just another code snippet and people might not click on it. They might just think that `pnpm fuels init` is gonna be all they need to run.

**Comment by arboleya** [comment]
@Dhaiwat10 Agreed. 👍
