### ISSUE TITLE
Consider merging all packages into `fuels`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2493]
The idea is to experiment with merging all `packages/*` into `packages/fuels`.

A single package should simplify the repo maintenance, build times, and feedback loop.

Also, it should make it easier to make our library fully tree-shakable and avoid bloating the final build.

 - [ ] #1751
 - [ ] #2475
 - [ ] #2476
 - [ ] #2477 
 - [ ] #2478

**Comment by arboleya** [comment]
Other points of interest:
 - Review `tsup` dependency and configs
 - Review utility of integrating with `tsc` project references ([docs](https://www.typescriptlang.org/docs/handbook/project-references.html))

**Comment by maschad** [comment]
Should we also consider merging [`abi-coder` into `abi-typegen`](https://github.com/FuelLabs/fuels-ts/issues/2346) as well?

**Comment by arboleya** [comment]
Closing EPIC — sub-issues will be resolved individually.
