### ISSUE TITLE
Add ChainID and AssetID for `mainnet`

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2509]
Before mainnet release, we must to double-check these items:

- ~[ ] Populate [`NETWORK_URL`](https://github.com/FuelLabs/fuels-ts/blob/54e16f03d93ae320cd66da6c50804e507246896c/packages/account/src/configs.ts#L5) with the mainnet URL.~
  - [ ] Instead of adding URL for mainnet, we should deprecate the other constants and later remove them.
- [ ] Add and populate the chain ID for `mainnet` in the static [`CHAIN_IDS` export](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/chains.ts#L7-L8).
- [ ] Add and populate the asset for `mainnet` for our [`assets` export](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/assets/assets.ts#L33).

**Comment by arboleya** [comment]
As @xgreenx said, IDs can be found here:
- https://github.com/FuelLabs/chain-configuration/tree/master/ignition#the-configuration-of-the-ignition-network
