### ISSUE TITLE
Use Next.js v14 resources in `create fuels` template

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2517]
Realign template and documentation with the latest of Next.js v14:
 - Using `npx create-next-app@14`, realign the template and docs to better align with the latest changes.

### Notable additions
 - As of `next@13` we had the introduction of the [app router](https://nextjs.org/docs/app).

> Incoming from the forum:
> https://forum.fuel.network/t/will-the-typescript-sdk-be-compatible-with-nextjs-14/5803

**Comment by arboleya** [comment]
Another related post - using NextJS 14:
 - https://forum.fuel.network/t/crucial-how-to-integrate-wallet-into-nextjs-v14-typescript/5809/3

**Comment by YaTut1901** [comment]
hello, I would like to take that

**Comment by YaTut1901** [comment]
hey, I created a PR, but not sure how to link it to issue: https://github.com/FuelLabs/fuels-ts/pull/2534

**Comment by YaTut1901** [comment]
hello, I closed previous PR cause it includes not intended changes for some reason. Created new one
