### ISSUE TITLE
Map `not enough coins to fit the target` error

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2522]
Errors like `not enough coins to fit the target` don't seem obvious to users:

- https://forum.fuel.network/t/fuelerror-not-enough-coins-to-fit-the-target/5818/2
- https://forum.fuel.network/t/creating-a-fuel-dapp-using-provided-example-in-docs/5796/1

We should consider mapping this one even before we get to https://github.com/FuelLabs/fuels-ts/issues/2467.

> [!NOTE]
> Should be done after:
> - https://github.com/FuelLabs/fuels-ts/issues/2521

**Comment by goheesheng** [comment]
The reason for causing this issue is because of the deployer or the provider has 0 tokens at first. Hence I think to fix it is to use `generateTestWallet`. However currently, the importation doesn't work [forum](https://forum.fuel.network/t/nodemodules-unable-to-import-generatetestwallet/5859/3).
```
import { NODE_URL } from "../../lib";
import { Provider, Wallet, WalletUnlocked, Signer } from "fuels";
import { useState } from "react";
import useAsync from "react-use/lib/useAsync";
// import { generateTestWallet } from '@fuel-ts/account/test-utils';

export const useFaucet = () => {
  const [faucetWallet, setFaucetWallet] = useState<WalletUnlocked>();

  useAsync(async () => {
    if (!faucetWallet) {
      const provider = await Provider.create(NODE_URL);
      const wallet = Wallet.fromPrivateKey("0x01", provider);
      const signer = new Signer("0x01");
      const balances: CoinQuantity[] = await wallet.getBalances();
      console.log('Local Provider address', signer)
      setFaucetWallet(wallet);
    }
  }, [faucetWallet]);

  return {
    faucetWallet,
  };
};

```

**Comment by msensys** [comment]
@arboleya, I am not sure about this, but we can only change the error message by explaining that the expected action wasn't possible due to insufficient coins.

**Comment by danielbate** [comment]
I'd like to close this in favour of #2467, I also don't think this is required for mainnet as we don't map any of the other VM errors. @FuelLabs/sdk-ts

**Comment by arboleya** [comment]
I was hoping we could squeeze this in because it's been more prevalent, but you also have a point.

Maybe we can give it another week or so and then deprioritize it in case we can't get it across the line.

**Comment by maschad** [comment]
@danielbate whilst I agree that this would be an exceptional use case in terms of mapping a VM error, the fact that other consumers have been perplexed by it suggests to me that we should consider the DX when this error is thrown. My personal opinion is that they should be directed to the faucet when this error is thrown, but that would require it to be mapped first.
