### ISSUE TITLE
Consider reviewing GH Issue templates

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2523]
The current templates are not always helpful:
https://github.com/FuelLabs/fuels-ts/tree/master/.github/ISSUE_TEMPLATE

We should consider reviewing and simplifying them.

We could use a blank page or something straightforward if time is short.

**Comment by maschad** [comment]
I certainly think for creating bugs, the current [bug template](https://github.com/FuelLabs/fuels-ts/blob/master/.github/ISSUE_TEMPLATE/bug.yaml could be amended to include [Stackblitz templates](https://github.com/FuelLabs/fuels-ts/issues/1927) so that we can have easier reproducibility
