### ISSUE TITLE
Detect the users package manager for `create fuels`

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2552]
### Summary

Detect the package manager that a user uses to bootstrap using `create fuels` and use that package manage to install the application. We can then remove the following CLI options:

- `--pnpm`
- `--npm`
- `--bun`

Relates to #2444

**Comment by mvares** [comment]
hey @petertonysmith94, what logic would you use for this? I think we would base it on `.lock` files (like yarn.lock, pnpm.lock)

**Comment by Dhaiwat10** [comment]
I highly doubt if this is possible. Even `create-next-app` doesn't do this

**Comment by petertonysmith94** [comment]
@Dhaiwat10 in that case, let's close this. Thanks for investigating!
