### ISSUE TITLE
Investigate dependabot workflow runs hanging

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2559]
When the [changesets are committed](https://github.com/FuelLabs/fuels-ts/blob/master/.github/workflows/pr-validate-changesets.yaml#L39-L47) by github bot in the dependabot workflow, https://github.com/FuelLabs/fuels-ts/pull/2488 was supposed to have addressed this as well but it seems it didn't,  the CI still hangs as can be seen in https://github.com/FuelLabs/fuels-ts/pull/2554
<img width="848" alt="Screenshot 2024-06-19 at 11 36 11 AM" src="https://github.com/FuelLabs/fuels-ts/assets/9755286/bd96c7c8-8f61-45c2-8247-97c4f6733af6">

This isn't a blocker for CI runs as once the branch is updated the workflows [re-run](https://github.com/FuelLabs/fuels-ts/pull/2528)

**Comment by arboleya** [comment]
@FuelLabs/sdk-ts Until we have this fix, we must intervene manually in these PRs so the workflows run as expected.
