### ISSUE TITLE
Upgrade `graphql-request` library to latest version

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2567]
We should consider upgrading `graphql-request` from `5.0.0` to `7.1.0`.

Due to breaking changes, this couldn't be done automatically by dependabot:
 - https://github.com/FuelLabs/fuels-ts/pull/2729

**Comment by nedsalk** [comment]
[https://github.com/FuelLabs/fuels-ts/pull/1597](https://github.com/FuelLabs/fuels-ts/pull/1597) is a related alternative which, at the time, was closed due to lack of a majority in favor of it. A revisit of it might be worthy.

**Comment by danielbate** [comment]
I've managed to upgrade 1 major version, however `v7` is ESM only meaning we'll need changes to our build tooling to support it... This could be strong case for #1597 or maybe build tooling adjustments, I'll probably have a think and open a discussion.
