### ISSUE TITLE
Move complex CI worfklow logic into scripts

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2581]
CI workflows, especially those related to changesets and release processes, have recently experienced a lot of expansion and have become rather cumbersome to read. Besides that, CI testing most of the time requires a lot of trial and error. We should move their logic to either shell or typescript scripts to make them more manageable and ideally write unit tests for existing logic and have the infrastructure ready for future logic to reduce trial and error.

> [!CAUTION]
> High caution needs to be exercised here to not break things.

**Comment by msensys** [comment]
hey @nedsalk, I suggest some additions to make these logics more understandable. Here's:

- Break this script into `separate files`
- Review the script code (Maybe we can improve it somehow)
- Create an `improvement proposal` explaining some technical decisions
