### ISSUE TITLE
Dependabot script not bumping patch versions in changesets

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2594]
If a dependency in one of our packages is bumped, the [changesets](https://github.com/FuelLabs/fuels-ts/pull/2588/files#r1650213697) should also bump the patch version of that package.

**Comment by maschad** [comment]
> Could we test for `templates/nextjs` bumping the `create-fuels` package as well :)

Just to clarify, your suggesting that if a dependency is bumped in [templates/nextjs](https://github.com/FuelLabs/fuels-ts/blob/master/templates/nextjs/package.json) then the `create-fuels` version should be bumped as well?

**Comment by nedsalk** [comment]
@maschad what is wrong with the `dependabot-changeset.sh` script? Doesn't it do what this PR suggests except for including `templates/nextjs`?
