### ISSUE TITLE
Upgrade `typedoc-plugin-markdown`  dependency

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2610]
Dependabot is unable to upgrade this https://github.com/FuelLabs/fuels-ts/actions/runs/9649869028/job/26614245232?pr=2599 so it needs to be done manually.

This dependency should be upgraded to latest version and all CI tests should pass.

**Comment by bolajahmad** [comment]
Could I take this on? I'm looking to contribute to fuel-ts and this could be a good issue to start with

**Comment by bolajahmad** [comment]
> Hey @bolajahmad 👋🏼
> 
> We welcome all contributions and would value your help. Let us know if you need any assistance 😄

Will do just that!

**Comment by aditya172926** [comment]
Hey is this issue still being worked on? 
If not, I can take it up if it's assigned to me.

**Comment by aditya172926** [comment]
> Hey @aditya172926, we're not assigning issues to external contributors unless there's a PR for it.
> 
> If you create a PR for it, please let us know.

Cool. Will let you know. 👍

**Comment by aditya172926** [comment]
@arboleya i have created a draft pr https://github.com/FuelLabs/fuels-ts/pull/2650 for this issue.

Will be adding some more commits for fixing build in the `typedoc.json` wrt different schema used in `typedoc-plugin-markdown` 4.1.0

**Comment by aditya172926** [comment]
Putting an update here for this pr.
The `typedoc_plugin_markdown` has been bumped up to the version `4.1.2`.
The dev dependencies `typedoc` and `typedoc-plugin-merge-modules` have also been updated to `0.26.3` and `6.0.0` respectively for compatibility with `typedoc_plugin_markdown`.

The updated new versions introduced changes in the structure of the modules after merging when building the docs and executing the current `typedoc-postbuild.ts` script fails.

Currently wip on updating the `typedoc-postbuild.ts` script to execute successfully.

**Comment by petertonysmith94** [comment]
> ### Update for this pr #2650 .
> The `typedoc_plugin_markdown` has been bumped up to the version `4.1.2`. The dev dependencies `typedoc` and `typedoc-plugin-merge-modules` have also been updated to `0.26.3` and `6.0.0` respectively for compatibility with `typedoc_plugin_markdown`.
> 
> The updated new versions introduced changes in the structure of the modules after merging when building the docs and executing the current `typedoc-postbuild.ts` script fails.
> 
> Currently wip on updating the `typedoc-postbuild.ts` script to execute successfully.

Wonderful - thanks you @aditya172926! ❤️ 

If you need any assistance then let us know.
