### ISSUE TITLE
Browser tests are inconsistently failing due to dynamic `istanbul` import

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2612]
There are a few PRs currently [failing on CI](https://github.com/FuelLabs/fuels-ts/actions/runs/9649866949/job/26614887599?pr=2602#step:5:113) due to the failure to dynamically fetch [istanbul](https://github.com/gotwarlost/istanbul) for code coverage. This doesn't happen consistently though.

Here are a few affected PRs:

- https://github.com/FuelLabs/fuels-ts/pull/2600
- https://github.com/FuelLabs/fuels-ts/pull/2601
- https://github.com/FuelLabs/fuels-ts/pull/2602
- https://github.com/FuelLabs/fuels-ts/pull/2608

**Comment by arboleya** [comment]
Bumping priority to `p0` as it seems to affect everything else. cc @nedsalk

**Comment by maschad** [comment]
I see that some of the CI jobs are [now passing](https://github.com/FuelLabs/fuels-ts/actions/runs/9649868095/job/26615921126?pr=2600) upon re-running the jobs, so the PRs in my description may become outdated.
