### ISSUE TITLE
Consider deprecating `FUEL_NETWORK_URL` and `LOCAL_NETWORK_URL`

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2644]
After we migrate to `launchTestNode`, we should be in a position to deprecate the following constants:
- [`FUEL_NETWORK_URL`](https://github.com/FuelLabs/fuels-ts/blob/b17ff622680aef2f69ab77fd0a2bc1d016ad28a2/packages/account/src/configs.ts#L7)
- [`LOCAL_NETWORK_URL`](https://github.com/FuelLabs/fuels-ts/blob/b17ff622680aef2f69ab77fd0a2bc1d016ad28a2/packages/account/src/configs.ts#L1)

This would leave us with the following:

- `DEVNET_NETWORK_URL`
- `TESTNET_NETWORK_URL`
- `NETWORK_URL` — upcoming `mainnet`

[Discussion Context](https://github.com/FuelLabs/fuels-ts/discussions/2510)

**Comment by arboleya** [comment]
@FuelLabs/sdk-ts Thoughts on this one?

**Comment by maschad** [comment]
Given that #1820 has been updated to limit `launchTestNode` integration to strictly the `fuel-gauge` suite, we need to integrate `launchTestNode` in a few other packages before those urls can be deprecated. I've created https://github.com/FuelLabs/fuels-ts/issues/2698 to address that.  Once that is resolved then yes I would agree both [`FUEL_NETWORK_URL`](https://github.com/FuelLabs/fuels-ts/blob/b17ff622680aef2f69ab77fd0a2bc1d016ad28a2/packages/account/src/configs.ts#L7) and [`LOCAL_NETWORK_URL`](https://github.com/FuelLabs/fuels-ts/blob/b17ff622680aef2f69ab77fd0a2bc1d016ad28a2/packages/account/src/configs.ts#L1) should be deprecated

**Comment by arboleya** [comment]
@petertonysmith94 Should we be doing this before release?

If yes, we need also to get #2698 in. cc @maschad

**Comment by petertonysmith94** [comment]
@arboleya it doesn't look like a big change, I think it's worthwhile. What are your thoughts?

#2811 is ready IMO - maybe we can get it in today, and get the conflicts resolved by Wednesday?

**Comment by arboleya** [comment]
Sounds like a plan. 🫡
