### ISSUE TITLE
Use Next's `Link` component

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-ts#2645]
### Motivation

The `create fuels` app template should use  next's `Link` component to avoid unnecessary refreshes.

### Possible implementations

We could just change the current `Link` component to use Next's `Link` instead of an `a` tag

**Comment by Dhaiwat10** [comment]
As discovered in #2691, there are still some places where this work needs to be done. Re-opening

**Comment by mvares** [comment]
@Dhaiwat10, as mentioned [here](https://github.com/FuelLabs/fuels-ts/pull/2691#discussion_r1670032489), can I send another PR to add Next's Link to the template?
