### ISSUE TITLE
Add `createAssetId` function

### ISSUE THREAD

**Issue by matt-user** [FuelLabs/fuels-ts#2646]
### Motivation

Creating an assetId manually is easy, but is also easy to mess up.  For new devs this function would be helpful.

### Summary

- Add new function `createAssetId`
- Add documentation for `createAssetId` in [Native Parameters -> Asset ID](https://github.com/FuelLabs/fuels-ts/blob/55998e3beb5c03dfaea51050ac90b60c69bd641d/apps/docs/src/guide/types/native-parameters.md#L64)

### Usage example

`const assetId = createAssetId(contractId, subId)`

### Possible implementations

```ts
function createAssetId(contractId: string, subId: string) {
    const contractIdBytes = arrayify(contractId);
    const subIdBytes = arrayify(subId);
    const bits = sha256(concat([contractIdBytes, subIdBytes]));
    const assetId: AssetIdInput = {
        bits
    }
    return assetId
}
```

**Comment by bolajahmad** [comment]
I agree with @Torres-ssf, there is already the `getMintedAsset` that returns pretty much the assetId and is the same function I had to use when writing the `createAssetId`. They are also located in the same file

Is there some special feature of the new `createAssetId`.
