### ISSUE TITLE
Consider adding a PR template

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2649]
By standardizing our PR templates, we can automate other routines around it.

One idea is to have all breaking changes consolidated in the release notes.

This is possible by slicing the PR description following a pre-defined template.

> Check two ideas in the comments below:
>  1. Full
>  1. Minimal

**Comment by arboleya** [comment]
Full - An amalgamation of a few PRs I've seen around lately.

----

# Issues

 - Closes #2560
 - Closes #1344

# Summary

- Upgrades `forc` to `0.61.0`
- Feature tests for `str`, coder was introduced already in `v1` based on the spec
- Fix for `str` in typegen to import the required type
- Enabled `raw_slice` in script test

# Breaking Changes

The return of the following methods was modified to support pagination:
- `getCoins` in [Provider](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/718055b2e2f9c408f660cad78401649c77985c86) and [Account](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/21364ce2c587068cba682fac250937276d6e1183).
 - `getBalances` in [Provider](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/4850e2896e76b73f24600539754351bd21db36e8) and [Account](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/4850e2896e76b73f24600539754351bd21db36e8).
 - `getMessages` in [Provider](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/638481adf32e774275a434d85719952c525ecc3a) and [Account](https://github.com/FuelLabs/fuels-ts/pull/2408/commits/f0f34111532e297fd73463dbbe394caccfb14503).


```ts
// before
abc
```

```ts
// before
xyz
```

# Checklist

 - [ ] I added tests
 - [ ] I triple-checked the docs
 - [ ] I reviewed the entire PR myself
 - [ ] I described all breaking changes

**Comment by arboleya** [comment]
- Closes #2560

# Checklist

 - [ ] I added tests
 - [ ] I triple-checked the docs
 - [ ] I reviewed the entire PR myself
 - [ ] I described all breaking changes

**Comment by arboleya** [comment]
We should also consider a CI check to validate that breaking `!`PRs have detailed breaking notes.

**Comment by arboleya** [comment]
Real-world example [here](https://github.com/FuelLabs/fuels-ts/issues/2609#issuecomment-2198286034).

**Comment by maschad** [comment]
Thanks for opening this @arboleya this will definitely help in the review process.

My preference is for the  [full template](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279189)

I think we should ensure we include comments in the PR template to indicate what the sections should be populated with, so for example

```markdown
<!--
Please write a summary of your changes and why you made them.
Please format the issue you are closing with a - beside it, for example:
- Closes https://github.com/FuelLabs/fuels-ts/issues/ABCD.
-->

# Summary
```

Also I think we should be a bit more explicit in the **Checklist** so that external contributors have no ambiguity about what is required before opening a PR for review.

My suggestion would be:

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have assigned someone to the pull request
- [ ] I have assigned the pull request a milestone


We could also highlight in the [`CONTRIBUTING.md`](https://github.com/FuelLabs/fuels-ts/blob/master/CONTRIBUTING.md) that PRs should be in draft until they have completed the checklist to make reviews more seamless.

Otherwise everything else looks good.

**Comment by arboleya** [comment]
The [minimal](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279806) template is the same as the [full](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279189) one but without "Summary" or "Breaking Changes."

Not all PRs will be complex or substantial enough to require all these sections; some can be optional.

As you exemplified, I agree with replacing the placeholder/demo texts with comments.

I was hesitant about having checklists because they become white noise. 

We can try a few options to see if there's a nice middle ground.

Here's another:

 - [ ] I _added_ — `tests` to prove my changes
 - [ ] I _updated_ — all the necessary `documentation`
 - [ ] I _reviewed_  — the entire PR myself, using the `GitHub UI`
 - [ ] I _described_  — all `Breaking Changes` and `Migration Guide`
 - [ ] I _checked_  — the impact of `Breaking Changes` on existing apps

The latter is questionable, but it can have its utility.

PR assignment, label, and milestone can be left out.

**Comment by maschad** [comment]
> The [minimal](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279806) template is the same as the [full](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279189) one but without "Summary" or "Breaking Changes."
> 
> Not all PRs will be complex or substantial enough to require all these sections; some can be optional.
> 
> As you exemplified, I agree with replacing the placeholder/demo texts with comments.
> 
> I was hesitant about having checklists because they become white noise.

Thanks for the clarification, in that case I agree.

> We can try a few options to see if there's a nice middle ground.
> 
> Here's another:
> 
> * [ ]  I _added_ — `tests` to prove my changes
> * [ ]  I _updated_ — all the necessary `documentation`
> * [ ]  I _reviewed_  — the entire PR myself, using the `GitHub UI`
> * [ ]  I _described_  — all `Breaking Changes` and `Migration Guide`
> * [ ]  I _checked_  — the impact of `Breaking Changes` on existing apps
> 
> The latter is questionable, but it can have its utility.
> 
> PR assignment, label, and milestone can be left out.

That's reasonable, I only suggested the milestone and assignee because it's apart of our review process, but I don't have a strong opinion on it, I think the above checklist is sufficient as well.

**Comment by danielbate** [comment]
I also prefer the [full template](https://github.com/FuelLabs/fuels-ts/issues/2649#issuecomment-2198279189).

I'm also not a huge fan of checkboxes but let's see, these ones seem reasonable.

> I checked — the impact of Breaking Changes on existing apps

What are we expecting for this? Existing apps being those outside the SDK? As we removed the breaking change workflow in #2631 and I can't see externals doing this. Internal app breakages should be immediately apparent with a failed build.
