### ISSUE TITLE
Improve AbiCoder

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#268]
- Add a way to check if a type is a reference type

**Comment by luizstacio** [comment]
This is also related to #231 also this comment: https://github.com/FuelLabs/fuels-ts/issues/231#issuecomment-1127644950

We can completely remove the check the type and just [check if args has more them 8 bytes.](https://github.com/FuelLabs/fuels-ts/blob/59cbeff8331f3c3a4e0373e67816fc143d69c2e5/packages/contract/src/scripts.ts#L27)

**Comment by luizstacio** [comment]
> Am I misunderstanding the table here? [FuelLabs/sway#1368](https://github.com/FuelLabs/sway/issues/1368)
> 
> It looks like `const isRef = (bytes) => bytes.length > 8;` wouldn't return the correct result.

I think the table has changed from the type it was like what I said. If wall struct should be pointer we really need to check the type
