### ISSUE TITLE
Integrate `launchTestNode` in remaining packages 

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2698]
Once https://github.com/FuelLabs/fuels-ts/pull/2579 is merged it's a much smaller effort to integrated `launchTestNode` in the remainder of the packages. This issue is a corollary to https://github.com/FuelLabs/fuels-ts/issues/1820 which allows for us to have more incremental and easily reviewable PRs for the integration of the test suite.

The remaining packages include:
- [ ] `docs-snippets`
- [ ] `@fuel-ts/account`
- [ ] `internal`
- [ ] `program`
- [ ] `script`
- [ ] `fuels`
- [ ] `create-fuels`

**Comment by arboleya** [comment]
Blocked by:
 - https://github.com/FuelLabs/fuels-ts/issues/1820

**Comment by arboleya** [comment]
@maschad Do you think we could [unblock and] get this going before https://github.com/FuelLabs/fuels-ts/issues/1820 is merged?

I understand it should be addressed separately, but it doesn't seem like it is actually blocked.

**Comment by maschad** [comment]
Correct @arboleya thanks for highlighting that
