### ISSUE TITLE
Improve `launchTestNode` integration with `typegen` contract factories

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2708]
The interface of `launchTestNode` can be simplified:
```ts
import { launchTestNode } from 'fuels/test-utils';
import { CallTestContractAbi__factory } from '../test/typegen/contracts';

const {
    contracts: [contract],
    cleanup,
  } = await launchTestNode({
    contractsConfigs: [ 
      CallTestContractAbi__factory, 
      { factory: CallTestContractAbi__factory, options: { storageSlots: {}, ... } }
    ],
  });
```
The `contractsConfigs` can now accept a factory directly
```ts
{ contractConfigs: [ CallTestContractAbi__factory ] }
```
but there can still be flexibility for when users want to use `DeployContractOptions` via the `options` property:
```ts
{ contractConfigs: [ { factory: CallTestContractAbi__factory, options: { storageSlots: {}, ... } } ] }
```

**Comment by danielbate** [comment]
This was closed by #2686.

**Comment by petertonysmith94** [comment]
@danielbate are you sure?

I believe this refers to passing in factories as an array element:
```ts
contractConfigs: [ CallTestContractAbi__factory ]
```

Currently we only support an object:
```ts
contractConfigs: [{
  factory: CallTestContractAbi__factory
}]
```

**Comment by danielbate** [comment]
I closed it as #2686 meant we no longer had to pass to bytecode as config. 

Personally I like the explicitness of passing the object rather than object OR factory.

**Comment by nedsalk** [comment]
@danielbate as @petertonysmith94 said, this wasn't completed. Having to pass the bytecode as config was the thing blocking it and #2824 resolved that. I will reopen it.

**Comment by danielbate** [comment]
IMO there isn't a massive improvement from:

```ts
contractConfigs: [{
  factory: CallTestContractAbi__factory
}]
```

to:

```ts
contractConfigs: [ CallTestContractAbi__factory ]
```

Just seems like we are going to be type overloading.

**Comment by nedsalk** [comment]
The `options` property is rarely used even in our own tests - maybe nowhere except `launch-test-node.test.ts` - so making the default simpler is a win in my book.
