### ISSUE TITLE
Node started via `launchTestNode` isn't closed in tests

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2712]
# Repro

Create a test with the snippet below and execute it.

```console
pnpm test:filter launching.test.ts
```

The test finishes and exits, but `fuel-core` continues running in the background.

```ts
// launching.test.ts
import { sleep } from 'fuels';
import { launchTestNode } from 'fuels/test-utils';

test('it works', async () => {
  console.log('before');
  using node = await launchTestNode();
  await sleep(2500);
  console.log('after', node.provider.url);
});
```

# Repro 2

I also tried it with `const` + `cleanup`; nothing changed.

```ts
import { sleep } from 'fuels';
import { launchTestNode } from 'fuels/test-utils';

test('it works', async () => {
  console.log('before');
  const node = await launchTestNode();
  await sleep(2500);
  console.log('after', node.provider.url);
  node.cleanup();
});
```

# Repro 3

However, it works if I transform this into a regular file (not a test) and execute it.

```ts
import { sleep } from 'fuels';
import { launchTestNode } from 'fuels/test-utils';

function main() {
  console.log('before');
  using node = await launchTestNode();
  await sleep(2500);
  console.log('after', node.provider.url);
};

main.catch(console.error);
```

# Conclusion

The utility fails where it will be primarily used: in tests.

**Comment by arboleya** [comment]
@maschad Have you experienced this in your PR?

**Comment by maschad** [comment]
@arboleya examining the code snippets you've shared I believe the setup is incorrect. If I add some logs to the `Symbol.dispose` symbol which is called at the end of the function scope of a variable initialized with the `using` keyword, I can observe that the resources are properly cleaned up. More info [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html)

For example, If we have the following test:

```ts
  it.only('dummy test', async () => {
    console.log('before');
    using node = await launchTestNode();
    console.log('after');
  });
```

and we add some logs to the [`[Symbol.dispose]`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/src/test-utils/launch-test-node.ts#L172) returned by `launchTestNode` 

```ts
 [Symbol.dispose]: () => {
      console.log('disposing provider');
      cleanup();
    },
```

we will observe the following output    

```console
stdout | packages/fuel-gauge/src/reentrant-contract-calls.test.ts > Reentrant Contract Calls > dummy test
before

stdout | packages/fuel-gauge/src/reentrant-contract-calls.test.ts > Reentrant Contract Calls > dummy test
after
disposing provider
```

**Comment by nedsalk** [comment]
I can reproduce this bug locally.

**Comment by maschad** [comment]
Good call @nedsalk I had made the false assumption that when `Symbol.dispose` was called the process was cleaned up. Thanks for catching this @arboleya
