### ISSUE TITLE
Upgrade `typedoc` dependency 

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2713]
Upgrading [typedoc](https://github.com/FuelLabs/fuels-ts/blob/master/apps/docs/package.json#L29) to `0.26.x` has caused issues in our doc building process and thus can't be done by dependabot.

**Comment by petertonysmith94** [comment]
Ignored this minor version in dependabot:
- https://github.com/FuelLabs/fuels-ts/pull/2765#issuecomment-2227851864

**Comment by aditya172926** [comment]
Working on this issue in parallel with #2610 
Draft PR #2650
