### ISSUE TITLE
Improving method DX for `getMessageProof`

### ISSUE THREAD

**Issue by mvares** [FuelLabs/fuels-ts#2736]
Currently, the code doesn't allow the use of both parameters at the same time. To use `commitBlockHeight`, I need to define `commitBlockId` as `undefined`, which doesn't seem to be a comprehensible approach for users.

https://github.com/FuelLabs/fuels-ts/blob/5b53581dddbac066424202c2c455427b2afd74dc/packages/account/src/providers/provider.ts#L1605-L1610

Therefore, I think it might be interesting if we could define this within an object:

```ts
async getMessageProof(
    transactionId: string,
    nonce: string,
    options: { 
      commitBlockId?: string,
      commitBlockHeight?: BN 
     }
  )
```

**Comment by petertonysmith94** [comment]
I think this has merit:
- Has better conformity with our approach to options.
- More explicit for the end user.

**Comment by mvares** [comment]
Makes sense. I think it's better to stick with the current DX.
