### ISSUE TITLE
Multiple wallets with individual configs in `launchTestNode`

### ISSUE THREAD

**Issue by mvares** [FuelLabs/fuels-ts#2746]
Adds a feature that allows wallets to be created with individual configurations. Currently, when we use `assets` or `coinPerAsset`, these configurations are applied to all wallets (e.g., if 2 wallets are created, they will be created with the same configuration)

```ts
export interface WalletsConfigOptions {
  /**
   * Number of wallets to generate.
   */
  count: number;

  /**
   * If `number`, the number of unique asset ids each wallet will own with the base asset included.
   *
   * If `AssetId[]`, the asset ids the each wallet will own besides the base asset.
   */
  assets: number | AssetId[];

  /**
   * Number of coins (UTXOs) per asset id.
   */
  coinsPerAsset: number;

  /**
   * For each coin, the amount it'll contain.
   */
  amountPerCoin: number;

  /**
   * Messages that are supposed to be on the wallet.
   * The `recipient` field of the message is overriden to be the wallet's address.
   */
  messages: TestMessage[];
}

```

**Comment by nedsalk** [comment]
@mvares this would make the API more complex. Can you give us an use case that would justify this change?

**Comment by mvares** [comment]
> @mvares this would make the API more complex. Can you give us an use case that would justify this change?

After I sent this issue, I took some time to reflect. 

Sometimes, it might be beneficial because I could handle specific scenarios. However, as you mentioned, this would make the API more complex, and I don't think the reason I provided is insufficient for this feature.

**Comment by mvares** [comment]
Moreover, I considered throwing an error at `compile-time`, but we would need to implement some workarounds in the code.

**Comment by nedsalk** [comment]
> [...] and I don't think the reason I provided is insufficient for this feature.

You mean you don't have sufficient reasons for this feature?

> Moreover, I considered throwing an error at compile-time, but we would need to implement some workarounds in the code.

I don't follow. Where/when/why would you throw a compile-time error?

**Comment by mvares** [comment]
> You mean you don't have sufficient reasons for this feature?

Yes, I don't have sufficient reasons for this feature. Currently, I'm working on an issue, and I see that this feature could be beneficial for handling specific scenarios where `wallet A` would need specific assets, while `wallet B` does not. 

> I don't follow. Where/when/why would you throw a compile-time error?

If I use count, `individualsConfig` cannot allow more entries than the number of wallets generated. For example, if the count is `2`, `individualsConfig` should only accept `two` arrays.

**Comment by nedsalk** [comment]
Thanks for opening the issue, regardless! I'll be closing it now. If any new ideas on this topic come to mind, feel free to write them here and we can evolve the topic.
