### ISSUE TITLE
Fix BlockHeight and Maturity types

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#275]
There is a confusion if these should be defined as u32s or u64s in the repo. The [specs](https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/tx_format.md) say it should be u32, but fuel-core GQL API uses U64s.

Either the spec or fuels-ts and fuel-core should be updated.

**Comment by adlerjohn** [comment]
There's an issue in the specs to make all those types `u64` in favor of consensus rules to bound them rather than types. https://github.com/FuelLabs/fuel-specs/issues/298

**Comment by Torres-ssf** [comment]
This Issue was already fixed
