### ISSUE TITLE
`create fuels` template broken metadata

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#2753]
Looks like as a part of the migration to Next.js App router (#2580), the metadata for the `create fuels` template app wasn't migrated properly and it is not showing properly anymore:

<img width="228" alt="image" src="https://github.com/FuelLabs/fuels-ts/assets/39617427/8d09ed66-c4ff-42e7-a727-e41156f65f56">

The template used to have a favicon and the title 'Fuel App'.

**Comment by mvares** [comment]
Hey @Dhaiwat10! With the arrival of Next 14, they now use `Metadata` for handling things like SEO, favicon, title, etc.
