### ISSUE TITLE
Improve faucet integration in `create fuels` 

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2774]
It'll be possible to use a `redirectUrl` param when sending users to the faucet:
 - https://github.com/FuelLabs/faucet/pull/73

We could also integrate the faucet by providing an iframe like was proposed in #2984.

We should use that to improve the flow of funding the wallet.

**Comment by arboleya** [comment]
Blocked by:
 - https://github.com/FuelLabs/faucet/pull/73

**Comment by danielbate** [comment]
This could also be integrated via iframe like was proposed in #2984.

Going to modify the issue description slightly.

**Comment by danielbate** [comment]
Closed by #3036
