### ISSUE TITLE
Migrate `create fuels` template from NextJS to Vite

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2781]
Our current [template bootstrapped dApp](https://github.com/FuelLabs/fuels-ts/tree/master/templates/nextjs) is templated in NextJS, based on conversations with @FuelLabs/devrel we have determined that a basic React template using [vite](https://vitejs.dev/) would be more useful for devs.

**Comment by arboleya** [comment]
Closing in favor of:
 - https://github.com/FuelLabs/fuels-ts/issues/2837
 - https://github.com/FuelLabs/fuels-ts/issues/2838
