### ISSUE TITLE
Make `Option<x>` optional with typegen

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2788]
For a simple sway program:
```sway
contract;

abi MyProgram {
    fn optional_input(input: Option<u8>) -> u8;
}

impl MyProgram for Contract {
    fn optional_input(input: Option<u8>) -> u8 {
        1
    }
}
```

Typegen generates the function type
```ts
optional_input: InvokeFunction<[input: Option<BigNumberish>], number>;
```
which mandates providing an input even though it's optional in sway. The generated type should be
```ts
optional_input: InvokeFunction<[input?: Option<BigNumberish>], number>;
```

Note that this might become tricky once multiple inputs are introduced where some are optional and some are not, akin to what is mentioned in #2148.

**Comment by mvares** [comment]
@nedsalk, in more complex Sway programs using `Option<x>`, does this still happen?
