### ISSUE TITLE
Debug randomized maturity issues in policy tests

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2795]
In https://github.com/FuelLabs/fuels-ts/pull/2579 the variations in [block maturity](https://docs.fuel.network/docs/specs/tx-format/policy/#maturity) policy seemed to cause failures in the [policy test suite](https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/policies.test.ts) we should re-introduce it but we need to investigate what the cause of those failures were.

**Comment by arboleya** [comment]
@maschad Do we have failing tests for this, or am I missing the problem?

The [policy test suite](https://github.com/FuelLabs/fuels-ts/blob/master/packages/fuel-gauge/src/policies.test.ts) you mentioned doesn't seem to have any skipped test.

It's not clear to me what we should re-introduce.

**Comment by maschad** [comment]
Good catch @arboleya I believe this had been resolved based on a similar recommendation as the one @Torres-ssf  made [here](https://github.com/FuelLabs/fuels-ts/issues/2857#issuecomment-2260332421)
