### ISSUE TITLE
Eliminate hardcoded Sway scripts

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#281]
We have at least one hardcoded script in the project that looks like this:
```
export const returnZeroScript = new Script(
  /*
    Opcode::RET(REG_ZERO)
    Opcode::NOOP
  */
  '0x24000000',
  () => new Uint8Array(0),
  () => undefined
);
```

We should do something more maintainable.

More discussion: https://github.com/FuelLabs/fuels-ts/pull/277#discussion_r875241902

**Comment by adlerjohn** [comment]
This would be either Sway code, or writing asm instead of raw bytecode. The latter might require the equivalent of `fuel-asm` in typescript, which wouldn't inherent be a bad thing to have.

**Comment by luizstacio** [comment]
It would be nice to have `@fuel-ts/asm`. The solution today uses the `script bin` generated on `build time`; it's much easier to maintain but doesn't deliver a good extendability to the SDK users.

If the user needs an app-specific script like a multi-call or something, he would need to put in place the process of building the `.sw` script, get the bin and append variables, etc...

**Comment by luizstacio** [comment]
@AlicanC as `returnZeroScript ` is very simple and will probably not generate a lot of maintenance, maybe we can close this issue and favor of future one to work on `@fuel-ts/asm` or something similar.

**Comment by adlerjohn** [comment]
Agree that the equivalent of https://github.com/FuelLabs/fuel-asm in TS would be nice to have.

**Comment by luizstacio** [comment]
Closing in favor of: https://github.com/FuelLabs/fuels-ts/issues/332
