### ISSUE TITLE
Private field "#et" must be declared in an enclosing class

### ISSUE THREAD

**Issue by fl0ydj** [FuelLabs/fuels-ts#2818]
### fuels-ts SDK Version

fuels@0.92.1

### Toolchain Versions

Don't have this

### Node.js Version

v20.12.2 but also observed with other nodejs versions

### Browser

Chrome but also observed with others

### Operating System

macOs

### Describe the Problem

The enum coder class in @fuel-ts/abi-coder is incorrectly being transpiled during next build. Even if NODE_ENV is set to development, it still produces the error.
Running next dev works.

The private method decodeNativeEnum somehow is not accessible leading to syntax errors in the produced js code.

Not sure at all why this is happening.

### Errors

```shell
Private field "#et" must be declared in an enclosing class

-> where #et is the minified version of #decodeNativeEnum
```

**Comment by petertonysmith94** [comment]
Hey @fl0ydj 👋 

Thanks for reporting this issue. I've just tried to replicate this my side and everything seems to work correctly. Could you provide us  with a repository or Gist with a reproduction of this error please?
