### ISSUE TITLE
Stop using Sparse Merkle Tree

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#2828]
We may have `fuel-core` removing the use of SMT.

I know we have a package:
 - [fuels-ts/tree/master/packages/merkle](https://github.com/FuelLabs/fuels-ts/tree/master/packages/merkle)

Which was ported from:
 - [fuel-vm/tree/master/fuel-merkle](https://github.com/FuelLabs/fuel-vm/tree/master/fuel-merkle)

A quick search led me here. I'm not sure about the state of this port, but it can be a good starting point to look into.

https://github.com/FuelLabs/fuels-ts/blob/b1dbe42361e52af77f124ec8c633e86885a790be/packages/account/src/predicate/predicate.ts#L65

---

Related:
 - https://github.com/FuelLabs/fuel-core/issues/2042

**Comment by Torres-ssf** [comment]
As mentioned in the [fuel-core issue](https://github.com/FuelLabs/fuel-core/issues/2042), the use of SMT has only been removed from the `balanceRoot` and `stateRoot` fields, which are part of the [OutputContract](https://docs.fuel.network/docs/specs/tx-format/output/#outputcontract).

These fields are exclusively set by the Client/VM. In the TypeScript SDK, we simply de/serialize these values from a processed transaction. Therefore, we can safely close this issue.
