### ISSUE TITLE
Contract Module needs to check Wallet and Provider type in a more robust way

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#285]
The contract module checks `instanceof` the `walletOrProvider` against `Wallet` and `Provider` which can return false depending on where imported from:

In `Contract`, the import is `import {Wallet} from '@fuel-ts/wallet';`
```javascript
if (walletOrProvider instanceof Wallet) {
  this.provider = walletOrProvider.provider;
  this.wallet = walletOrProvider;
} else if (walletOrProvider instanceof Provider) {
  this.provider = walletOrProvider;
  this.wallet = null;
} else {
  this.provider = null;
  this.wallet = null;
}
```

In a consumer React/TypeScript app, a developer might instead get Wallet from:
`import {Provider, Wallet} from 'fuels';`

Example:
```javascript
import {Provider, Wallet as UmbrellaWallet} from 'fuels';
import {Wallet as DirectWallet} from '@fuel-ts/wallet';

export const compare = (): void => {
  const provider = new Provider('http://127.0.0.1:4000/graphql');
  const w1 = UmbrellaWallet.generate({provider});
  const w2 = DirectWallet.generate({provider});

  console.log(w1 instanceof UmbrellaWallet);
  console.log(w1 instanceof DirectWallet);
  console.log(w2 instanceof UmbrellaWallet);
  console.log(w2 instanceof DirectWallet);
};
```

See [relevant contract source](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/src/contract.ts#L155)

## Options
Since the `instance.constructor.name` is minified/uglified out at runtime, this cannot be checked. The suggested plan is to add some constant property onto the object (`instance.name`) or  (`instance.type`) to better solve for this check.

[See also stackoverflow](https://stackoverflow.com/questions/41587865/using-instanceof-on-objects-created-with-constructors-from-deep-npm-dependenci)

**Comment by AlicanC** [comment]
I was working under the assumption that we were all aware and okay with this behavior. (At least for now I mean.)

Does this block anything? Frontend should just use `fuels` and if it needs any other packages we can just put them in `fuels`.
