### ISSUE TITLE
Complex tx example dApp

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#2850]
@SilentCicero has requested a complex example dApp to support devrel:

It should have the following spec
1. Templated with `create fuels` for local development support
2. Replace the counter contract with a token minter contract (multi asset example in [sway-playground](https://www.sway-playground.org/) for context)
3. Introduce 4 predicates in 4 additional, separate workspaces. Each predicate can be very simple as follows:

```rs
predicate;

configurable {
    INDEX: u64 = 1,
}

fn main(input: u64) -> boolean {
    input === INDEX
}
```

5. In the dApp, it should send the following transactions which will produce a 3 kinds (two fungible / one NFT) of tokens to specific predicate addresses:

> - Send/mint fungible 10,000 asset A to predicate A
> - Send/mint fungible 10,000 asset B to predicate A
> - Send/mint fungible 5000 asset A to predicate B
> - Send/mint fungible 5000 asset B to predicate C
> - Send/mint 1 non-fungible asset to predicate D

6. Create a tx that utilises and attempts to spend all the assets from the previous txs via the predicate code.

**Comment by maschad** [comment]
Before creating another example dApp, given we currently already maintain two, I do wonder if we could explore the possibility of covering such an advanced use case in the [cookbook](https://docs.fuel.network/docs/fuels-ts/cookbook/), similar to how we conduct such a complex transaction using doc snippets such as one with [multiple signers](https://docs.fuel.network/docs/fuels-ts/cookbook/transactions-with-multiple-signers/). This example essentially highlights a complex use of scripts and multiple UTXOs. At the very least this could the precursor for the example dApp.

**Comment by danielbate** [comment]
Given the [above comment](https://github.com/FuelLabs/fuels-ts/issues/2850#issuecomment-2256390403) and #2864, moving this to `p1`

**Comment by arboleya** [comment]
@danielbate If #2864 suffices, we can safely close this issue.
