### ISSUE TITLE
UTXOs Cache Mechanism Needs To Consider Message Nonces

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2855]
The current UTXOs [cache mechanism](https://github.com/FuelLabs/fuels-ts/pull/930) needs to be refactored to include caching of message nonces. This is essential because message coins, uniquely identified by their nonces, are resources that can be used to fund transactions.

The cache mechanism must account for message coins to ensure the SDK is aware of all resources to be spent. This refactor will prevent errors such as the SDK using the same message to fund multiple transactions submitted within a short period of time (to be processed and mined at the same node).

**Comment by arboleya** [comment]
Considering mentioning why we enable cache by default in the docs:
 - https://github.com/FuelLabs/fuels-ts/issues/2858
