### ISSUE TITLE
The historical view is not implemented for `MemoryStore`

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2857]
As we integrated `launchTestNode` across the whole monorepo, instances of the the error 
```ts
FuelError: got error during work with storage The historical view is not implemented for `MemoryStore`
```  
appear [more frequently](https://github.com/FuelLabs/fuels-ts/actions/runs/10151394064/job/28070565753?pr=2811#step:5:1006) in test runs, which affects the consistency of our tests. This is obviously due to the fact that we are using an in-memory database, but using a persistent key-value store comes with it's own challenges, and there aren't any test cases where we actually require historical data yet, so I wouldn't suggest that as a solution.

We should at the very least handle this error as it's not relevant to our test cases, so that we reduce flakiness in our CI checks.

Related to https://github.com/FuelLabs/fuels-ts/issues/2698

Related to https://github.com/FuelLabs/fuels-ts/issues/1755

**Comment by arboleya** [comment]
What is there to be fixed on the ts-sdk?

**Comment by maschad** [comment]
@arboleya the error is being thrown [here](https://github.com/FuelLabs/fuels-ts/blob/master/packages/account/src/providers/provider.ts#L570-L574) on random tests,  so I've tried a very rudimentary [way to suppress it](https://github.com/FuelLabs/fuels-ts/pull/2811/files#diff-69a6670d0426c74935ed2830ce552e7df2379c2d112a582306e57569fcd17029R572-R579) in the tests since it's not relevant to our test cases, but I haven't investigated the issue in depth to see the root cause.

**Comment by petertonysmith94** [comment]
Had a brief look and it appears to occur predominantly when we pass through a custom POA, however, this could be a red herring.

**Comment by arboleya** [comment]
Following @Torres-ssf investigations, I understood it's coming from `fuel-core`.

If that is true, it may have nothing to do with `launchTestNode`, which makes this issue a bit misleading.

**Comment by maschad** [comment]
@arboleya thanks for sharing that information, I'm still unsure how to reproduce the issue consistently. My primary rationale for raising this issue is that it's currently failing tests on https://github.com/FuelLabs/fuels-ts/pull/2811 and so at the very least we should handle the error / suppress it in test runs so it's not relevant to them.

@petertonysmith94 for that reason I've made it a `p0`

**Comment by maschad** [comment]
I've lowered this to a `p2` as it seems by skipping the [main test](https://github.com/FuelLabs/fuels-ts/blob/mc/chore/integrate-launch-test-node-in-remaining-packages/apps/docs-snippets/src/guide/cookbook/transferring-assets.test.ts#L73) causing this issue, it can be avoided.

**Comment by Torres-ssf** [comment]
@maschad, I believe this error can be mitigated by using a longer `--poa-interval-period` when starting the node.

I am under the impression that this error tends to occur when the `--poa-interval-period` is set to a very short duration, such as a few milliseconds.

The reasoning is that a shorter `--poa-interval-period` causes nodes to be spawned more quickly, and since we are not using a persistent data solution, I suspect `fuel-core` eventually has trouble accessing data written in previous nodes, though I am not entirely sure about this.

**Comment by maschad** [comment]
@Torres-ssf I'm aware that the issue is related to `--poa-interval-period` as I had previously tried [altering the period](https://github.com/FuelLabs/fuels-ts/pull/2811/commits/44299371e9aa2cda3cfdb2a8617cfef4d8622fb5) in previous commits but to no avail. Likewise I can't pinpoint the exact cause. 

Unfortunately your recommendation is insufficient for [this test use case](https://github.com/FuelLabs/fuels-ts/blob/mc/chore/integrate-launch-test-node-in-remaining-packages/apps/docs-snippets/src/guide/cookbook/transferring-assets.test.ts#L73) (or any test similar to it) as it requires a transaction _maturity > 1_ and so we need a shorter interval period to increase block production time for such scenarios.

**Comment by maschad** [comment]
I'm unassigning myself from this for now as it would require substantial engineering effort and currently only one test would benefit from it. We can revisit this in the future if needs be.

**Comment by arboleya** [comment]
Should be automatically solved when `fuel-core` releases this:
 - https://github.com/FuelLabs/fuel-core/pull/2063


@maschad @Torres-ssf Please reopen if necessary.
