### ISSUE TITLE
Improve docs around `cachUTXO` usage 

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2858]
As a follow-up to https://github.com/FuelLabs/fuels-ts/issues/2816 we should document the rationale why it's enabled by default, and also potential issues around disabling cache as warning to most users not to do so.

**Comment by arboleya** [comment]
Moved as a comment on the related existent issue:
 - https://github.com/FuelLabs/fuels-ts/issues/2855
