### ISSUE TITLE
Integrate the `stateConfig.contracts` field into `launchTestNode`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#2878]
When deploying contracts in `launchTestNode`, we can put them directly on the genesis block instead of deploying them afterwards via the `ContractFactory`. We'd do that by integrating it with the `contracts` field of `stateConfig`. An example can be found [here](https://github.com/FuelLabs/fuel-core/blob/c2f5a3a64c0e792ef5390346ce0264696c95ea21/bin/fuel-core/chainspec/local-testnet/state_config.json#L123).

**Comment by arboleya** [comment]
I'd argue that we should not do this and continue deploying as we do to dogfood the functionality.

**Comment by nedsalk** [comment]
@arboleya That's a good point and I agree with it. I'll close the issue.
