### ISSUE TITLE
Evaluate Global Resources Cache Within Provider Instances

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2893]
The current implementation of the resources cache, managed by the [Provider instance](https://github.com/FuelLabs/fuels-ts/blob/4e82ad42b84e520c3133907aabeea2aad1c1a199/packages/account/src/providers/provider.ts#L376), utilizes a global cache. 

This design ensures that the cache is shared among all `Provider` instances within the same dApp. This approach was chosen due to the possibility that multiple providers may be instantiated from different parts of the dApp, and transactions can be submitted from these various instances using resources owned by the same address.

While the global cache design has its advantages, it also introduces some unintentional issues:

1. Each `Provider` instance can set its cache Time-To-Live (TTL), leading to confusion since the actual cache is shared among all instances.
2. Developers might expect each `Provider` instance to manage its own cache independently, leading to potential misunderstandings.

Given the potential unintentional problems, this issue should serve as a reminder to continuously evaluate if another approach is more suitable.

**Comment by arboleya** [comment]
Should we make the setter for the TTL a static method on the provider class?

**Comment by nedsalk** [comment]
@arboleya yes, if we're going to make the cache static then we should make the TTL setter static as well. 
```ts
public class Provider {
  static cache?: ResourceCache = new ResourceCache(20000);
  
  static updateCacheTtl(ttl: number) {
    if (ttl === -1) { this.cache = undefined; return; }
    const activeData = this.cache?.getActiveData();
    // activeData as the second argument is used to invalidate the data based on the new ttl
    this.cache = new ResourceCache(ttl, activeData);
  }
}
```

I'm not sure about the name of `updateCacheTtl` but that's the idea.

**Comment by nedsalk** [comment]
@Torres-ssf Regarding the cache being public, I know that you had some reasoning behind it but I can't remember it... What was it?

**Comment by arboleya** [comment]
@Torres-ssf Comment from Github.

**Comment by arboleya** [comment]
@sergio.torres Comment from Linear.

**Comment by arboleya** [comment]
@Torres-ssf @arboleya These are github handles.

**Comment by arboleya** [comment]
@sergio.torres @anderson.arboleya these are handles from Linear.

**Comment by arboleya** [comment]
Mentioning from Linear @torres-ssf @arboleya

**Comment by arboleya** [comment]
Mentioning from GH @Torres-ssf @arboleya

**Comment by arboleya** [comment]
Mentioning from GH @Torres-ssf @arboleya

**Comment by arboleya** [comment]
Mentioning from Linear @torres-ssf @arboleya

**Comment by maschad** [comment]
Closing this as not planned based on investigations

See more [here](https://github.com/FuelLabs/fuels-ts/pull/3454)
