### ISSUE TITLE
Review and Validate Sparse Merkle Tree Implementation

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#2916]
We need to validate if the [Sparse Merkle Tree](https://github.com/FuelLabs/fuels-ts/blob/master/packages/merkle/src/sparse/sparseMerkleTree.ts) implementation in the TypeScript SDK is outdated. This implementation is one of the oldest parts of the SDK and has mostly remained unchanged.

To do this, we should:

- Cross-reference related issues and pull requests in the `fuel-core` and `fuel-vm` repositories to ensure our implementation is up-to-date and aligned with the latest standards.
- Validate the implementation by observing all related issues and PRs from both repositories to ensure nothing is amiss.

The goal is to confirm that the implementation is current, maintaining compatibility with updates from `fuel-core` and `fuel-vm`.

**Comment by maschad** [comment]
My investigations into this haven't revealed any discrepancies between our implementation on the specification. If there are any issues or there is something I may have missed feel free to re-open.
