### ISSUE TITLE
Blob upload optimisations

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2917]
Follow up optimisations for #2827

- ~~Improve sync flow. Since #2692 contract deployment has been non blocking. The blob deployment process first deploys blocking blob txs then a non blocking create tx. We should make the whole flow non blocking. Full context [here](https://github.com/FuelLabs/fuels-ts/pull/2827#discussion_r1714942020).~~
- Improve chunk size estimation. Based on [discussions](https://github.com/FuelLabs/fuels-ts/pull/2827#discussion_r1711251634) with @danielbate we determined chunk estimation can be improved. The rationale is that if we know the account's balance, the transaction limit, contract limit and maximum configurable request body size, we can determine an accurate cost before deployment, and thus reduce the need for the user provided value for chunk size tolerance. 
- Blob tx retry conditions - [comment](https://github.com/FuelLabs/fuels-ts/pull/2827/files/fd95a20d87038b30aa1d03fc356648027606ff57#r1715065398)

**Comment by petertonysmith94** [comment]
Wouldn't this be a breaking change?

If yes, would it be worth basing off #2827 and getting it into the release?

**Comment by danielbate** [comment]
IMO the above optimisations that @maschad mentions will definitely reduce the importance of the tolerance level. However unknowns at compile time such as the configurable graph QL body size limit means we should still keep this parameter, and this not introduce a breaking change.

**Comment by danielbate** [comment]
@maschad I'm going to transition this whole issue to blob follow ups.

**Comment by maschad** [comment]
https://github.com/FuelLabs/fuels-ts/pull/3434#issuecomment-2512170624
