### ISSUE TITLE
Typedoc produces unnecessary docs when used with multiple entry points

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#2919]
Following https://github.com/FuelLabs/fuels-ts/pull/2082 we are now able to support multiple entry points in a _typedoc_ configuration, but when one passes multiple entry points it results in [unnecessary files](https://github.com/FuelLabs/fuels-ts/pull/1356#discussion_r1593712213) which contain the exported types along with the relevant typedocs.

E.g. adding `test-utils.ts` to the [contract typedoc](https://github.com/FuelLabs/fuels-ts/blob/master/packages/contract/typedoc.json#L4)

```ts
{
  "$schema": "https://typedoc.org/schema.json",
  "extends": ["../../typedoc.base.json"],
  "entryPoints": ["src/index.ts", "src/test-utils.ts"]
}
```

Results in  the screenshot below:

<img width="304" alt="Screenshot 2024-08-12 at 6 21 16 PM" src="https://github.com/user-attachments/assets/29655781-96d5-453c-a809-3cd69e819878">

**Comment by danielbate** [comment]
These files are expected. Classes and interfaces get there own page, types go on in the index. As we've got two entry points it generates two index files, accessed from the top level index. I'll do a PR.

**Comment by danielbate** [comment]
Ooh actually just need to remove them from the links! Good point.
