### ISSUE TITLE
Calling `wallet.createTransfer()` throws `InsufficientFeeAmount` error

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#2960]
### fuels-ts SDK Version

0.93.0

### Toolchain Versions

1

### Describe the Problem

when calling a simple `createTransfer` request on
- **devnet network**, it's failing with `'Validity(InsufficientFeeAmount { expected: 2817503, provided: 2788618 })'`
- **local network**, it's failing with `'Validity(InsufficientInputAmount { asset: f8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07, expected: 1000048, provided: 971138 })'`

the amount being sent is close to the balance in the user account
```
const to = '0x5502f46f90c3c68c85489b1f57ae6146c81e8549daf408574e3a9a0bb80c4ba0';
const amount = bn(2788617);
const assetId = '0xf8f8b6283d7fa5b672b530cbb84fcccb4ff8dc40f8176ef4544ddb1f1952ad07';
await wallet.createTransfer(
          Address.fromDynamicInput(to),
          amount,
          assetId
)
```

**Comment by petertonysmith94** [comment]
Hey @LuizAsFight,

Do suppose you've got the stack traces for these errors (devnet and testnet if possible)?

Would you also happen to know the balances and transfer amounts at the time/s of experiencing this?

**Comment by danielbate** [comment]
I can also not reproduce this on [master](https://github.com/FuelLabs/fuels-ts/pull/2961) or in an isolated repo on `0.93.0`.

**Comment by LuizAsFight** [comment]
you can reproduce by running this PR locally https://github.com/FuelLabs/fuels-wallet/pull/1427

pr preview link is broken but I am working on it, but for now you can replicate by running locally

**Comment by LuizAsFight** [comment]
fixed it by changing the wallet flow and switching from `provider.getTransactionCost`  to `wallet.getTransactionCost`
