### ISSUE TITLE
Re-evaluate usage of `Buffer` in bytecode compression

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#2984]
Incoming from the [forum](https://forum.fuel.network/t/new-ts-sdk-requires-buffer-which-hinders-frontend-dev/6487)

> The latest version of the TS SDK (0.94.0) uses decompressBytecode function in the factory, which requires the node builtin Buffer, which isn’t available in most Frontend Envs and causes issues especially with Vite.

This causes the following issue on a frontend application:

> ReferenceError: Buffer is not defined

**Comment by arboleya** [comment]
For historical context:
 - https://github.com/FuelLabs/fuels-ts/issues/765
