### ISSUE TITLE
Remove the custom burner wallet from `create fuels` template

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#2998]
We don't need this implementation anymore since we now can utilise the burner wallet connector instead.

**Comment by petertonysmith94** [comment]
We could potentially use the [FuelSDK#selectConnector](https://github.com/FuelLabs/fuels-ts/blob/d51a5631afcf118ca99bdaada67f7d453a57be0c/packages/account/src/connectors/fuel.ts#L56-L57) to default to the burner wallet on initialisation.
