### ISSUE TITLE
Unused `OperationName` Enum Entries in the SDK

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#3008]
Not all entries of the `OperationName` enum seem to be in use. Right now the SDK does not assemble operations for the following enum values:

1. `OperationName.mint`
_Intended to be used when the transaction minted some coins_
2. `OperationName.predicatecall`
_When a predicate code was executed within the TX_
3. `OperationName.script`
_Presumably for script calls, though its exact usage is unclear._
4. `OperationName.sent`
_The purpose of this entry is not well defined._ 

These entries might need to be reviewed and either implemented where necessary or removed if they are irrelevant/redundant.

**Comment by Torres-ssf** [comment]
@LuizAsFight Can you help us determine which operations should be removed/implemented?

**Comment by LuizAsFight** [comment]
I think they can be removed @Torres-ssf
