### ISSUE TITLE
Update Provider Transaction Response waitForResult to poll for updates on SubmittedStatus

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#301]
Per #203 there is a todo within [@fuel-ts/providers](https://github.com/FuelLabs/fuels-ts/blob/master/packages/providers/src/transaction-response/transaction-response.ts#L107-L109) to implement GraphQL subscription or some basic polling feature.

**Comment by luizstacio** [comment]
This would also require something on the `fuel-core` I think. cc: @Voxelot

**Comment by Dhaiwat10** [comment]
This might be a duplicate of #782
