### ISSUE TITLE
Fix integration / UI tests for `create-fuels`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3014]
After merging #2992, integration/UI tests are properly failing.

In `master`:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/10510671296/job/29119853106#step:7:129

In the `changesets` PR:
- https://github.com/FuelLabs/fuels-ts/actions/runs/10510671296/job/29119853106#step:7:129

Since this will halt the next release, we must fix this asap.

**Comment by arboleya** [comment]
One more thing: Could we enable this workflow to run on all PRs?

**Comment by danielbate** [comment]
[Was not resolved](https://github.com/FuelLabs/fuels-ts/actions/runs/10526902267/job/29168819241)

**Comment by petertonysmith94** [comment]
[Not resolved](https://github.com/FuelLabs/fuels-ts/actions/runs/10585770432/job/29333135991)
