### ISSUE TITLE
Implement pagination on Wallet for getCoins / getBalances

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#302]
Per #203 there is a todo within [@fuel-ts/wallet getCoins()](https://github.com/FuelLabs/fuels-ts/blob/master/packages/wallet/src/wallet.ts#L131) and  [@fuel-ts/wallet getBalances()](https://github.com/FuelLabs/fuels-ts/blob/master/packages/wallet/src/wallet.ts#L168) to implement pagination on a Wallet with more than one page of results.

**Comment by Torres-ssf** [comment]
UPDATE:
This is currently blocked since we need the Indexer.
