### ISSUE TITLE
Implement UI testing in `create fuels`

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#3024]
`create fuels` aims to provide a full stack and feature complete solution for working with and deploying dApps on fuel.

We should provide a UI testing solution so that consumers test their frontend applications. We should use something like playwright or vitest to integrate with our own infra.

**Comment by arboleya** [comment]
Terminoplogy-wise, perhaps this could be called `ui` tests.

I expanded on this thought [here](https://github.com/FuelLabs/fuels-ts/issues/3025#issuecomment-2307697078).
