### ISSUE TITLE
Document Error for Failed Transaction Resubmission Due to Spent Resources

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#3049]
Related to https://github.com/FuelLabs/fuels-ts/issues/3009

We need to update our documentation to inform users that re-submitting a transaction request that failed during processing is likely to result in an error. 

This occurs because the VM will still consume the funded resources to cover the gas used up to the point when the transaction reverts. 

In such cases, the SDK will throw the following error:

```ts
FuelError: Transaction is not inserted. UTXO does not exist: {{utxoId}}
```

**Comment by arboleya** [comment]
What is the difference between this issue and https://github.com/FuelLabs/fuels-ts/issues/3009?
