### ISSUE TITLE
Error on contract call forwarding an assetId different from base assetId

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#3053]
### fuels-ts SDK Version

0.94.0

### Describe the Problem

when doing a contract call forwarding an assetId different from the baseAssetId of the provider, I am running into this error.

<img width="348" alt="image" src="https://github.com/user-attachments/assets/f01f8278-ef4f-41b6-b143-547df1f1b436">

2 issues here:
1- estimated maxFee is not enough to pay for the transaction
2- even specifying a maxFee through `.txParams`, is not working, the estimation overrides my params

the issue 2 has already happened before and it was fixed, if it doesn't exist yet I suggest creating a test to make sure it doesn't happen anymore, something like:
- create a contract
- do a contract call infoming `txParams`
- in the last moment before sending the transaction, the `txParams` such as `gasLimit` , `maxFee`, `tip` should remain the same as set before in .txParams

### Reproduce
See it happening in this PR preview link https://github.com/FuelLabs/fuel-explorer/pull/455
you can use the [Fuel Dev Wallet](https://dev-wallet.fuel.network/docs/install/), or run `@FuelLabs/fuels-wallet` repo locally from master branch

Steps:
- open the preview link of bridge app
- click on asset "ETH" in input amount
- in the "TKN" card, click in the faucet button
- deposit TKN to Fuel
- after deposit is completed
- use the tokens received on fuel to start a Withdraw of erc20 TKN

**Comment by petertonysmith94** [comment]
Hey @LuizAsFight,

Struggling to reproduce this issue using the reproduction steps, I'm using the Fuel Development Wallet (v0.27.0) and the latest preview link provided. I get the following error when attempting to confirm the transaction on depositing of TKN:

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/e9b4531b-a181-4a02-b8bb-41d09e1c0852">

I don't suppose you've experienced this before, or know a way to resolve this?

---

I did also observed that during settlement the `getMessageStatus` is return a `NOT_FOUND` state. I'm not sure if this is related.

```json
{"query":"query getMessageStatus($nonce: Nonce!) {\n  messageStatus(nonce: $nonce) {\n    state\n  }\n}","variables":{"nonce":"0x00000000000000000000000000000000000000000000000000000000000e364e"},"operationName":"getMessageStatus"}
```

```ts
{data: {messageStatus: {state: "NOT_FOUND"}}}
```

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/c10fa092-95bc-464b-80b4-e3da23647248">

**Comment by LuizAsFight** [comment]
hey @petertonysmith94 thanks for the answer turns out the issue was occurring only on account that have a InputMessage containing `data`. it would be reproducible only in fuel accounts that received a deposit from erc20 token in the bridge. that was my case.

this PR was created with the fix https://github.com/FuelLabs/fuels-ts/pull/3068

cc @Torres-ssf

**Comment by petertonysmith94** [comment]
@LuizAsFight Wish I could have been more of a help 😓
