### ISSUE TITLE
Consider moving `ApiDocs` outside of the documentation.

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#3058]
### Summary

Currently our API docs are appended to our handcrafted documentation ([example](https://docs.fuel.network/docs/fuels-ts/api/)). This has been the source of a couple of issues and it is aesthetically unappealing in the docs-hub. We should explore the possibility of hosting this ourself (via Vercel perhaps), and adding a reference to this (like the Rust SDK does [here](https://docs.fuel.network/docs/fuels-rs/reference/)).

- [ ] Deploy `ApiDocs`
- [x] Add reference within our docs to this new deployment
- [x] Remove all legacy resources that enabled this process
- [ ] Ensure compatibility with the `docs-hub`

**Comment by danielbate** [comment]
@petertonysmith94 suggested a smarter, phased approach which will allow us to not break the link CI stage. So in [this PR](https://github.com/FuelLabs/fuels-ts/pull/3413) we will ship the API docs, and in a follow-up we will remove the existing API doc code and move links to the shipped API doc URL.
