### ISSUE TITLE
Increase test timeout to reduce flakiness

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3065]
> Ref: https://github.com/FuelLabs/fuels-ts/issues/2967#issuecomment-2313138412

Raw error example:

```console
 FAIL  packages/account/src/test-utils/launchNode.test.ts > launchNode > should throw on error and log error message
Error: Test timed out in 5000ms.
```

**Comment by petertonysmith94** [comment]
@arboleya I don't think this did the job:

- https://github.com/FuelLabs/fuels-ts/actions/runs/10681798669/job/29606209965#step:6:1075
