### ISSUE TITLE
Make `Provider.getMessageByNonce` return parsed data

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#3070]
The method `Provider.getMessages` returns the data parsed 
https://github.com/FuelLabs/fuels-ts/blob/d19736b72f85cce90d4333252175e30be46bdb36/packages/account/src/providers/provider.ts#L1574-L1608

while the `Provider.getMessageByNonce` returns directly the graphql response, I think they should return the same
https://github.com/FuelLabs/fuels-ts/blob/d19736b72f85cce90d4333252175e30be46bdb36/packages/account/src/providers/provider.ts#L1791-L1801

**Comment by arboleya** [comment]
Also, `provider.getMessages()` returns the full messages with all the fields, including `messageId` while `provider.getMessageByNonce()` skips the `messageId` field.

> cc @DefiCake
