### ISSUE TITLE
Typegen fails when handling Sway type aliases

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#3073]
### Summary

We can define [alias types](https://docs.fuel.network/docs/sway/advanced/advanced_types/) in Sway. These are getting incorrectly transpiled and therefore causing the following error while running typegen:

```console
FuelError: Type not supported: (struct std::asset_id::AssetId, struct std::asset_id::AssetId, bool)
```

Incoming from the [forum](https://forum.fuel.network/t/typescript-typegen-doesnt-support-some-types/6546/7).

### Example

Consider the following contract:
```sw
type TupleWithNativeAssets = (AssetId, AssetId, bool);

abi MyContract {
    fn alias_types_tuple_with_native_types(x: TupleWithNativeAssets) -> TupleWithNativeAssets;
}
```

The following transpile ABI is produced:
```jsonc
{
  "types": [
    {
      "typeId": 1,
      // This type is incorrect
      "type": "(struct std::asset_id::AssetId, struct std::asset_id::AssetId, bool)",
      "components": [
        {
          "name": "__tuple_element",
          "type": 22,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 22,
          "typeArguments": null
        },
        {
          "name": "__tuple_element",
          "type": 32,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "x",
          "type": 1,
          "typeArguments": null
        }
      ],
      "name": "alias_types_tuple_with_native_types",
      // ...
    },
  ]
  // ...
}
```

### Expected

We expect to generate a `type` with signature:
`(_, _, _)`

### Actual

We actually generate a `type` with signature:
`(struct std::asset_id::AssetId, struct std::asset_id::AssetId, bool)`

**Comment by petertonysmith94** [comment]
Closed as this appears to be an issue in Sway:
- https://github.com/FuelLabs/sway/issues/6488

**Comment by arboleya** [comment]
@petertonysmith94 Should we add some tests to validate this? They will fail at first, but they'll pass once I merge this:
 - https://github.com/FuelLabs/fuels-ts/issues/3117

The issue (https://github.com/FuelLabs/sway/pull/6494) was fixed in the latest forc:
 - https://github.com/FuelLabs/sway/releases/tag/v0.63.4

**Comment by petertonysmith94** [comment]
@arboleya We have tests [here](https://github.com/FuelLabs/fuels-ts/pull/3066) for an aliased type.

**Comment by arboleya** [comment]
Great! Can we merge these tests, then?

**Comment by petertonysmith94** [comment]
I've based off of:
- https://github.com/FuelLabs/fuels-ts/pull/3118

This is ready to go once we merge the above:
- https://github.com/FuelLabs/fuels-ts/pull/3066

**Comment by arboleya** [comment]
Thank you! 🫡
