### ISSUE TITLE
Fix WARNING: Missing strong random number source

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#309]
This looks to have been introduced with the updated build process, as the dist files generated by wallet are optimized for the browser explicitly.

The best fix would be to use the internal universal crypto -> random bytes: https://github.com/FuelLabs/fuels-ts/blob/master/packages/keystore/src/universal-crypto.ts

**Comment by AlicanC** [comment]
> This looks to have been introduced with the updated build process

What do you mean by "the updated build process"?

**Comment by AlicanC** [comment]
> I can roll back to that state and see for sure

I was just curious if you meant the changes on #238.

> another ethers project dependency is removed

To be clear, I believe `@ethersproject/random` is ok. It seems safer to source this functionality from Ethers which is battle-tested and also tested on browsers and even on React Native: https://github.com/ethers-io/ethers.js/blob/master/package.json#L32-L40

When I was agreeing with the "getting rid of Ethers" discussion, I was meaning the parts that aren't suitable for us, which are just '@ethersproject/abi' and '@ethersproject/logger' if I'm not missing anything.
