### ISSUE TITLE
Add support for proxy contracts in `fuels deploy`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3123]
# Intro

It goes like this:

```toml
[proxy]
enabled = true
```

Docs:
 - https://docs.fuel.network/docs/forc/plugins/forc_client/#proxy-contracts

# Tips

We currently have this helper:
https://github.com/FuelLabs/fuels-ts/blob/751d638fd3324e41906f9170adb3d8caa781414a/packages/fuels/src/cli/config/forcUtils.ts#L35

It is used here, but the `toml` contents get discarded when the method finishes:
https://github.com/FuelLabs/fuels-ts/blob/56018e3720898571074bd2d3994ab48ca44d7185/packages/fuels/src/cli/config/loadConfig.ts#L92

The final touch will probably have to be around here:
https://github.com/FuelLabs/fuels-ts/blob/8faeaa401723f98b5f573700934b786d2ae4dbca/packages/fuels/src/cli/commands/deploy/deployContract.ts#L28

Ultimately, we should probably persist the TOML contents with the other artifacts.

# Notes

I wonder if it'd be a good moment to address this issue together with:
 - https://github.com/FuelLabs/fuels-ts/issues/989

**Comment by danielbate** [comment]
The behaviour of the deployment depends on the existence of both the `proxy` table and the `enabled` and `address` flags. I've created the following decision tree to illustrate the process:

<img width="379" alt="Screenshot 2024-09-19 at 16 48 35" src="https://github.com/user-attachments/assets/c3c7ece4-df67-485f-bd77-32afbad38f5d">
