### ISSUE TITLE
Add CI Benchmarks for Browser environments

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#3136]
https://github.com/FuelLabs/fuels-ts/pull/3084 seeks to introduce benchmarks on CI for local nodes in a Node.js environment. These are intended to be run per PR workflow and currently take ~ 12 mins.  

We would like to support running these in the browser on CI but that would require [extra setup](https://github.com/FuelLabs/fuels-ts/actions/runs/10780020394/job/29894818040?pr=3084#step:6:108) which could take the workflow in excess of ~25 mins. I don't think this would be appropriate to be run per PR or even in a release process, but could be useful post-release (the downside of that is if we introduce a regression in the browser it would be caught after the release) 

I do think though that there is a low probability one could introduce a performance regression that is vastly more significant in the browser than in node, but still possible.

**Comment by arboleya** [comment]
Okay, 25+ minutes seems like a no-go. It's too much. Why does it take so long?

**Comment by maschad** [comment]
I elaborated a bit more [here](https://github.com/FuelLabs/fuels-ts/pull/3084#discussion_r1754833380) but TLDR If we can essentially cache the SDK builds + pretest, as well as the chrome setup ubuntu builds, we can take each benchmark time down to roughly 6 mins which would be 12 mins total.

**Comment by maschad** [comment]
Something to note as well https://github.com/CodSpeedHQ/action/issues/107

**Comment by danielbate** [comment]
Blocked by [Codspeed support for a browser env](https://github.com/CodSpeedHQ/action/issues/107)
