### ISSUE TITLE
Run Benchmarking utility in devnet environment

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#3138]
#3043 seeks to introduce the basic benchmarking infrastructure which has now given us benchmarks against a local `fuel-core` node in a Node.js environment (for browser support see https://github.com/FuelLabs/fuels-ts/issues/3136)

We should also run these benchmarks in devnet, also introducing blob transactions.

**Comment by arboleya** [comment]
I think this could use a similar approach to how we do diffs of code coverage: by having two sets of results, one for the `master` branch and one for the current PR/commit—something like that. If we can upload/retrieve `master` bench results, we don't need to run things twice.
