### ISSUE TITLE
Introduce Benchmark utility to support running different SDK versions

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#3139]
If I would like to measure performance improvements/regressions between two TS SDK versions, we currently have no means of doing that. Ideally we could have a tool that would spin up an instance of two versions of the SDK and perform benchmarking tests such as sending a transaction or deploying a contract

**Comment by arboleya** [comment]
I think this could use a similar approach to how we do diffs of test coverage: by having two sets of results, one for the `master` branch and one for the current PR/commit—something like that. If we can upload/retrieve `master` bench results, we don't need to run things twice

**Comment by maschad** [comment]
I've done a bit more digging and we may not actually need such a tool as CodeSpeed can give us a historical overview, here's an [example of sway](https://codspeed.io/FuelLabs/sway)

and here's an example of a historical overview of [the compile step](https://codspeed.io/FuelLabs/sway/benchmarks/sway-lsp/benches/lsp_benchmarks/compile.rs::benches::benchmarks::compile)

If we are satisfied with this I think we can close this issue. Thoughts? @FuelLabs/sdk-ts

**Comment by Torres-ssf** [comment]
@maschad Nice, this seems to solve the problem. 

No opposition from my side to close this issue.

**Comment by arboleya** [comment]
Agreed.
