### ISSUE TITLE
Change how the SDK uses the JSON ABI schema for function outputs

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/fuels-ts#314]
A change to the JSON ABI schema generated by the Sway compiler (https://github.com/FuelLabs/sway/issues/1818) will change how function outputs are handled. This change will make it such that function outputs in the JSON ABI schema will consist of one value only, instead of the current array of values.

So, we will need to change how the SDK interprets the JSON ABI to accommodate for this change.

The corresponding issue for the spec: https://github.com/FuelLabs/fuel-specs/issues/323

The same change will happen in the Rust SDK: https://github.com/FuelLabs/fuels-rs/issues/358

**Comment by nedsalk** [comment]
@digorithm The [words](https://github.com/FuelLabs/fuels-rs/issues/358#issuecomment-1408858502) of @segfault-magnet ring true for fuels-ts as well.
