### ISSUE TITLE
Include assets for Mainnet

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#3140]
- the current list is missing Ethereum on mainnet (eth network)
- we need to include set of assets other than ethereum (list will be provided when available)

**Comment by arboleya** [comment]
Blocked, waiting for the final assets list.

**Comment by LuizAsFight** [comment]
I already sent this chore PR to include the one is missing https://github.com/FuelLabs/fuels-ts/pull/3152

@arboleya

**Comment by LuizAsFight** [comment]
@arboleya just created this one including the whole list of assets

https://github.com/FuelLabs/fuels-ts/pull/3153
