### ISSUE TITLE
buildBlockExplorerUrl needs to get updated

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#3141]
- it can use the new block-explorer as default URL.. app.fuel.network
- if the user don't pass `blockExplorerUrl` we can try give you the right link anyway instead of default one, given that user informed a `chainId` input

**Comment by danielbate** [comment]
@luiz.gomes we should only need to make the first change as we [default to the block explorer url](https://github.com/FuelLabs/fuels-ts/blob/c98461f49b6a21e0ced9aea99fae0e669447a259/packages/account/src/providers/utils/block-explorer.ts#L37) if one is not provided anyways.
