### ISSUE TITLE
Provide better ergonomics for proxied contract calls

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3145]
We should provide a type-safe API that can work behind proxied contracts.

This should go in tandem with:
 - https://github.com/FuelLabs/fuels-ts/issues/3123

Original request:
 - So, the proxy contract works on dynamically dispatching calls based on the function selector. Previously, to call a contract method, they could use the TS SDK to generate the types for the contract and call the contract by `contractA.functions.someRandomFunc().call()`. However, they're saying for the proxy contract, there isn't any way to call a particular function (say, "someRandomFunc") that is defined in the implementation because the base proxy contract has essentially just a "fallback" method. They've found [this](https://github.com/FuelLabs/proxy-chunks-minimal-example/tree/main), but it mentions the usage of forc that isn't ideal for their use case.

**Comment by arboleya** [comment]
Just some rough ideas. (pseudo-code)

```ts
// instantiating the target and then informing the proxy
targetContract
  .addProxyContract(proxyContract)
  .functions // functions of target contract
  .xyz()
  .call()
```

```ts
// instantiating the proxy and then informing the target
proxyContract
  .addProxiedContract(targetContract)
  .functions // functions of target contract
  .xyz()
  .call()
```

**Comment by danielbate** [comment]
At face value I think this should _work_ out of the box with `addContracts` however we'll get type errors, consider the following example:

```ts
const myContract = new Contract('0x01', MyContractAbi, wallet);
const myProxyContract = new Contract('0x02', MyProxyAbi, wallet);

await myContract.functions.myContractXyz().addContracts([myProxyContract]).call();
```

The proxy and it's ABI is added to the call so can use it and it's logs. However, the ABI is only really useful for logged types. For proxy calls, we also want to be able to call methods available to `myProxyContact`.

The solution `addProxyContract` should perform everything `addContracts` can, but also allow us to safely perform functions from the proxy.

```ts
await myContract.functions.myProxyContractXyz().addProxyContracts([myProxyContract]).call();
```

I'd recommend testing this first with a proxy contract and seeing how it works with the current SDK before informing the solution.

**Comment by arboleya** [comment]
It turns out that proxy contracts are supported out of the box.

The only thing that needs handling is proxy deployments:
 - https://github.com/FuelLabs/fuels-ts/issues/3123
