### ISSUE TITLE
Automatic Linear x Github PR integration

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3157]
# Problem

When integrating with Linear, PRs now must keep track of two things:
 - GitHub Issues
 - Linear Issues

One would expect Linear to follow this automatically, but it doesn't.

Then, we end up with Github Issues vs. Linear Issues, which is not only noisy but also cumbersome to do manually.

![pr-linear](https://github.com/user-attachments/assets/f78f160c-3759-4178-8fa0-613c9ead1ce8)

# Desires

 - Have this working automatically out of the box
 - Keep the Linear magic words out of the PR description

# Solution

Implement workflow automation that will:
 - Find all GH issues the PR is closing
 - Find their related Linear issue IDs
 - Modify the PR description, adding Linear magic words as comments (invisible!)

```
<!-- Closes to TS-1, TS-2, TS-N -->
<!-- Part of to TS-5, TS-7, N -->
```

Premisses:
 - GitHub issues must be informed one per line _(predictable parsing)_
 - Linear Comments can contain multiple issues per line _(it doesn't matter)_

Docs:
 - [Github Keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)
 - [Linear Magic Words](https://linear.app/docs/github?tabs=206cad22125a#link-using-pull-requests) & [Linear API](https://developers.linear.app/docs/graphql/working-with-the-graphql-api/filtering#examples)

# Github Action

The final solution must be a GitHub action that all other repos can reuse; it can go here:
 - https://github.com/FuelLabs/github-actions

**Comment by arboleya** [comment]
Thanks to @nedsalk for the ideas and discussions around this. ❤️

**Comment by arboleya** [comment]
@FuelLabs/sdk-ts While we get there, I enabled this:
 - https://linear.app/docs/github#enable-autolink

Which turns mentions to `TS-NNN` strings into clickable links:
![autolink](https://github.com/user-attachments/assets/abdb1e3f-34f0-49d4-90d5-e899db44a0d2)

**Comment by nedsalk** [comment]
Closing to test out integration with linear - will reopen immediately.
