### ISSUE TITLE
Adjust `types` property in all `package.json` files

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3208]
We need to replicate this to all packages: https://github.com/FuelLabs/fuels-ts/pull/3190/commits/3d0c0f6432297912caa3bb67bd632258d375aef3

It seems that the `types` property must be the first, otherwise we get a warning:

```
Warning: G] The condition "types" here will never be used as it comes after both "import" and "require" [package.json]

    ../../package.json:19:6:
      19 │       "types": "./dist/index.d.ts"
         ╵       ~~~~~~~
```

_Originally posted by @petertonysmith94 in https://github.com/FuelLabs/fuels-ts/pull/3190#discussion_r1773851228_

**Comment by Namanedogawa** [comment]
This PR ensures that the `types` property is correctly positioned as the first property in all `package.json` files to avoid potential warnings during compilation.

I have checked all linked repositories, and this issue has been addressed in all relevant `package.json` files.

This PR closes #3208.
https://github.com/FuelLabs/fuels-ts/pull/3212
