### ISSUE TITLE
Facilitate `devnet` tests on `fuel-gauge` suite

### ISSUE THREAD

**Issue by maschad** [FuelLabs/fuels-ts#3243]
As per discussion with @petertonysmith94 it would be ideal to have an easy way to run the `fuel-gauge` tests against `devnet` as opposed to just solely with `launchTestNode`  perhaps this could be added to the [e2e workflow](https://github.com/FuelLabs/fuels-ts/blob/8321098963996088ba33988176e028a2af5da98b/.github/workflows/test.yaml#L90-L111)

**Comment by petertonysmith94** [comment]
At the moment, I override `launch-test-node` with the following:

https://github.com/FuelLabs/fuels-ts/blob/5194a853e78efeac8144c298044b7265c8a12e54/packages/contract/src/test-utils/launch-test-node.ts#L132-L140


```ts
  // const { provider, wallets, cleanup } = await setupTestProviderAndWallets({
  //   walletsConfig,
  //   providerOptions,
  //   nodeOptions: {
  //     ...nodeOptions,
  //     snapshotConfig,
  //     args,
  //   },
  // });

  const provider = await Provider.create(DEVNET_NETWORK_URL);
  const wallet = Wallet.fromPrivateKey('0xOMITTED', provider); // Obviously adding your private key here.
  const wallets = [wallet, wallet, wallet, wallet, wallet];
  const cleanup = () => {};
  ```
  
  ---
  
  Then I run select tests via test:filter.

**Comment by petertonysmith94** [comment]
I think we need to identify:
- What tests are best for testing a wide range of scenarios (currently I do some predicate, contracts, scripts).

**Comment by petertonysmith94** [comment]
Un-assigning myself for now, as I underestimate the work required + my current workload.
