### ISSUE TITLE
Set Query Limit for `Provider.getTransactions` Method

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#3245]
Similar to what we already do for [Provider.getBlocks](https://github.com/FuelLabs/fuels-ts/blob/8321098963996088ba33988176e028a2af5da98b/packages/account/src/providers/provider.ts#L1509-L1512) and [Provider.getMessages](https://github.com/FuelLabs/fuels-ts/blob/8321098963996088ba33988176e028a2af5da98b/packages/account/src/providers/provider.ts#L1735-L1738), we need to apply a limit for querying transactions using the [Provider.getTransactions](https://github.com/FuelLabs/fuels-ts/blob/8321098963996088ba33988176e028a2af5da98b/packages/account/src/providers/provider.ts#L1616) method. 

Setting a limit of 20~30 should be enough since this method supports pagination.

**Comment by aditya172926** [comment]
I would like to work on this @Torres-ssf. Can I take it up if its not being worked on already?

**Comment by maschad** [comment]
Hey @aditya172926 we appreciate the interest here but unfortunately this is a pressing issue and so someone from the team, in this case @Dhaiwat10 is best suited to handle it
