### ISSUE TITLE
Alter`type:check` command

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#3248]
# Summary

- We currently do `type:check` in various hooks, which can slow down development, so we should move check to our `lint` hook.
- Potentially the best strategy for this issue is to roll back the [original PR](https://github.com/FuelLabs/fuels-ts/pull/3046), then re-add the checks to the related lint command.

## All hooks
- `pretest`
  - https://github.com/FuelLabs/fuels-ts/blob/next/apps/docs-snippets/package.json#L7
  - https://github.com/FuelLabs/fuels-ts/blob/next/internal/benchmarks/package.json#L9
  - https://github.com/FuelLabs/fuels-ts/blob/next/packages/fuel-gauge/package.json#L8
  
- `build`
  - https://github.com/FuelLabs/fuels-ts/blob/next/packages/create-fuels/package.json#L18

- `postbuild`.
  - https://github.com/FuelLabs/fuels-ts/blob/next/packages/fuels/package.json#L59

**Comment by YashSherla** [comment]
Can u assign me

**Comment by maschad** [comment]
Hey @YashSherla we appreciate your interest in this, if you would like to begin working on it feel free to but we prefer to only assign issues to contributors after they have opened a PR.
