### ISSUE TITLE
Review and optimize GQL operations

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3281]
During some load tests, we realized a couple of issues ([#3279](https://github.com/FuelLabs/fuels-ts/issues/3279), [#3277](https://github.com/FuelLabs/fuels-ts/issues/3277)) that we're fixing and optimizing.

In keeping with this theme, we should continue the effort and review our predefined GQL queries and fragments.

Every field removal _is_ a breaking change and _can_ break things for apps, so we need to be extra careful here.

Taking from the [`providers/operations.graphql`](https://github.com/FuelLabs/fuels-ts/blob/d0e9b1a110721fa721aa40f87d7b5515be16b9b3/packages/account/src/providers/operations.graphql):

- [ ] `getVersion`
- [ ] `getNodeInfo`
- [ ] `getChain`
- [ ] `getTransaction`
- [ ] `getTransactionWithReceipts`
- [ ] `getTransactions`
- [ ] `getTransactionsByOwner`
- [ ] `estimatePredicates`
- [ ] `getBlock`
- [ ] `getBlockWithTransactions`
- [ ] `getBlocks`
- [ ] `getCoin`
- [ ] `getCoins`
- [ ] `getCoinsToSpend`
- [ ] `getContract`
- [ ] `getContractBalance`
- [ ] `getBalance`
- [ ] `getLatestGasPrice`
- [ ] `estimateGasPrice`
- [ ] `getBalances`
- [ ] `getMessages`
- [ ] `getMessageProof`
- [ ] `getMessageStatus`
- [ ] `getRelayedTransactionStatus`
- [ ] `getMessageByNonce`

**Comment by petertonysmith94** [comment]
Currently what @Green is doing to capture the GQL is setup a proxy to intercept the requests and dump them into the file `traffic.dump` via the following command:

```
mitmdump --mode reverse:https://mtls-testnet.fuel.network -w traffic.dump
```

**Comment by petertonysmith94** [comment]
List of all operations used **internally** in `provider.ts`

```markdown
dryRun
estimateGasPrice
estimatePredicates
getBalance
getBalances
getBlobs
getBlock
getBlockWithTransactions
getBlocks
getChain
getCoins
getCoinsToSpend
getContract
getContractBalance
getLatestGasPrice
getMessageByNonce
getMessageProof
getMessageStatus
getMessages
getNodeInfo
getRelayedTransactionStatus
getTransaction
getTransactions
getVersion
produceBlocks
submitAndAwaitStatus
```

<br>List of all operations used **external** of the `provider.ts`

```
getTransactionWithReceipts
statusChange
statusChange
getTransactionWithReceipts
getTransactionsByOwner
```

**Comment by arboleya** [comment]
Closed in favor of individual issues that can be done in isolation.
