### ISSUE TITLE
Temporary PR deployments should have the source header populated with the PR number

### ISSUE THREAD

**Issue by petertonysmith94** [FuelLabs/fuels-ts#3285]
### Summary

For temporary PR deployments, we should be able to identify via the `Source` header which version is being used. We could either:
1. Read the version installed on the user's disk
1. Add some automation to update the `getBuiltinVersions` return for temporary releases.

_Originally posted by @nedsalk in https://github.com/FuelLabs/fuels-ts/issues/3282#issuecomment-2401707383_

Follow up from: https://github.com/FuelLabs/fuels-ts/issues/3280

**Comment by petertonysmith94** [comment]
Questions:

With option 1: how do we then add these to the header?
With option 2: this will cause tests to fail.

**Comment by arboleya** [comment]
This is low priority, especially given our moment, and can be circumvented by manually editing the version file.

**Comment by Dhaiwat10** [comment]
Unassigning myself for now then
