### ISSUE TITLE
Optimize general graphql queries

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3288]
During some load tests, we realized a couple of issues ([#3279](https://github.com/FuelLabs/fuels-ts/issues/3279), [#3277](https://github.com/FuelLabs/fuels-ts/issues/3277)) that we're fixing and optimizing.

In keeping with this theme, we should continue the effort and review our predefined GQL queries and fragments.

Every field removal *is* a breaking change and *can* break things for apps, so we need to be extra careful here.

Taking from the [`providers/operations.graphql`](https://github.com/FuelLabs/fuels-ts/blob/d0e9b1a110721fa721aa40f87d7b5515be16b9b3/packages/account/src/providers/operations.graphql):

- [X] `getVersion`
- [X] `getNodeInfo`
- [X] `getChain`
- [X] `getLatestGasPrice`
- [X] `estimateGasPrice`
- [X] `estimatePredicates`

**Comment by maschad** [comment]
Took a look at this and the queries don't look like they could be optimized further. Most of these are relatively simple queries.

```gql
"""
from fuel-core-schema.gql
"""

type NodeInfo {
  utxoValidation: Boolean!
  vmBacktrace: Boolean!
  maxTx: U64!
  maxDepth: U64!
  nodeVersion: String!
  peers: [PeerInfo!]!
}

"""
  Estimate the predicate gas for the provided transaction
  """
  estimatePredicates(tx: HexString!): Transaction!


```




```gql
"""
from operations.graphql
"""
# Queries and Mutations
query getVersion {
  nodeInfo {
    nodeVersion
  }
}

fragment nodeInfoFragment on NodeInfo {
  utxoValidation
  vmBacktrace
  maxTx
  maxDepth
  nodeVersion
}

query getNodeInfo {
  nodeInfo {
    ...nodeInfoFragment
  }
}

fragment chainInfoFragment on ChainInfo {
  name
  latestBlock {
    ...blockFragment
  }
  daHeight
  consensusParameters {
    ...consensusParametersFragment
  }
}

query getChain {
  chain {
    ...chainInfoFragment
  }
}

query getLatestGasPrice {
  latestGasPrice {
    gasPrice
  }
}

query estimateGasPrice($blockHorizon: U32!) {
  estimateGasPrice(blockHorizon: $blockHorizon) {
    gasPrice
  }
}


query estimatePredicates($encodedTransaction: HexString!) {
  estimatePredicates(tx: $encodedTransaction) {
    ...transactionEstimatePredicatesFragment
  }
}


fragment transactionEstimatePredicatesFragment on Transaction {
  inputs {
    ...inputEstimatePredicatesFragment
  }
}


fragment inputEstimatePredicatesFragment on Input {
  ... on InputCoin {
    predicateGasUsed
  }
  ... on InputMessage {
    predicateGasUsed
  }
}
```

All the data queried via these queries is utilized in the places where the queries are used, so there's no place for more optimization.
