### ISSUE TITLE
Optimize contract's graphql queries

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3292]
During some load tests, we realized a couple of issues ([#3279](https://github.com/FuelLabs/fuels-ts/issues/3279), [#3277](https://github.com/FuelLabs/fuels-ts/issues/3277)) that we're fixing and optimizing.

In keeping with this theme, we should continue the effort and review our predefined GQL queries and fragments.

Every field removal _is_ a breaking change and _can_ break things for apps, so we need to be extra careful here.

Taking from the [`providers/operations.graphql`](https://github.com/FuelLabs/fuels-ts/blob/d0e9b1a110721fa721aa40f87d7b5515be16b9b3/packages/account/src/providers/operations.graphql):

- [ ] `getContract`
- [ ] `getContractBalance`

**Comment by nedsalk** [comment]
Took a look at this and the queries don't look like they could be optimized further.

```gql
"""
from fuel-core-schema.gql
"""
type Contract {
  id: ContractId!
  bytecode: HexString!
  salt: Salt!
}

type ContractBalance {
  contract: ContractId!
  amount: U64!
  assetId: AssetId!
}

"""
from operations.graphql
"""
fragment contractBalanceFragment on ContractBalance {
  contract
  amount
  assetId
}

query getContract($contractId: ContractId!) {
  contract(id: $contractId) {
    bytecode
    id
  }
}

query getContractBalance($contract: ContractId!, $asset: AssetId!) {
  contractBalance(contract: $contract, asset: $asset) {
    ...contractBalanceFragment
  }
}
```

All the data queried via these queries is utilized in the places where the queries are used, so there's no place for more optimization.
