### ISSUE TITLE
Implement storage initialization in the SDK

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/fuels-ts#334]
The JSON format spec for storage initialization is now ready: https://github.com/FuelLabs/fuel-specs/blob/master/specs/protocol/storage_initialization.md

The compiler will emit this file (task tracked in https://github.com/FuelLabs/sway/issues/1185) and the SDK read that file and set the initial storage slots in the contract creation tx.

**Comment by luizstacio** [comment]
Today we already support initialization of storage #239

- The new JSON spec should be used to generate types for storage initialization also?

**Comment by adlerjohn** [comment]
> Should the new JSON spec also be used to generate types for storage initialization?

Yes. Well, not types, but values.

**Comment by mohammadfawaz** [comment]
Note that the compiler side of this is still WIP. The compiler does not generate this JSON file yet.

**Comment by luizstacio** [comment]
On PR #344 I have commented the storage initialization due to a difference when calculating `stateRoot` between [fuel-merkle](https://github.com/FuelLabs/fuel-merkle) and [@fuel-ts/merkle](https://github.com/FuelLabs/fuels-ts/pull/packages/merkle).

**Comment by adlerjohn** [comment]
Do you know the root cause of the difference?
