### ISSUE TITLE
How to convert bech32 address to hexadecimal address？

### ISSUE THREAD

**Issue by daihaojun554** [FuelLabs/fuels-ts#3351]
### fuels-ts SDK Version

fuels 0.92.0

### Toolchain Versions

None

### Browser

chrome v5

### Operating System

mac mini

### Describe the Problem

How to convert bech32 address to hexadecimal address？

### Code Snippet

```shell
How to convert bech32 address to hexadecimal address？
```

### Contract ABI

```shell
How to convert bech32 address to hexadecimal address？
```

### Errors

```shell
How to convert bech32 address to hexadecimal address？
```

**Comment by maschad** [comment]
Perhaps you could elaborate a bit more on your use case with a snippet, but have you explored the [`toB256()`](https://docs.fuel.network/docs/fuels-ts/interfaces/abstractaddress/#tob256) method? 

```ts
const bech32 = 'fuel1d5cfwekq78r0zq73g7eg0747etkaxxltrqx5tncm7lvg89awe3hswhqjhs';

Address.fromAddressOrString(bech32).toB256()
```

**Comment by daihaojun554** [comment]
thanks

**Comment by daihaojun554** [comment]
Thank you, I have solved this problem.
