### ISSUE TITLE
`onDeploy` does not work for predicates and scripts in `fuels deploy`

### ISSUE THREAD

**Issue by luisburigo** [FuelLabs/fuels-ts#3356]
It would be interesting to implement this for predicates and scripts to enable some automations. Currently,`onDeploy` is executed after contracts are deployed.
https://github.com/FuelLabs/fuels-ts/blob/88d7535733c98340cd21bc6f7846290c462bef4c/packages/fuels/src/cli/commands/deploy/index.ts#L11-L18

My suggestion would be to implement something like this:

```ts
export async function deploy(config: FuelsConfig) {
  /**
   * Deploy contract and save their IDs to JSON file.
   */
  const contractIds = await deployContracts(config);
  await saveContractIds(contractIds, config.output);

  /**
   * Deploy scripts and save deployed files to disk.
   */
  const scripts = await deployScripts(config);
  saveScriptFiles(scripts, config);

  /**
   * Deploy predicates and save deployed files to disk.
   */
  const predicates = await deployPredicates(config);
  savePredicateFiles(predicates, config);
  
  config.onDeploy?.(config, {
    scripts,
    predicates,
    contracts: contractIds,
  });

  /**
   * After deploying scripts/predicates, we need to
   * re-generate factory classe with the loader coee
   */
  await generateTypes(config);

  return contractIds;
}
```

**Comment by Chirag-S-Kotian** [comment]
assign this to me

**Comment by petertonysmith94** [comment]
Hey @Chirag-S-Kotian,

We generally assign to outside contributors once the PR has been created :) 

Let us know if you need any assistance.

**Comment by Chirag-S-Kotian** [comment]
Assign this to me and give me details for this issue

**Comment by petertonysmith94** [comment]
@Chirag-S-Kotian It looks like @YaTut1901 has already taken on this piece (https://github.com/FuelLabs/fuels-ts/pull/3383); maybe there is a [good first issue](https://github.com/FuelLabs/fuels-ts/labels/good%20first%20issue) that you'd like to contribute to.

**Comment by YaTut1901** [comment]
hello, @petertonysmith94 could you verify if that possible to continue with my PR?

**Comment by petertonysmith94** [comment]
@YaTut1901 - yes, please continue with your PR 🙏🏼

**Comment by YaTut1901** [comment]
then, could you please approve? From my side I do not see any changes
