### ISSUE TITLE
`fuel-core` node cleanup doesn't work in bun

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#3359]
When using `bun v1.1.33`, trying to call `cleanup` on the return of `launchTestNode` results in the following error:
```
282 |       }
283 |       childState.isDead = true;
284 |       removeSideffects();
285 |       if (child.pid !== void 0) {
286 |         try {
287 |           process.kill(-child.pid);
                ^
RangeError: The value of "pid" is out of range. It must be a positive integer.
```
There is the issue https://github.com/oven-sh/bun/issues/8787 which documents an additional occurrence of this problem, so it might not be our fault.

Run the following to reproduce:
```bash
mkdir bun-test && cd bun-test && bun init -y && bun add fuels@0.96.1 && echo 'import { test } from "bun:test";
import { launchTestNode } from "fuels/test-utils";

test("test", async () => {
    using launched = await launchTestNode();
});' > failing.test.ts && bun test
```

**Comment by petertonysmith94** [comment]
Potentially blocked by [https://github.com/oven-sh/bun/issues/8787](https://github.com/oven-sh/bun/issues/8787)
