### ISSUE TITLE
Move script and predicate blob deployment logic away from `ContractFactory`

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#3361]
The predicate and script blob deployment logic currently lives in `ContractFactory.deployAsBlobTxForScript`. We should move it out of there and into a function that can then be used in e.g. `new Predicate(...).deployAsBlob()` and `new Script(...).deployAsBlob()`. This `deployAsBlob` method can then return a new `Predicate`/`Script` instance with the updated bytecode and abi.

**Comment by arboleya** [comment]
Perhaps the method could be called `deploy`.

**Comment by maschad** [comment]
Related to https://github.com/FuelLabs/fuels-ts/issues/2917
