### ISSUE TITLE
Make CI fail when tests not pass

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#341]
With the latest changes on CI when tests do not fail as the process keeps running and obfuscates the issues.

Ex.: https://github.com/FuelLabs/fuels-ts/runs/6867495021?check_suite_focus=true

**Comment by QuinnLee** [comment]
Feel free to cherry-pick https://github.com/FuelLabs/fuels-ts/pull/342

**Comment by QuinnLee** [comment]
Sorry for the last-minute changes - I think we should close this and open a new issue to handle the code coverage.
