### ISSUE TITLE
Stop hashing the message before signing it with the wallet

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#3427]
[Currently](https://github.com/FuelLabs/fuels-ts/blob/ad0a081473f83cee19ee0852ecd5e07341cad909/packages/account/src/wallet/base-wallet-unlocked.ts#L71), when we want to sign a message with a wallet, the message first gets hashed. This is unexpected behavior as signing shouldn't be modifying the message and has [caused](https://forum.fuel.network/t/how-to-sign-a-message-in-typescript-for-sway-smart-contract-verification/6809) people to unnecessarily make their sway code more complex for the sake of working with our SDK.

We should also change the input of the method to `BytesLike` so that people don't have to convert their `Uint8Array`s into `string`.

@bajpai244 has some additional info:
> SignMessage automatically hashes the message it receives, but what if the person using it doesn't want it to hash the message!Why would one want that? Imagine someone only has a hash and wants a signature over it; now, this will require someone to re-construct the whole payload to get a signature over the hash { otherwise, the hash will internally get hashed again! }This becomes an issue because frontend wallets don't give access to the signer, so u can only use signMessage! This becomes important for mult-party transactions, where u want someone's signature over a transaction hash, but now because of the current implementation one would have to reconstruct the whole payload first themselves, which doesn't feel like ideal DX.

> [!IMPORTANT]
> This is a breaking change.

**Comment by Torres-ssf** [comment]
Closing this issue as we need to always convert the data to `utf-8` and hash before signing; this ensures security, avoiding users being fished to sign a transaction hash.
