### ISSUE TITLE
Add docs around UTXO dismantling/consolidation

### ISSUE THREAD

**Issue by Torres-ssf** [FuelLabs/fuels-ts#3429]
Typical use cases are:
 1. Split one UTXO into several
 1. Consolidating several UTXOs into one

Examples:
- 1x UTXO with a value of `1000` could be split into 10x UTXOs, each valued at `100`
- 100x UTXOs with a value of `10` could be consolidated into 1x UTXO valued at `1000`

Notes:
- Fee must be subtracted before the split/consolidation
- Chain constraints limit the maximum number of outputs allowed per transaction

**Comment by maschad** [comment]
@Torres-ssf @arboleya perhaps I may be misinterpreting but after reading through the [combining UTXO docs](https://docs.fuel.network/docs/fuels-ts/cookbook/combining-utxos/) I think the only documentation that is missing is regarding the `maxOutputs` which are determined by the chain config. I've added that to the docs in [this PR](https://github.com/FuelLabs/fuels-ts/pull/3435)
