### ISSUE TITLE
Create a way to externalize a graphql query builder

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#347]
As a SDK user I should be able to create app-specific queries to the provider.

Today if the users want to do some query different from the ones provided by default on the `@fuel-ts/provider` he needs to setup all the infra to use a nice `graphql queries`.

Use case:
On SwaySwap I want to query nodeVersion, minGasPrice, minBytePrice, consensusParameters and latestBlock, to optimize queries I also want to do everything in one query. Todo it I had to write it using fetch wich works but is not the best experience.

```ts
const chainConfigQuery = `query {
    nodeInfo {
      minGasPrice
      minBytePrice
    }
    chain {
      consensusParameters {
        gasPriceFactor
      }
      latestBlock {
        height
      }
    }
  }`;
  const chainConfigResponse = await fetch(FUEL_PROVIDER_URL, {
    method: 'POST',
    headers: {
      accept: '*/*',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      operationName: null,
      variables: {},
      query: chainConfigQuery,
    }),
  }).then<{ data: ChainConfig }>((resp) => resp.json());
  return chainConfigResponse.data;
```

**Comment by AlicanC** [comment]
On SwaySwap and especially on BlockExplorer, we shouldn't do queries like this. In an ideal setup we would have a GraphQL compiler that would read these queries and optimize them and maybe even do [Persisted Queries](https://relay.dev/docs/guides/persisted-queries/). When you programmatically build these queries it becomes impossible for the build tools to optimize them.

**Comment by digorithm** [comment]
@luizstacio should we close this one?

**Comment by luizstacio** [comment]
> @luizstacio should we close this one?

This feature is related to creating an API for users to write custom queries to the provider, instead of relying only on the queries provided by the SDK Provider.

But, I think the DApps could also connect directly to the Graphql API using tools like what @AlicanC mentioned these solutions are more flexible than if we try to provide them via SDK.

Let's close for now.
