### ISSUE TITLE
Add Example Node App

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#35]
Add an example Node.js app that uses fuels-ts.

- [ ] Add example Sway contract
- [ ] Add a script to publish the contract
- [ ] Add a script that generates TS types/code from contract
   - Blocked by https://github.com/FuelLabs/sway/issues/322
- [ ] Add an Express app (80% usage in [State of JS 2020 Back-end Frameworks](https://2020.stateofjs.com/en-US/technologies/back-end-frameworks/))
- [ ] Add Jest tests (68% usage in [State of JS 2020 Testing](https://2020.stateofjs.com/en-US/technologies/testing/))

**Comment by matt-user** [comment]
Should we close this issue?  @luizstacio updated the docs with the [quickstart](https://github.com/FuelLabs/fuels-ts/pull/425) and we have the sway-apps repo.

**Comment by luizstacio** [comment]
> Should we close this issue? @luizstacio updated the docs with the [quickstart](https://github.com/FuelLabs/fuels-ts/pull/425) and we have the sway-apps repo.

I think this would be more on the back-end side, like an API that creates TXs the quickstart is more focused on the front-end side.

**Comment by digorithm** [comment]
I believe this one should be closed; plenty of docs out there with example apps using the TS SDK. Feel free to reopen if that's not the case!
