### ISSUE TITLE
Consider removing benchmarks and codspeed

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#3502]
Codspeed turned out not to be the best option for our use case of monitoring network latency/roundrips. Because everything runs locally and variations are in the house of milliseconds, we have many false negatives that backfire on the initial intention. We can achieve better and faster results if we go with something manual.

**Comment by adriencaccia** [comment]
Hey @arboleya, indeed the default CPU instrument of CodSpeed might not be the best tool for this use case.

We released our new [Walltime instrument](https://codspeed.io/changelog/2024-11-27-walltime-instrument-and-codspeed-macro-runners) that is specially designed for benchmarks with I/O.
Feel free to check it out, and let me know if you are interested 😉
