### ISSUE TITLE
trying to setup the project fails at pnpm install when using PowerShell on Windows

### ISSUE THREAD

**Issue by nedsalk** [FuelLabs/fuels-ts#375]
### What version of fuels-ts are you using?

0.7.0

### Steps to Reproduce

Open a terminal and try to install the project's dependencies:

```sh
git clone git@github.com:FuelLabs/fuels-ts.git
cd fuels-ts
pnpm install
```

### Expected Behavior

The installation process should finish without failure.

### Actual Behavior

The installation process fails with the following message:
```sh
packages/forc-bin install$ ./dist/install.js
│ '.' is not recognized as an internal or external command,
│ operable program or batch file.
└─ Failed in 36ms
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by adlerjohn** [comment]
I can't repro on my machine. What version of `pnpm` are you using, and are you using Linux?

**Comment by nedsalk** [comment]
Tried it with pnpm v7.3.0 and v7.5.0 on WSL 2 and with PowerShell.

**Comment by Muhamedkaric** [comment]
The problem with windows is not easy to solve...
For example in forc-bin/package.json there is install script: "./dist/update.js" on windows this path cannot be resolved.
To fix this you can say: "install": "node dist/install.js". This is fine for all os. 
But there is another issue this installation script will call shared.ts (function getPkgPlatform) where it is explicitly defined that only mac and linux users are allowed to do this installation and you will get "win32 not supported" or "win64 not supported".
The way to solve this issue (I hope so) is to provide zip files on https://github.com/FuelLabs/sway/releases/download and then in forc-bin/src/install.ts you should support extraction for zip files. Currently as you can see in install.ts you have only 4 filename combinations of tar.gz. on this source 
  
![Screenshot_1](https://user-images.githubusercontent.com/36570905/184530232-b624840e-1333-4f39-a117-afccbd99a0d9.png)

**Comment by Torres-ssf** [comment]
Closing as low priority
