### ISSUE TITLE
Pick framework and deploy`fuels-ts` docsite

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#387]
### Motivation

Onboarding new users can be difficult.  If we have a docsite to answer questions and provide examples this can help onboard new users.  First pass is to pick a template and deploy

Checklist

- [ ] Pick Docsite template
- [ ] Deploy as github pages with GH actions

**Comment by luizstacio** [comment]
I think the current `typedoc` can do the job well also, it handles custom pages and menus: https://github.com/FuelLabs/fuels-ts/blob/master/docs/index.md.

Also, the docs are going to autogenerate on each release #123, PR: #406
