### ISSUE TITLE
Create a CRA-like example on `code sandbox` 

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#389]
### Motivation

Adding more code samples will allow users to get onboarded.  This issue is to create a sandbox template on code sandbox where a dev can explore the SDK and tooling.

Goal

- [ ] Build a Fuel code sandbox template with all tooling 

### Possible implementations

Should investigate adding a custom Docker image with a local Fuel Node: https://codesandbox.io/docs/environment

**Comment by danielbate** [comment]
Closing as we now have the fuels CLI and scaffolding tools, with further examples in the `apps` directories.
