### ISSUE TITLE
Add `type-fest` to `typechain` definition files

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#390]
### Motivation

We are currently using `type-fest` in the `abi-encoder`; we should also use these for certain complex types.

e.g.

- [ ] Update enums
- [ ] TODO find more

**Comment by QuinnLee** [comment]
@JC - What's your take? I think this is a good idea but want to validate using `type-fest`.  If it's a dependency in the SDK, the user should already have it in the node_modules.

**Comment by luizstacio** [comment]
I think it could add some complexity to the setup.

These are going to add a lot of conveniences? Or just replace the Enum for now?

Maybe it would be good if we could export the used types inside the generated files, and not require to install.
