### ISSUE TITLE
Create aggregate release tag with changeset publish

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#438]
Today when the release PR (ex.: #432) is merged, it creates a git tag for each package. The desired behavior is to create a single tag for the entire version and generate a single release changeset.

**Comment by pedronauck** [comment]
This is one of trade-offs I saw a lot of people complain about changesets, I saw once @davidkpiano talking about this 😕

**Comment by luizstacio** [comment]
> This is one of trade-offs I saw a lot of people complain about changesets, I saw once @davidkpiano talking about this 😕

https://github.com/changesets/action/pull/193
