### ISSUE TITLE
Create a standard way to treat logs.

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#444]
Today on the SDK, we have some places using `logger` from `@ethersproject` and others using plain `console.log`. We should make a standard and fix all places to use the same.

**Comment by QuinnLee** [comment]
I think we should use `logger` (or equivalent) over `console.log`

**Comment by arboleya** [comment]
Agreed - closing it.

@luizstacio Please reopen if you think something else is still required.
