### ISSUE TITLE
Improve documentation page

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#450]
- [ ] Overview of how each package work
  - [ ] How to create a Wallet
    - [ ] Transfers
    - [ ] Check balances
  - [ ] How to call a Contract
    - [ ] Call a simple method
    - [ ] Call a read-only method
    - [ ] Simulate transaction
    - [ ] Estimating transaction Fee
  - [ ] How to create a TX
    - [ ] How to create a custom script
    - [ ] How to handle inputs/outputs etc
    
 > Each topic can be created as a separate PR / ISSUE.

**Comment by digorithm** [comment]
Closing this because the new TS SDK doc has been released.
