### ISSUE TITLE
Add contract inputs automatically by simulate tx

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#462]
When doing a transaction, the user sometimes will need to add  `contract inputs`  in cases where the scripts interact with multiple contracts.

To make it easier, we should implement an exhausting iteration, where it's possible to emulate a transaction, parse the errors, and change the tx by adding contract inputs until the tx stop failing.

To achieve this, we also need to ensure the fuel node returns the proper errors when a variable or contract input is missing and what values it expects.

The support for `contractId` on panic errors are been implemented here: https://github.com/FuelLabs/fuel-tx/pull/198

**Comment by QuinnLee** [comment]
@digorithm Does the rust sdk have contract we can resuse to test against this?

**Comment by digorithm** [comment]
> @digorithm Does the rust sdk have contract we can resuse to test against this?

Not really, at least not yet, we're also on working on something like this on the Rust side!

**Comment by luizstacio** [comment]
https://github.com/FuelLabs/fuel-specs/pull/409

**Comment by luizstacio** [comment]
https://github.com/FuelLabs/fuels-rs/issues/596 this one will help on the variable outputs estimation

**Comment by luizstacio** [comment]
PR open for contract id: https://github.com/FuelLabs/fuel-tx/pull/195

**Comment by QuinnLee** [comment]
Just to confirm this is for `simulate()` calls, not `dryRun` aka `.call()`

**Comment by luizstacio** [comment]
> Just to confirm this is for `.simulate()` calls, not `dryRun` aka `.call()`

I think we should incorporate the `dryRun` we run right before doing the transaction to get the `gasUsed` and add some flags to disable and also pass the max number of iterations.

**Comment by QuinnLee** [comment]
Moved this out of `blocked`
