### ISSUE TITLE
Add `Vec<T>` Support as an `Output`

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#487]
### Description
Iterate through the structure and log its contents, then parse those receipts

```rust
fn echo_u8_vector(input: Vec<u8>) -> Vec<u8> {
    let mut i = 0;
    while i < input.len() {
      log(input.get(i).unwrap());
      i += 1;
    }
    
    input
}
```

- The vector length will be retrieved from the returned `Vec` `struct` property `len` (`input` in above example)
- In above code, the vector data will be inside the log as items with type `ReceiptTypeReturnData`
- See [`LogReader`](https://github.com/FuelLabs/fuels-ts/blob/56b635db91cdb3d4d4f3a44d2ebab425b5b596f1/packages/providers/src/LogReader.ts), perhaps we can add there or reuse some of the code

Details: https://github.com/FuelLabs/fuels-rs/issues/353

See also #434 and #497 

### Initial checklist
- [ ] Call a contract fn and receive a Vec<T> as return data in logs
- [ ] TBD Generate the correct `Type` using `Typegen` for the `Vec<T>` Output

See also #434

**Comment by luizstacio** [comment]
We should add some documentation on how to structure the contract to use Vec outputs. This could be on the README.md of the package contract. And also, have a page under the menu -> `Working with vectors`.
