### ISSUE TITLE
Update or deprecate quickstart guide

### ISSUE THREAD

**Issue by supiket** [FuelLabs/fuels-ts#514]
The [README.md quickstart](https://github.com/FuelLabs/fuels-ts#quickstart) points to [fuels-ts quickstart docs](https://fuellabs.github.io/fuels-ts/QUICKSTART.html). 
Following this guide strictly results in `error=enough coins could not be found` when attempting to call the `increment` function.

Update or deprecate the docs to fix this issue.

One suggestion is to reflect the updated way of creating a wallet and running a node, as in [The Fuel Book's Developer Quickstart](https://fuellabs.github.io/fuel-docs/master/developer-quickstart.html), that is: 
- Using [forc-wallet](https://github.com/FuelLabs/forc-wallet#forc-wallet) and
- Running a testnet node with `forc deploy --url https://node-beta-1.fuel.network/graphql --gas-price 1`

instead of what is suggested in the current `fuels-ts` quickstart guide, that is:
- Setting `initial_state` in the `chainConfig.json` file
- Running a local node with `fuel-core run --ip 127.0.0.1 --port 4000 --chain ./chainConfig.json`

**Comment by luizstacio** [comment]
The quickstart is focused on local development, did you try to deploy or connect in a different network? Folowing the steps here looks to be working correctly.

**Comment by luizstacio** [comment]
@QuinnLee or @camsjams can you also try the quickstart locally to see if it works as expected?

**Comment by supiket** [comment]
@luizstacio are you able to call the `incerement` function without getting insufficient coins error?
