### ISSUE TITLE
Refactor Interface, Contact, etc to use Flat ABI

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#520]
### Motivation

Currently, we allow both nested and flat ABI.  However, this is causing our code to be harder to maintain.  Going forward, we should support the Flat ABI and refactor the code path.

The following are types that can be simplified.

- [ ] `ParamType`
- [ ] `JsonFragment`
- [ ] `FunctionFragment`

**Comment by arboleya** [comment]
Will this require updating the current code templates we use when generating Typescript files via `fuelchain`?

**Comment by arboleya** [comment]
> I am refactoring the whole type's generation stuff [...]

FYI — [here](https://github.com/FuelLabs/fuels-ts/tree/aa/typegen-revamp/packages/abi-typegen/src/templates) are the templates on the new [branch/PR](https://github.com/FuelLabs/fuels-ts/pull/570) I started.

**Comment by arboleya** [comment]
The new `typegen` should cover the majority of improvements and fixes.

New proposals can be made in the future, but I'll close this one since it isn't clear enough.

> **My understanding**: _The general suggestion here seems to reduce the generated code by using more type helpers_.
