### ISSUE TITLE
Missing name in ABI gives "Can't guess class name, please rename file"

### ISSUE THREAD

**Issue by FossilFrank** [FuelLabs/fuels-ts#521]
### What version of fuels-ts are you using?

0.16.0

### Steps to Reproduce

My ABI has the following function def:

```
    {
      "inputs": [],
      "name": "get_tokens",
      "output": {
        "name": "",
        "type": 1,
        "typeArguments": null
      }
    },
```

Parsing this gives me the error `Can't guess class name, please rename file:`

### Expected Behavior

Generate output successfully

### Actual Behavior

`Can't guess class name, please rename file:`

----------

If I add an output name like this, then it works correctly:
```
    {
      "inputs": [],
      "name": "get_tokens",
      "output": {
        "name": "tokens",
        "type": 1,
        "typeArguments": null
      }
    },
```

**Comment by QuinnLee** [comment]
Thanks for the bug report, can you add the full JSON abi by chance?

**Comment by QuinnLee** [comment]
I can't replicate this with the newest version of the SDK `v0.21.x` - I'm going to close it for now but will keep an eye on this

**Comment by FossilFrank** [comment]
Yep, just confirmed that this issue is fixed in newer versions :)
