### ISSUE TITLE
Configure-time constants

### ISSUE THREAD

**Issue by QuinnLee** [FuelLabs/fuels-ts#529]
Tracking https://github.com/orgs/FuelLabs/projects/17/views/2 on TS side
Sway currently supports constants declared in Forc.toml, e.g.:

[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "oracle"

[constants]
# Change to an Identity once https://github.com/FuelLabs/sway/issues/2647 is fixed
owner = { type = "b256", value = "0x09c0b2d1a486c439a87bcba6b46a7a1a23f3897cc83a94521a96da5c23bc58db" }

[dependencies]
The SDK must offer support for this feature so that users can, in their Rust code, set the value of a constant and deploy the contract without the need to recompile the code.

To achieve this, the compiler will output a new piece of data (e.g., a new file similar to the JSON ABI) that will tell us the type of the constant, name (? tbd), and its location in the compiled bytecode. With this information, the SDK should inject that constant's value into the compiled bytecode before deploying it.

Note that there will be more discussions on the specifics of how this is going to be achieved. The Sway compiler currently blocks this work until then.

**Comment by digorithm** [comment]
It's finally time to address this on the TS SDK. The Rust SDK already does it: https://rust.fuel.network/v0.41.0/contracts/configurable-constants.html

We should do something similar for the TS SDK as well.

**Comment by arboleya** [comment]
@Torres-ssf Let me know in case this requires changes on the Typegen.

I'm guessing it does not, but I can help you if something is needed.
