### ISSUE TITLE
Test breaking when PR comes from a fork

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#538]
### What version of fuels-ts are you using?

0.17.0

### Steps to Reproduce

open a PR from a fork

### Expected Behavior

tests should work

### Actual Behavior

`ArtiomTr/jest-coverage-report-action`

this action doesn't support PR from forks. it breaks when trying to compare with `master`, blocking the PR

Blocks: #500

**Comment by arboleya** [comment]
I believe this one was fixed via #601.

**Comment by LuizAsFight** [comment]
yes @arboleya thanks !
