### ISSUE TITLE
CI tests: Add a process to build, pack and install the libs on each PR

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#568]
Today it's possible to open a PR that passes all tests but has issues after the built version for release. The idea here is to add a CI step to run;
- build the packages
- pack the packages
- install from the packed version
- run a project with  this packed version
  - In this step, we could have a simple Node.js
  - And a simple front-end app running on browser env. Ref.: #284

**Comment by arboleya** [comment]
This is a real-world example of a problem that would have been caught in time before release:
 - https://github.com/FuelLabs/fuels-ts/pull/815

**Comment by danielbate** [comment]
@petertonysmith94 @Dhaiwat10 should this have been completed as part of #2489.

**Comment by petertonysmith94** [comment]
@danielbate we're installing the published version to `create-fuels` as part of the integration tests so I'm going to mark this as complete :)

Reference:
- https://github.com/FuelLabs/fuels-ts/pull/2489
