### ISSUE TITLE
Review support for types from `sway-lib-std`

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#586]
We need to consider supporting types from the sway `stdlib`. 

A good start would be to make a list of all types to be implemented.

Then understand if it's a matter of `abi-typegen` only or if something else (`abi-coder`?) is needed.

Please, refer to these requests made on the rust SDK:
 - https://github.com/FuelLabs/fuels-rs/issues/661
 - https://github.com/FuelLabs/fuels-rs/issues/688

Sway STD Lib:
 - https://github.com/FuelLabs/sway/tree/master/sway-lib-std/src

> _This issue might be split into smaller ones if needed._

**Comment by arboleya** [comment]
> **Note** — The code for type `b512` is being implemented on #612 and should be mirrored on #570 ([more](https://github.com/FuelLabs/fuels-ts/pull/570#discussion_r1028892695)).

**Comment by danielbate** [comment]
When I did the initial work in #995, as it is a b256 wrapped in a struct and thus supported by the `B256Coder`/`StructCoder`, adding an Abi Coder type seemed unnecessary.

**Comment by arboleya** [comment]
@camsjams Yes, I opened this issue long ago during the Typegen implementation when I was poorly familiarized with everything and all these types. I was unsure of what to implement or not.

@FuelLabs/sdk-ts Feel free to reopen if you notice something went unchecked.
