### ISSUE TITLE
What encryption algorithm is used?

### ISSUE THREAD

**Issue by Jaammerr** [FuelLabs/fuels-ts#619]
I want to create own SDK in python, but what encryption algorithm does this project use? I cant find this info.

**Comment by luizstacio** [comment]
The best place to look to the SDK is on the repos, all the encryption is implemented there:
Rust lang: https://github.com/FuelLabs/fuels-rs
TypeScript: https://github.com/FuelLabs/fuels-ts

**Comment by QuinnLee** [comment]
Hi @Jaammerr 

I would look at the [fuel-specs](https://github.com/FuelLabs/fuel-specs).  First would be getting the ABI encoding and decoding.  

[Public-Key Cryptography](https://github.com/FuelLabs/fuel-specs/blob/master/src/protocol/cryptographic_primitives.md) is here too

**Comment by digorithm** [comment]
Hopefully, @QuinnLee answered your question, @Jaammerr. Closing the issue.
