### ISSUE TITLE
Add Docs Page: Cookbook

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#629]
### Motivation

This section covers more advanced use cases that can be satisfied by combining various features of the TS SDK

### Usage example

https://fuellabs.github.io/fuels-rs/v0.31.1/cookbook/cookbook.html

### Possible implementations

Copy the same examples from the Rust SDK, but make files in this repo under the unit tests folders to keep code up-to-date and tested.

**Comment by danielbate** [comment]
Closing as a cookbook has been implemented - [https://docs.fuel.network/docs/fuels-ts/cookbook/](https://docs.fuel.network/docs/fuels-ts/cookbook/).
