### ISSUE TITLE
Add Docs Page: Messages

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#630]
### Motivation

It would be nice to add documentation showing how to use Messages in various ways.

### Usage example

Get messages:
https://github.com/FuelLabs/fuels-ts/pull/515

Get all resources:
https://github.com/FuelLabs/fuels-ts/pull/589

Get Message Proof:
https://github.com/FuelLabs/fuels-ts/pull/577

**Comment by ef3n9r98** [comment]
Hi @camsjams, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by digorithm** [comment]
I'm afraid there's no such budget, at the moment, at Fuel Labs. Also, first time hearing about OpenQ -- looks neat!

**Comment by ef3n9r98** [comment]
Thanks @digorithm! @otrho juuust let me know the same thing in [#3174](https://github.com/FuelLabs/sway/issues/3174#issuecomment-1347571454) unfortunately. Keep up the great work!

**Comment by Dhaiwat10** [comment]
Will take care of this
