### ISSUE TITLE
Add contracts tooling from swayswap to fuels-ts

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#631]
### Description

Currently, on swayswap, we created a CLI tool that helps in the development cycle by making the process of building, deploying, and replacing contract IDs simpler by executing a single command.

This CLI flow works this way;
- The developer creates a config file with the following;
    - Contracts path folder
    - The output folder for the types that are going to be generated
    - A postscript that enables the auto-replace of contract IDs after the build is complete anywhere on the application.
- When executing `deploy` command;
    - Build
    - Deploy
    - Replace

This way, for example, a frontend application can be auto-refreshed with the new contract ids after a single command to build and deploy contracts changes.

SwaySwap tool: https://github.com/FuelLabs/swayswap/tree/master/packages/scripts

### Implementation expected

Port the current scripts tool to `fuels-ts` refactoring and removing specific application code, making it simple to use inside any application.

The CLI command will be following the pattern created on #570, where the CLI will be inside `fuels workspace tool` and accessible by executing `fuels contracts <command>`.

**Comment by arboleya** [comment]
Aside from the configurable options made available on the `config`, does the tool require users to follow any other specific conventions? Those could be regarding file structure, nomenclatures, or anything else that is assumed _(or expected)_ to be a certain way.

**Comment by luizstacio** [comment]
> Aside from the configurable options made available on the `config`, does the tool require users to follow any other specific conventions? Those could be regarding file structure, nomenclatures, or anything else that is assumed _(or expected)_ to be a certain way.

No, the initial idea is to be very customizable. This is why the config is also a script, not a standard JSON.

**Comment by arboleya** [comment]
Closing in favor of #1291
