### ISSUE TITLE
Bug: log data decode issue when using custom errors

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#634]
### What version of fuels-ts are you using?

v0.21.2

### Steps to Reproduce

1. Create custom errors
2. Trigger a potential error or log
3. Decode log results in a types/value length mismatch

### Expected Behavior

No error should be thrown. We've also improved logs to better understand these issues in the future: https://github.com/FuelLabs/fuels-ts/pull/632

### Actual Behavior

![image](https://user-images.githubusercontent.com/833485/204873859-08fae00e-e567-4ad3-99a2-0fdfb936472e.png)

**Comment by arboleya** [comment]
It looks like we have someone with this problem on Discord _(see the thread [here](https://discord.com/channels/732892373507375164/1034937869736878160/threads/1060499318613745734))_.

**Comment by himanshudevrani96** [comment]
Thanks I am looking for the response

**Comment by danielbate** [comment]
This was resolved in #640, we have an example test case logs a custom error using an enum, very similar to the above replication.
