### ISSUE TITLE
Mnemonic package should have a utility to check if a phrase is valid

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#648]
Currently, when a user passes a seed phrase to the mnemonic component, the component doesn't check if the phrase is valid or not and accepts any sequence of existing words on the wordlist.

We should implement a validator utility to ensure the seed phrase is valid and return true or not.

Currently, this implementation is possible by just trying to create and expect an error, but we can implement a check using the wordlist.

```ts
export function isValidMnemonic(phrase: string): boolean {
  const words = phrase.split(' ');
  const mnemonic = new Mnemonic();
  return (
    words.filter((w) => mnemonic.wordlist.includes(w)).length === 12 // size of the mnemonic
  );
}
```

**Comment by protocolwhisper** [comment]
Hey hi, the packages must be rebuilt, or do you just need the snippet?

**Comment by digorithm** [comment]
Not sure I follow your question @protocolwhisper. Do you mind elaborating further?

**Comment by protocolwhisper** [comment]
Sure, the question is if the problem is to solve the " == " operator. 
![image](https://user-images.githubusercontent.com/57886661/208178907-20fd8bea-5890-4d53-a38e-4114224a28e1.png)

**Comment by digorithm** [comment]
Oh, I believe this snippet is just a sketch of what the actual solution _should look like_; it captures the idea: each word in a phrase should be part of the wordlist provided by the `Mnemonic` class. 

The example solution provided by @luizstacio filters all words that match the words in the `wordlist` and ensure the resulting length matches the length of the mnemonic phrase standard that the SDK is using. 

You're free to explore other approaches to this solution.

**Comment by Dhaiwat10** [comment]
Let me know if you're still stuck or want me to take this on instead @protocolwhisper

**Comment by protocolwhisper** [comment]
I solved that, but I’m trying to find out if any contribution guidelines exist, perform some tests, and maybe get rid of “fs” dependency.

Here, take a look :) 

https://github.com/FuelLabs/fuels-ts/compare/master...protocolwhisper:fuels-ts:master

**Comment by arboleya** [comment]
@protocolwhisper There's the `Contributing` section on the docs:
 - https://fuellabs.github.io/fuels-ts/CONTRIBUTING.html
