### ISSUE TITLE
The fuels package has an empty readme on NPM

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#665]
We should make sure that we are pushing a readme file to the build artifacts that we publish to NPM.

https://www.npmjs.com/package/fuels

**Comment by arboleya** [comment]
I'm not sure if this is intentional or directly related to the problem, I we don't have a `packages/fuels` entry here:

https://github.com/FuelLabs/fuels-ts/blob/789ed6abb753e316e6cac43d5d3e5fda3c4dd4dd/typedoc.json#L5-L28

**Comment by Dhaiwat10** [comment]
I think what's causing this issue is the fact that all packages have a `README` file inside the respective package's source code (at `./packages/**/README.md`), apart from the `fuels` package because it has its `README` at the root of the monorepo. I think I can create a pre-publish script that copies over that `README`.

**Comment by Dhaiwat10** [comment]
https://www.npmjs.com/package/fuels

Reopening this since the issue still doesn't seem to be fixed
