### ISSUE TITLE
Methods without #[payable] annotation cannot accept coins

### ISSUE THREAD

**Issue by anton-trunov** [FuelLabs/fuels-ts#675]
### Motivation

Once https://github.com/FuelLabs/sway/pull/3450 is merged the SDK also needs to forbid accepting coins in non-payable functions. The current plan is to introduce function attributes into the JSON ABI schema to mark payable functions as such. I'm happy to take any comments/suggestions on this.

Spec issue: https://github.com/FuelLabs/fuel-specs/issues/446
Compiler change: https://github.com/FuelLabs/sway/pull/3450
fuels-rs issue: https://github.com/FuelLabs/fuels-rs/issues/742

**Comment by anton-trunov** [comment]
FYI, all the relevant PRs have been merged

**Comment by Dhaiwat10** [comment]
Picking this one up

**Comment by arboleya** [comment]
Should this change something on the Typegen land, like generating code annotations and extra type helpers?

We can sync up on this as you advance with your implementation.
