### ISSUE TITLE
Add a `CONTRIBUTING.md` to the repo

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#693]
Right now only our docs have the contributing guidelines. New contributors might not be aware of this since it's common practice to have a `CONTRIBUTING.md` on the Github repo too. (see https://github.com/FuelLabs/fuels-ts/issues/648#issuecomment-1359058152)

**Comment by arboleya** [comment]
Although GIT handles symlinks just fine, this attempt didn't work:
 - https://github.com/FuelLabs/fuels-ts/pull/694

> cc @Franqsanz

----

# Render

GitHub renders the `symlink` differently
![symlink](https://user-images.githubusercontent.com/26660/208937261-6a2bfbd4-36ee-4b68-b018-f8ee5238afe3.png)

# Click

But when you click on it, the link is not followed, just shown.

![not-following](https://user-images.githubusercontent.com/26660/208937285-fd4b7130-4172-4e84-9159-341d38cd82a6.png)

**Comment by Franqsanz** [comment]
Maybe the problem is because I am on Windows, on my PC it works fine or I did something wrong.

**Comment by arboleya** [comment]
No, you did nothing wrong. The problem is how Github renders the symlink.; instead of rendering the contents of the destination Markdown, it simply prints the path to it. So I tried the opposite [here](https://github.com/FuelLabs/fuels-ts/pull/703).

**Comment by arboleya** [comment]
The symlink didn't work. Another solution is to copy the `CONTRIBUTING.md` file inside the guide directory on a `prebuild` step, as done on #716.

**Comment by arboleya** [comment]
Notes to self:
 - Ensure `CONTRIBUTING.md` lives only inside the repo _(not the docs)_
 - https://forum.fuel.network/t/contribution-guidelines-for-ts-sdk-packages/1066/2
