### ISSUE TITLE
Add get contract balance to provider

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#696]
Today if a developer wants to know the balance of a contract, he can write a graphql query but it would be great to include it inside the SDK.

Docs ref: https://graphql-docs.fuel.network/docs/recipes/#get-an-asset-balance-of-a-contract

**Comment by digorithm** [comment]
+1. 

Likewise, we should add the same thing to the contract instance, like in the Rust SDK. i.e., add get contract balance to the contract instance.

This could be part of this same issue, as it's touching the same parts of the codebase.
