### ISSUE TITLE
Implement transaction dependencies estimation

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-ts#701]
Similar to the [Rust SDK](https://github.com/FuelLabs/fuels-rs/blob/a424a9eff6fb0e03df56b15926f6dca39f47c175/packages/fuels/tests/contracts.rs#L468), the TS SDK should be able to estimate the transaction dependencies (contract input set and variable outputs). 

This removes the guesswork of setting the variable outputs and contract input set when performing a call.

**Comment by Dhaiwat10** [comment]
I will try having a go at this one @digorithm

**Comment by Dhaiwat10** [comment]
After doing some digging around this, I found this function in our codebase: [`addMissingVariables`](https://github.com/FuelLabs/fuels-ts/blob/609d5f052e5c1e7f2a73a619ac49a76605812c51/packages/providers/src/provider.ts#L336). It does more or less what the `estimate_tx_dependencies` function from our Rust SDK does, and it is automatically called by several of TS SDK's functions like `sendTransaction`, `call` & `simulate`. So I think the TS SDK _already_ adds in any missing transaction dependencies for you. I also found [this unit test](https://github.com/FuelLabs/fuels-ts/blob/609d5f052e5c1e7f2a73a619ac49a76605812c51/packages/fuel-gauge/src/token-test-contract.test.ts#L60) titled 'Automatically adds variableOutputs` which, I believe, tests this behaviour.

Do you think we still need to create another function? I might be missing something so please correct me if I'm wrong 😅

**Comment by luizstacio** [comment]
We currently have this solution working by simulating the tx. @digorithm @Dhaiwat10, if is now possible to know missing dependencies ahead of time without the need to call the tx then the work, is to replace the current solution.

**Comment by digorithm** [comment]
Unfortunately, we still have to simulate the transaction to be able to estimate the transaction dependencies.

So, is this feature live or not? I can't seem to find the documentation for it yet!

**Comment by Dhaiwat10** [comment]
@digorithm I would say yes, but documentation around it is missing.

Our [`addMissingVariables`](https://github.com/FuelLabs/fuels-ts/blob/d0eb7a39d2d5cd59cc45fede3826a327f158d5ea/packages/providers/src/provider.ts#L344) function does the same things that the [`estimate_tx_dependencies`](https://github.com/FuelLabs/fuels-rs/blob/d7279519a26eba46311a4c8c95020d059d6f296a/packages/fuels-programs/src/contract.rs#L605) in the Rust SDK does.

**Comment by digorithm** [comment]
> @digorithm I would say yes the feature is live, but documentation around it is missing.
> 
> Our [`addMissingVariables`](https://github.com/FuelLabs/fuels-ts/blob/d0eb7a39d2d5cd59cc45fede3826a327f158d5ea/packages/providers/src/provider.ts#L344) function does the same things that the [`estimate_tx_dependencies`](https://github.com/FuelLabs/fuels-rs/blob/d7279519a26eba46311a4c8c95020d059d6f296a/packages/fuels-programs/src/contract.rs#L605) in the Rust SDK does.

Ah, I see. Then I'll ask of you two things: Can we rename `addMissingVariables` to `estimateTxDependencies`? Rationale: We should unify the nomenclature/terminology between the two SDKs. Please let me know what you think. The other thing: let's add this stuff to our docs; this is something users will often look for!

**Comment by Dhaiwat10** [comment]
@digorithm

1. Yes, I agree with the renaming suggestion because of the point you raised, and the fact that the `addMissingVariables` also adds any missing external contract IDs and not just missing variable outputs. 
2. Will add docs for this!
