### ISSUE TITLE
Create `fuel-ts/tx` package

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-ts#708]
### Motivation

Currently the SDK returns `Transaction`, `TransactionResponse` and `TransactionResult`, over 3 different requests inside provider module.
- If I need transaction `receipts`, I need to create a `TransactionResponse` and use `waitForResult` method.
- If I need transaction `graphql query` data, I cannot access it because SDK doesn't return. Only way is to build the queries in the frontend app itself
- If I need status, both `TransactionResponse.fetch` and `TransactionResponse.waitForResult` return it, but in different forms.

In order to show correct transaction data in front end, we need to apply a lot of logic, deal with this SDK different ways of getting transaction data, explore transaction specs, deal with `outputs` , `inputs` , `receipts`, process them in different ways depending on transaction type.

### First Solution

To simplify and unify things, In [fuels-wallet](https://github.com/FuelLabs/fuels-wallet) repo a collection of [tx util](https://github.com/FuelLabs/fuels-wallet/blob/master/packages/app/src/systems/Transaction/utils/tx.ts) functions was created.

- It has a `lot` of functional helpers to get whichever transaction data the user wants, and also process them depending on the type.
  - All this helpers are extensively `unit tested`, as I wanted to let it as ready as possible to go in SDK.
- for most simple cases, only `parseTx` method should be enough, returning a `Tx` object:
```
export type Operation = {
  name?: string;
  from?: Address;
  to?: Address;
  assetsSent?: Array<Coin>;
};

export type Tx = {
  operations: Operation[];
  gasUsed: BN;
  fee: BN;
  type: TxType;
  totalAssetsSent: Coin[];
  isTypeMint: boolean;
  isTypeCreate: boolean;
  isTypeScript: boolean;
  status?: TxStatus;
  isStatusPending?: boolean;
  isStatusSuccess?: boolean;
  isStatusFailure?: boolean;
  id?: string;
};
```

- It centralizes `fee` and `gasUsed` calculation.
- it returns the `operations` of the transaction

### Proposal

Create a new package `fuel-ts/tx`. This package will contain
- tx utility methods
- other methods to request transaction data 
  - `getTx` - returns tx data
    - input: `{ id: string; provider: Provider; }`
    - output: `{ gqlTransaction, transaction, tx }`
      - `gqlTransaction` is the data return from `graphql query`
      - `transaction` is the decoded transaction from `gqlTransaction.rawPayload`
      - `tx` is the parsed `Tx` returned by utility method `parseTx`
  - `getTxs` - returns list of txs
    - input: `{ provider: Provider; filters: { owner: Address; } }` <- inside filters here, we should add all filters possible to `getTransactionsByOwner` query
    - output: same as `getTx`, but a list
  - `getTxFromRequest` - this function will simulate a `TransactionRequest` and return a parsed `Tx`
    - input: `{ transactionRequest: TransactionRequest; provider: Provider; }`
    - - output: `{ transaction, tx }`

This `outputs` logic it meant to cover all scenarios the user will need. We provide final parsed `Tx`, but also provide the data we needed to use to parse it: `transaction and gqlTransaction`.
If the user need things that we don't provide in `Tx`, or needs data from `graphql query`, or needs `decoded transaction` to build some more complex use cases, he has all of this available, and also has all the other specific utility methods to help in his task.

### After
When this package gets created, some other things can de deprecated:
- some methods of `provider/utils.ts` can be removed
  - `getGasUsedFromReceipts`
  - `calculateTransactionFee` (it's also currently wrong using fixed `GAS_PRICE_FACTOR`, leading to wrong calculations)
- `fuel-ts/provider`
  - `getTransaction`
  - `getTransactionCost`
  - `TransactionResponse`

### Usage example

```
const provider = new Provider(url);
const tx = await getTx({ id: '0xdcbd3117aab0ec4a9a00f4a0f81616878140dccc3046b8fc4510fa2181d955e7', provider });
```

**Comment by protocolwhisper** [comment]
Is this solved?
