### ISSUE TITLE
Script `forc:check` fails silently

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#779]
The `pnpm forc:check` script _(and the related CI action)_ always passes, regardless of errors.

Example:
 - https://github.com/FuelLabs/fuels-ts/actions/runs/4145700900/jobs/7170416899#step:4:14

<details>
  <summary>Screenshot</summary>

![ci](https://user-images.githubusercontent.com/26660/218167629-4c4ee18d-dd38-4d88-a0be-7bd1aabca76e.png)

</details>

**Comment by digorithm** [comment]
Should this be closed?

**Comment by arboleya** [comment]
No, it hasn't been addressed yet.

**Comment by arboleya** [comment]
The problem is with this script, which seems to have _never_ worked since it'd always `exit 0` regardless.

I pushed a quick fix here:
 - https://github.com/FuelLabs/fuels-ts/pull/1300

Now, it [fails](https://github.com/FuelLabs/fuels-ts/actions/runs/6329057387/job/17188571857?pr=1300#step:4:678) as expected, and it's a matter of fixing all poorly formatted files.

Any help is appreciated. 🙏
