### ISSUE TITLE
Implement transaction subscriptions

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#782]
Currently, the `fuel-core` implements a solution to improve transaction status monitoring via GraphQL Subscriptions. This new approach enables us to improve the current "expanding backoff" approach on `TransactionReponse.waitFor...`, where we query transactions on a timely basis before the status change to use subscriptions and avoid multiples request.

Note: We could use two strategies, `expanding backoff` and `subscribe`, to work on config bases giving the option to developers to pass wich strategy to be used. The default should be `subscribe`.

**Comment by Dhaiwat10** [comment]
@luizstacio are you aware of any ways to get our GraphQL codegen to generate a method that would let me _subscribe_ to this subscription. I added this code to `operations.graphql`:

```gql
subscription statusChange($id: TransactionId!) {
  statusChange(id: $id) {
    __typename
  }
}
```

And this is the function it generated in `operations.ts`, which returns a _Promise_ that would resolves as soon as the status changes. This won't work like a subscription.

```ts
statusChange(
      variables: GqlStatusChangeSubscriptionVariables,
      requestHeaders?: Dom.RequestInit['headers']
    ): Promise<GqlStatusChangeSubscription> {
      return withWrapper(
        (wrappedRequestHeaders) =>
          client.request<GqlStatusChangeSubscription>(StatusChangeDocument, variables, {
            ...requestHeaders,
            ...wrappedRequestHeaders,
          }),
        'statusChange',
        'subscription'
      );
    },
```
