### ISSUE TITLE
Allow users to pay for transaction fees using predicates

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-ts#788]
Users have to use their `Wallet` to pay for a transaction. However, there are many use cases where a user wants to pass a `Predicate`, instead of a `Wallet`, to pay for a transaction. The actual UTXOs used to pay for the transaction must be unlocked in the predicate passed. 

For example: 

```ts
const contract = ExampleContractAbi__factory.connect(wallet);

let response = await contract
    .functions
    .initialize_counter(42) // Build the ABI call
    .call() // Perform the network call
```

Here, we link a `Wallet` to the contract instance. Underneath, it will grab this wallet's funds to pay for the transaction. 

With this new feature, one could pass in a `Predicate` instead of a `Wallet`, and, underneath, the predicate would be evaluated, and, if true, the UTXOs unlocked would be used to pay for the tx fees.

This is based by a feedback we got from an external developer, here's what was said about this feature request: 

> When I want to spend utxos from a predicate, there should be a wallet that offers the same kind of features as a wallet for a simple public key address. Currently, you need to initialize the wallet with a key, and that will also be the address that pays for the fees. If I have a predicate, I generally want to pay for the fees with the coins available in the utxos on the predicate address. A public-key based address should not be required to manage a predicate wallet.

Base issue: https://github.com/FuelLabs/fuels-rs/issues/809

**Comment by arboleya** [comment]
@luizstacio How is this issue different from this other one?
 - https://github.com/FuelLabs/fuels-ts/issues/757

> cc @camsjams

**Comment by luizstacio** [comment]
> 

Issue #757 would include tests using a predicate to execute script call. Once this issue is done and also scripts are done, it would be possible to implement a Script using a Predicate as we do use Wallets.
