### ISSUE TITLE
Eslint - Treat `no-explicit-any` rule as an error

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#821]
Currently, our `eslint` _**`warn`s**_ about violations of the [`no-explicit-any`](https://typescript-eslint.io/rules/no-explicit-any/) rule.

We should treat these as **`error`s** instead and _adjust/refactor_ all current usages accordingly.

If using `any` can't be avoided, we can use an `eslint` comment to disable the rule **_explicitly_**:

```ts
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const msg: any = "any is allowed in this line";
```

> _This should ideally be a last resort thing_

**Comment by Dhaiwat10** [comment]
Will have a look at this

**Comment by Dhaiwat10** [comment]
I'll try to replace `any` with `unknown` or the relevant type wherever possible. I just had a brief look after applying this change in some places. It's gonna make us add a lot of type annotations (a lot of `x as SomeType` 😅 This will probably add more confidence to our code, though.
