### ISSUE TITLE
Dynamically fetch values of constants that rely on the environment

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#825]
This is a follow-up issue to #820. Now that we have organized our constants throughout the repo, the next step should be to making constants like `GAS_PRICE_FACTOR` dynamic and async.

https://github.com/FuelLabs/fuels-ts/blob/dd7b1cab0e7c4a5234383ce6fc34f041ee6d03a9/packages/transactions/src/consts.ts#L12-L17

Please also see #784 and #808 for more context.

**Comment by digorithm** [comment]
@Dhaiwat10 What's the status on this one? Should this issue still be open?

**Comment by Dhaiwat10** [comment]
@digorithm I think we can close this issue. We have added the supporting structure for the dynamic fetching of these constants through #1181.
