### ISSUE TITLE
Possibly new flaky test

### ISSUE THREAD

**Issue by arboleya** [FuelLabs/fuels-ts#845]
Never seen this one before (_it worked after [re-running](https://github.com/FuelLabs/fuels-ts/actions/runs/4480342044/jobs/7875965168#step:8:1195) the flow_):
 - https://github.com/FuelLabs/fuels-ts/actions/runs/4480342044/jobs/7875505933?pr=844

```
FAIL packages/fuel-gauge/src/auth-testing.test.ts
  ● Auth Testing › can check_msg_sender [with incorrect id]

    expect(received).rejects.toThrow()

    Received promise resolved instead of rejected
    Resolved to value: undefined

      46 |
      47 |   it('can check_msg_sender [with incorrect id]', async () => {
    > 48 |     await expect(async () => {
         |           ^
      49 |       await contractInstance.functions
      50 |         .check_msg_sender({ value: wallet.address.toB256().replace('a', 'b') })
      51 |         .call();

      at expect (node_modules/.pnpm/expect@29.3.1/node_modules/expect/build/index.js:105:15)
      at Object.<anonymous> (packages/fuel-gauge/src/auth-testing.test.ts:48:11)
```

**Comment by arboleya** [comment]
@Torres-ssf I don't follow — not exactly what?

You said in your comment:
 - _"After applying this change it stopped falling"_

Which I understand as:
 - _"Yes, my PR might address this by fixing its async signature"_

Also, I see that the changes you made on your PR are aligned with [Jest docs](https://jestjs.io/docs/asynchronous#asyncawait) (img below).

Did I misunderstand something?

![async](https://user-images.githubusercontent.com/26660/226741795-d4b74bb9-f185-43bf-8ae2-5b5799ad5bc1.png)

**Comment by Torres-ssf** [comment]
@arboleya Sorry, I miss read and misunderstood your question. :sweat_smile: 

Yes makes sense. As a matter of fact, I am already updating all similar occurrences.

**Comment by arboleya** [comment]
No worries, that's great!
