### ISSUE TITLE
Setup Versioned Releases

### ISSUE THREAD

**Issue by AlicanC** [FuelLabs/fuels-ts#85]
We have addressed the issue of publishing packages to NPM on https://github.com/FuelLabs/fuels-ts/issues/38, but that doesn't include proper versioning.

We should make proper releases that:
- Are published to the NPM tag `latest`
- Have proper semver-following versions
- Have changes in a CHANGELOG.md
- Make GH releases with change logs (that will appear here: https://github.com/FuelLabs/fuels-ts/releases)

**Comment by QuinnLee** [comment]
@AlicanC Can i take a stab at this? I'll write something up before I implement.

**Comment by AlicanC** [comment]
@QuinnLee yup, go for it.
