### ISSUE TITLE
Document how the `abi-coder` package works

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#907]
Most of the code for the `abi-coder` package is undocumented. Since it has several moving parts in different places, it makes it tricky to navigate the codebase when the need for maintenance or a bug fix arises.

I think we should add at least some basic documentation (maybe in the readme) outlining the encoding/decoding flow, which would make navigating and understanding the code easy.

**Comment by danielbate** [comment]
@Dhaiwat10 Are you still working on this one?

**Comment by Dhaiwat10** [comment]
@danielbate Hey mate, missed your comment on the issue. No I unfortunately completely forgot about this issue and never started working on it. Feel free to take it if you want!

**Comment by danielbate** [comment]
No worries man, ty for the update 🙌🏻
