### ISSUE TITLE
Keystore package does not work in a Node ESM environment

### ISSUE THREAD

**Issue by camsjams** [FuelLabs/fuels-ts#909]
### What version of fuels-ts are you using?

latest/ 0.39.0

### Steps to Reproduce

1. Create a Node esm project
2. Attempt to load a fuels package or util that requires `keystore`
3. The execution fails as `require` is not available

### Expected Behavior

This code should also work in esm style environments.

This block needs to support `require` for legacy support but also somehow do dynamic `import` for ESM:

https://github.com/FuelLabs/fuels-ts/blob/6c8ce489f2384de7def5daec009b6af20bc38523/packages/keystore/src/universal-crypto.ts#L22-L31

### Actual Behavior

Crashes with error message:
```bash
keystore expects a standard Web browser or Node environment. Error: Dynamic require of "crypto" is not supported
    at file:///test-fuels/bg/node_modules/.pnpm/@fuel-ts+keystore@0.39.0/node_modules/@fuel-ts/keystore/dist/index.mjs:1:231
    at file:///test-fuels/node_modules/.pnpm/@fuel-ts+keystore@0.39.0/node_modules/@fuel-ts/keystore/src/universal-crypto.ts:25:22
```

**Comment by arboleya** [comment]
I stumbled upon this issue when debugging all the CJS/ESM shenanigans at:
 - #827 

I left some annotations with a possible fix here:
https://github.com/FuelLabs/fuels-ts/blob/735bc66495ec1a37fd11593b2fad194a11973087/packages/keystore/src/universal-crypto.ts#L28-L38
