### ISSUE TITLE
Update docs w.r.t support to vector as output

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-ts#922]
Since https://github.com/FuelLabs/fuels-ts/pull/812 was merged, we have had support for returning vectors. But, in https://fuellabs.github.io/fuels-ts/guide/types/vectors.html, we still mention that returning vectors isn't supported, which is untrue. We should update the docs to reflect this.

**Comment by danielbate** [comment]
No longer blocked as we can return vectors as output, however it has some scenarios where it it is not possible which should be documented. These can be identified from tests.

**Comment by danielbate** [comment]
This will be closed by #2238, as there will no longer be any constraints on vectors.
