### ISSUE TITLE
Create a very minimal `getting started` section in the docs

### ISSUE THREAD

**Issue by digorithm** [FuelLabs/fuels-ts#961]
Currently, a new user reading the docs and trying to set up a project using the TS SDK has to find the information to get the project started in the section `generating types from ABI`; there's a bit of guessing here to find this. This type of information should be in a top-level section called "getting started" (or "setting up a project," etc., TBD).

The introduction section fails to deliver this information quickly. Instead, it redirects the user to the official Developer Quickstart, which is great, but it's not until the [frontend section](https://fuelbook.fuel.network/master/quickstart/frontend.html) that this information is delivered.

I propose we create this top-level section with the following content and flow:

0. `npx create-react-app my-app` to set up an initial react-based project
1. `yarn add fuels` or `npm install fuels --save`
2. `yarn exec fuels typegen -i ./abis/*-abi.json -o ./types`
3. Then, an example identical or similar to the one in the section `using generated types`:
```typescript
import { Wallet } from "fuels";
import { MyContract__factory } from "./types";

const contractId = "0x...";
const wallet = Wallet.fromAddress("...");
const contract = MyContract__factory.connect(contractId, wallet);

// All contract methods are available under functions with the correct types
const { transactionId, value } = await contract.functions.my_fn(1).call();

console.log(transactionId, value);
```

This top-level section intends to be concise and bring the user up to speed as quickly as possible without reading a lot of additional documentation.

**Comment by Dhaiwat10** [comment]
Thoughts on using Next.js instead of `create-react-app` for our frontend examples? I think this would be a good move because most devs use Next.js and even the official React docs recommend using it over `create-react-app`.

**Comment by arboleya** [comment]
I once suggested to @Torres-ssf we could have different _(bare minimum)_ demo applications inside the `apps` dir, which could serve as an `example` and help us validate if the SDK is playing well with such tools.

> **Warning** Only possible after #827 _(happening very soon!)_

A few demos/examples could be:

```
fuel-ts
└── apps
    ├── demo-react-cra
    ├── demo-react-nextjs
    ├── demo-react-vite
    ├── demo-vue-vite
    ├── demo-...
    ├── docs
    └── docs-snippets
```
