### ISSUE TITLE
Craft a solution for a 'centralized' changelog for the `fuels` package

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#970]
Currently, the [`CHANGELOG.md` at the root of our project](https://github.com/FuelLabs/fuels-ts/blob/master/CHANGELOG.md) is a symlink that points to the `CHANGELOG.md` file inside of the `fuels` package. Apart from the fact that GitHub does not handle symlinks properly, and instead shows this:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/39617427/235912171-50889ea3-ec24-4579-a7d5-ff7d29986ced.png">
... the `CHANGELOG.md` file inside the `fuels` package also does not contain _all_ the changes that are incorporated in our codebases. It only includes information about version bumps to other packages.

Ideally, we should have a `CHANGELOG.md` file at the root of the repo where we append any and all the changes we add to any of the child packages' changelogs.

The motivation behind this is to make it easy for SDK users to browse through our version history and see what changes happened when.

**Comment by arboleya** [comment]
I agree, but I also like the idea of a consolidated Changelog.

Perhaps a combination of all could involve:
 1. Improve the [Changelog template](https://github.com/FuelLabs/fuels-ts/issues/416) (patch changes seems useless)
 3. Add a link to the `Releases` page at the very top of it
 3. Have a consolidated `<repoRoot>/CHANGELOG.md` with the all releases combined (probably auto-[generated](https://github.com/FuelLabs/fuels-ts/issues/416#issuecomment-1201618820))

**Comment by arboleya** [comment]
Related:
 - https://github.com/FuelLabs/fuels-ts/issues/1347

**Comment by arboleya** [comment]
This should be automatically resolved by:
 - https://github.com/FuelLabs/fuels-ts/issues/2493
