### ISSUE TITLE
Add docs around different capabilities of a `Provider` instance

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#975]
The current docs for `Provider` only cover some essential features. We should add docs for the rest of the features that the `Provider` supports.

A good place to refer to for the list of these features could be [`provider.test.ts`](https://github.com/FuelLabs/fuels-ts/blob/master/packages/providers/src/provider.test.ts) since it contains unit tests for several of them.

**Comment by danielbate** [comment]
@Torres-ssf are you still working on this one?

**Comment by petertonysmith94** [comment]
@danielbate could you put my head on this one pls 🙏🏼

**Comment by petertonysmith94** [comment]
I will start on this one, however, potentially worth me looking at #1539 before this.
What do you think @danielbate?

**Comment by danielbate** [comment]
I'd recommend taking one at a time, but I believe #1444 is the highest priority given it came up in our recent discussions with the FE team

**Comment by petertonysmith94** [comment]
@nedsalk will this be resolved by #1918?

I could create a options page for the `Provider`, akin to the following [example](https://docs.fuel.network/docs/fuels-ts/cli/config-file/).

**Comment by nedsalk** [comment]
> @nedsalk will this be resolved by https://github.com/FuelLabs/fuels-ts/issues/1918?

@petertonysmith94 Yes, it should be resolved alongside that issue.

> I could create a options page for the Provider, akin to the following [example](https://docs.fuel.network/docs/fuels-ts/cli/config-file/).

You don't have to bother yourself, I'll do it when I get to it. :)
