### ISSUE TITLE
Upgrade `fuel-core` to `0.18.1`

### ISSUE THREAD

**Issue by Dhaiwat10** [FuelLabs/fuels-ts#976]
Rust SDK equivalent PR: https://github.com/FuelLabs/fuels-rs/pull/950

**Comment by arboleya** [comment]
Should `forc` be upgraded alongside `fuel-core`?

Maybe unrelated:
 - https://github.com/FuelLabs/fuels-ts/issues/982

**Comment by Dhaiwat10** [comment]
@arboleya it probably should be. I think I might even _need_ to upgrade it to get things to work properly. Let me see how this goes.

**Comment by Lukasz2891** [comment]
How about that change? Is it in progress or sth?
