### ISSUE TITLE
Typegen - Account for program types automatically

### ISSUE THREAD

**Issue by danielbate** [FuelLabs/fuels-ts#989]
Currently the default behaviour of the typegen CLI is to generate types for the contract program type:

https://github.com/FuelLabs/fuels-ts/blob/49c103b4952ce3d68efb28e3f8ba9c7d33260021/packages/abi-typegen/src/cli.ts#L16-L34

We have had a couple of questions on the forum suggesting that they would expect typegen default behaviour to account for predicates:
- https://forum.fuel.network/t/how-to-build-predicate-ad-create-abi-for-predicate/2467/4
- https://forum.fuel.network/t/cant-create-predicate-instance-following-use-type-tutorial-in-ts-sdk/2490/6

So should we adjust typegen to account for all program types? Program type can be inferred from the ABI [`programType`](https://github.com/FuelLabs/fuels-ts/blob/7af2130c12e969e8bc1fa709a8371d77c12037fe/packages/abi-coder/src/types/JsonAbiNew.ts#L8) property. The parameters could remain and act as a filter for when a single program type is required.

**Comment by arboleya** [comment]
**[TL;DR]** Currently, ABIs have no information about the program type.

----

We touched on this here:
 - https://github.com/FuelLabs/fuels-ts/pull/750#discussion_r1121555229

And also here:
 - https://github.com/FuelLabs/sway/issues/4244#issuecomment-1466671639

----

Maybe we should have an explicit issue for this on the Sway repo?

**Comment by arboleya** [comment]
@nedsalk Should we address this together with the new abi spec PR?
 - https://github.com/FuelLabs/fuels-ts/pull/2747

**Comment by nedsalk** [comment]
@arboleya we can, but I'd do it in a separate PR that can be based off of the "new ABI format" one. Also, I believe that this can bring about some breaking changes like removing `contracts`/`scripts`/`predicates` from the fuels cli if we increase the scope to cover the cli.

**Comment by arboleya** [comment]
Makes sense, better to do it in isolation.

**Comment by petertonysmith94** [comment]
This is being implemented in [TS-600](https://linear.app/fuel-network/issue/TS-600/abi-refactor-gen)

**Comment by danielbate** [comment]
Resolved by #3032
